### ISSUE TITLE
Can no longer change keybindings since #717

### ISSUE THREAD

**Issue by MarauderIIC** [michail-nikolaev/task-force-arma-3-radio#1000]
The commit that fixed #717 looks like it has removed the ability to change key bindings, making this unusable for me, a left-handed player that uses the numpad to move. Although it's possible that I'm missing something, but the code change looked like it made the keys hardcoded and they were removed from the config file.

**Comment by michail-nikolaev** [comment]
Hm... Now you could change keys using CBA menu.
