### ISSUE TITLE
Unable to keep client muted due to TFA3R

### ISSUE THREAD

**Issue by xthxne** [michail-nikolaev/task-force-arma-3-radio#1001]
Was able to narrow this issue down to the TFA3R plugin on TeamSpeak 3. 

With the plugin disabled, clients stay muted. 
If the plugin is enabled, it mutes the client for 1-3 seconds and automatically unmutes that client weather it be a blocked or muted client. 

Looks like it is happening to other people as well from the TeamSpeak forums. 
See last post.
http://forum.teamspeak.com/showthread.php/106273-Not-letting-me-Local-Mute!

Would be nice if you could look into this issue. Thanks.

**Comment by michail-nikolaev** [comment]
Yes, currently TFAR unmutes everyone every few seconds. It is required due some technical issues. So, will think how to avoid it...

**Comment by xthxne** [comment]
Thank you.

**Comment by dedmen** [comment]
Right now we can circumvent the mute by just adding a muted filter to him which will just transmit silence when the plugin processes incoming voice data.
The main issue was that we are muting dead players. And if they disconnect from teamspeak while being muted they dont get unmuted. I think! We can unmute a client shortly after he disconnected. As mutes are saved clientside that should be possible.

**Comment by dedmen** [comment]
Fixed in 1.0
