### ISSUE TITLE
BWMod related

### ISSUE THREAD

**Issue by Feivel69** [michail-nikolaev/task-force-arma-3-radio#1002]
Hello guys, I have 4 requests related to BWMod/German part of the project.

(1). Update Documentations>Classes with BWMod radios

      "tf_rt1523g_bwmod"
      "tf_rt1523g_big_bwmod"
      "tf_rt1523g_big_bwmod_tropen"
      "tf_mr3000_bwmod_tropen"
      "tf_mr3000_bwmod"

(and there is a little typo related to rhs radio ">tf_rt1523g_rhs") 

(2). ~~Add BWMod desert radios to the TFR crate~~ (done)
https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1006

(3). ~~Update German stringtable.xml~~ (done)
https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1005

(4). TFR's auto distribution goes by faction, preventing the distribution of desert camo radios to desert camo troops and wooden tarn radios to wooden camo troops, etc.
Is it possible to make the VehicleClass relevant instead of only the faction or would that require too much effort/rewriting?

Something like this? (ihavenoideawhatimdoing.gif)

BW Wooden:
(getText (configFile >> "CfgVehicles" >> typeOf player >> "VehicleClass") == "Men")

BW Desert:
(getText (configFile >> "CfgVehicles" >> typeOf player >> "VehicleClass") == "BWA3_Men_Tropen")

Thank you very much for reading and for your hard work. Sorry for my English.
Kind regards.

**Comment by Feivel69** [comment]
(2) & (3) I finished hopefully correct and with your agreement.

**Comment by kavinsky** [comment]
this is still needed @Feivel69 ?
