### ISSUE TITLE
Remove newline characters (stringtable.xml)

### ISSUE THREAD

**Issue by Feivel69** [michail-nikolaev/task-force-arma-3-radio#1008]
I removed the newline characters (~2000 characters), so the source code formation doesn't effect the ingame display anymore.

Picture:
https://img3.picload.org/image/iwiocrl/crlf.png

New stringtable.xml:
https://www.dropbox.com/s/cqeqm7jnl4kasj0/stringtable.xml?dl=0

(also added a few line breaks to each language and fixed a German sentence)

I would have pulled a request but it didn't show the removed characters so I'm not sure if a merge would inherit the changes? Kind regards.

**Comment by michail-nikolaev** [comment]
yep. try to create pull request please

**Comment by dedmen** [comment]
already Resolved in f063a5811ae50f1c3403157983325273c72db2b9
