### ISSUE TITLE
Cant hear or talk to anyone in game

### ISSUE THREAD

**Issue by Drugt3rs** [michail-nikolaev/task-force-arma-3-radio#1013]
Cant hear anyone or talk to anyone in game even standing right next to them

**Comment by kavinsky** [comment]
Can you provide more details?

**Comment by Drugt3rs** [comment]
When i downgraded from 1.50 to 1.48 hoped in game i cant hear anyone anything. everything is enabled in TS in arma 3 it looks like its working cause i can change my voice volume and looks like im talking on the radio but i cant hear anyone standing next to me or on the radio and they cant hear me talking

**Comment by kavinsky** [comment]
@Drugt3rs still happening?

**Comment by dedmen** [comment]
This happens when the Teamspeak plugin has a different filename.
