### ISSUE TITLE
TFAR - Enforce Usage work?

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#1014]
Does the editor module: TFAR - Enforce Usage work? Everyone gets long range radio regardless of what I choose.

**Comment by dedmen** [comment]
Ref: https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1099#issuecomment-247903100
userconfig might overwrite Module settings if loadorder is bad.
