### ISSUE TITLE
Error in TFAR Settings Modul

### ISSUE THREAD

**Issue by shukari** [michail-nikolaev/task-force-arma-3-radio#1016]
FILE: fn_initialiseBaseModule.sqf
LINE: 52

The line must be:
"if (([_LRradio, "tf_hasLrRadio",0] call TFAR_fnc_getConfigProperty) != 1) then {"
because all LRRadios have in Config as tf_hasLrRadio parameter 1...

Thas the wrong code:
if (([_LRradio, "tf_hasLrRadio",0] call TFAR_fnc_getConfigProperty) != 0) then {
	diag_log format ["TFAR ERROR: %1 is not a valid LR radio", _LRradio];
	hint format ["TFAR ERROR: %1 is not a valid LR radio", _LRradio];
	_LRradio = "-1";
};

Enter in LRRadio at the setiings module -> tf_rt1523g an on mission start it say that this is not a valid LSRadio ;D

Willi "shukari" Graff

**Comment by michail-nikolaev** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_initialiseBaseModule.sqf#L52

**Comment by michail-nikolaev** [comment]
Thanks!

**Comment by dedmen** [comment]
This is so easy to solve why does it lay around that long.
