### ISSUE TITLE
Re-broadcast stations

### ISSUE THREAD

**Issue by AtomicTim** [michail-nikolaev/task-force-arma-3-radio#1018]
In large maps such as Al Rayak, with the main airbase up in the top right corner, it is really hard, almost impossible to transmit messages to and from ground troops. Most missions on this map the unit I am in has run have involved ground forces being 10-18km way, and that doesn't even fully cover the expanse of the map.
A re-broadcasting station feature would be incredibly useful in situations like this.
My thoughts would be an object you could place down somewhere, that increases the range of transmissions on certain frequencies. Having it sling loadable would be ideal too.

**Comment by AtomicTim** [comment]
Do functions that would enable this already exist? If they do, and with some pointing to them, I could try to implement this.

**Comment by jokoho48** [comment]
i think you can do this with 
`player setVariable ["tf_sendingDistanceMultiplicator", 0.5]`
and
`player setVariable ["tf_receivingDistanceMultiplicator", 2]`

**Comment by rogerxxxx** [comment]
Your "rebroadcast stations" in reality are called Repeaters.

This should be extremely easy to implement, if not already implemented.  All you're doing is copying/rebroadcasting (ie. repeating) what is being heard via one frequency and repeated on another frequency.  (I'm not sure if one can repeat on the same frequency though, however within the game, this probably doesn't matter and would just further complicate requiring players to enter additional frequencies for using other repeaters.)

**Comment by AtomicTim** [comment]
Thanks for the advice guys I'll get back to you with my attempts

**Comment by rogerxxxx** [comment]
FYI: See Issue #603 Radio rebroadcasting

**Comment by kavinsky** [comment]
closed in favor of #603
