### ISSUE TITLE
Entering *Some* vehicles causes TFAR to crash

### ISSUE THREAD

**Issue by Phantasmogasm** [michail-nikolaev/task-force-arma-3-radio#1019]
Several players on my server including myself have experienced a strange issue with TFAR 0.9.8, when entering certain vehicles like the A3 Gorgon, or the RHS Bradley, TFAR seems to semi crash, the player gets moved back to the channel they were in before TFAR pulled them into the task force radio channel, the plugin shows connected Y play N attempting to move yourself manually back into the TFR channel results in you being able to hear everyone in game as though it was a normal teamspeak channel regardless of distance or frequency, upon exiting the vehicle TS quickly switches you back to the TFR channel and it begins to work normally. this is repeatable by re-entering the vehicle. this only seems to affect some players. re-downloading TFAR both client side and server side does not seem to have fixed it.

TS 3.0.18.2
TFAR 0.9.8 (play with six)
A3 Server 1.52.132676

**Comment by michail-nikolaev** [comment]
hm... anything similar is such vehicles?

**Comment by Phantasmogasm** [comment]
no idea. Its happened on at least 2 separate game days, with more than one person being affected. however each time there was about 30 players on the server, when i test the same vehicles with the server empty it doesnt have the same effect. maybe it has something to do with high server load or something along the lines of.

**Comment by michail-nikolaev** [comment]
Please keep me infrormed about next games and resutls..

2015-10-27 23:03 GMT+03:00 Phantasmogasm <notifications@github.com>:

**Comment by Phantasmogasm** [comment]
no further instances have been seen in our ops, will let you know if we see it again.
