### ISSUE TITLE
Is Linux supported Server Side

### ISSUE THREAD

**Issue by RaJiska** [michail-nikolaev/task-force-arma-3-radio#1022]
Hello there,

I'd like to know if Linux is supported server side as currently the folder 'Arma 3/@task_force_radio' which is as far as I know supposed to be putted server side, however it's .dll and Linux only does handle .so. Does it actually only runs on Windows ?

Thanks.

**Comment by kavinsky** [comment]
the dll its only for clients.

**Comment by RaJiska** [comment]
Awesome, then another question would need to be asked: is there something triggered server side ?
If not, how would one be able to ensure the client has Task Force loaded and initiated during the game session ?

Thank you.

**Comment by kavinsky** [comment]
you should add TFAR Module to the mission.
