### ISSUE TITLE
Radio distance

### ISSUE THREAD

**Issue by UpperM** [michail-nikolaev/task-force-arma-3-radio#1023]
Hi ! I have update task force on my server and i want to have a larger zone to communicate with the personnal radio. I made alot test with your API but nothing work !
 
 
My test in the Init.sqf
 
player setVariable ["tf_sendingDistanceMultiplicator", 20, true];
player setVariable ["tf_receivingDistanceMultiplicator", 20, true];
 
----------
 
player setVariable ["tf_sendingDistanceMultiplicator", 20.0];
player setVariable ["tf_receivingDistanceMultiplicator", 20.0];
 
---------
 
player setVariable ["tf_sendingDistanceMultiplicator", 30];
player setVariable ["tf_receivingDistanceMultiplicator", 30];
player setVariable ["tf_terrain_interception_coefficient", 30];
 
Do you have an idea why it's doesnt work ?

**Comment by michail-nikolaev** [comment]
set tf_receivingDistanceMultiplicator to 1.0
set tf_terrain_interception_coefficient to 5

**Comment by UpperM** [comment]
And my players can speak on all the map with personal radio ? Thank

**Comment by michail-nikolaev** [comment]
@UpperM yes, it should work
