### ISSUE TITLE
Use of Task Force Radio within a Single Editor Session

### ISSUE THREAD

**Issue by rogerxxxx** [michail-nikolaev/task-force-arma-3-radio#1024]
Quite simply, can users debug/test Task Force Radio within a single Editor session?  If so, are there instructions?

Or is the only method of debugging/testing is setting up a server?

**Comment by michail-nikolaev** [comment]
You could use debug mission from sources to check things like UI and so on. To check real broadcastng it is required to create server (probably local).

**Comment by rogerxxxx** [comment]
Within the real world, we can easily test by having a second radio nearby.

Transmit on one radio, and listen via the second radio.

**Comment by rogerxxxx** [comment]
Within the real world, we can easily test using two radios.  Transmit on one radio, while listening to the second radio.

From what I'm guessing, the Task Force Radio program requires the ARMA 3 server, and uses the input and output channels of the server in order to function.
