### ISSUE TITLE
WIKI: TFAR_fnc_setVoiceVolume;

### ISSUE THREAD

**Issue by shukari** [michail-nikolaev/task-force-arma-3-radio#1025]
In the wiki and the header it says the usage is: 
*/
        [...]
        Example:
		[30] call TFAR_fnc_setVoiceVolume;
 */

But it use _this and not (_this select 0) or params ["volume"]:
#include "script.h"
TF_speak_volume_meters = TF_max_voice_volume min _this;

So "30 call TFAR_fnc_setVoiceVolume;" is the right one at the moment...

Willi "shukari" Graff

**Comment by michail-nikolaev** [comment]
thanks!
