### ISSUE TITLE
Only Generic Incorrect Version Error if no userconfig/taskforceradio/radio_settings.hpp

### ISSUE THREAD

**Issue by rogerxxxx** [michail-nikolaev/task-force-arma-3-radio#1026]
If there is no "C:\Program Files (x86)\Steam\SteamApps\common\Arma 3\userconfig\task_force_radio", then only a generic error will be printed within the 3D game world, stating "Incorrect version, ... etc."

After enabling logging (on by default) or removing "-noLogs " parameter, then there is a prompt stating no radio_settings.hpp file.  However, the user still needs know where this radio_settings should be placed.

1) When "-noLogs" is used, preventing the "no radio_settings.hpp" file to be printed to the screen, the "Incorrect version, ... etc" pop-up within the 3D game likely needs to be more specific.  If a specific error message cannot be generated, then I would suggest also appending "Please remove -noLogs parameter from your executable for further debugging." to the 3D in-game error.

2) I'm not sure if the ReadMe.txt states anything concerning the default location of the radio_settings.hpp file.  On prior versions, I had mine located within my "My Documents" folder!

**Comment by kavinsky** [comment]
userconfig file its already deprecated on upcoming versions. so no more errors or readme updated needed :)
