### ISSUE TITLE
ARMA 1.54 & TFAR : Stuck in loading screen

### ISSUE THREAD

**Issue by havena** [michail-nikolaev/task-force-arma-3-radio#1028]
tfar are not compatible with arma3 1.54 !
player stuck in loading screen.

no idea what cause this. no RPT error

**Comment by michail-nikolaev** [comment]
wooh, will check moarning...

**Comment by havena** [comment]
my bad !

i have add a  waitUntil {sleep 0.1;!isNil "pv"}; in TFAR_fnc_TaskForceArrowheadRadioInit for prevent player to load before load mission script.. and this stuck with 1.54, i just move it to TFAR_fnc_ClientInit and its work perfectly.

**Comment by kavinsky** [comment]
![Pheww](http://cdn.meme.am/instances/43806532.jpg)
