### ISSUE TITLE
move from TaskForceRadio channel is broken?

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#1033]

**Comment by ArMaTeC** [comment]
would be nice to set a default exit room

**Comment by Skaronator** [comment]
works fine for me (CBA 1.1.23 & TFAR 0.9.8)

**Comment by kavinsky** [comment]
Channel must not have spaces in order to work.

**Comment by dedmen** [comment]
@kavinsky where does that error come from? And are you sure?
My group uses a channel named "ArmA 3 (mit TFAR)" which has 2 spaces in it and it works fine.
Also disconnecting from TFAR and moving back out of the channel works fine AFAIK.

**Comment by kavinsky** [comment]
i tried this long time ago, and moving only worked for me when you use no spaces name but i cant confirm atm, maybe its fixed.

**Comment by dedmen** [comment]
I dont know what would cause this. The Teamspeak Plugin should handle strings with spaces just fine.

**Comment by kavinsky** [comment]
ill try to recreate it this week.

**Comment by kavinsky** [comment]
Not broken, working.
