### ISSUE TITLE
Radios missselect on active usage

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#1035]
акая проблема возникает, когда общаешься по дв и по кв активно. Кнопки зажимаешь правильные и индикация верная(картинка рации и частота), а говоришь ты в дв, а не в кв или на оборот...

**Comment by dedmen** [comment]
This has been fixed in 1.0. I'm sure there was a duplicate issue somewhere that talkes about this. The rewrite of the hotkey handler probably fixed it.
