### ISSUE TITLE
Block frequencies.

### ISSUE THREAD

**Issue by webzi** [michail-nikolaev/task-force-arma-3-radio#1037]
Hi,

Is it possible to do so for example.

60-60.9 is blocked for civ, so only guer/west faction can use those frequencies? 

Been trying to puzle this together, but can´t make it work.

[] spawn
{
	if(side player == civilian) then {
		while {true} do {
				_wtfno = call TFAR_fnc_haveSWRadio;
				if(_Wtfno) then {
					_channel = (call TFAR_fnc_ActiveSwRadio) call TFAR_fnc_getSwChannel;
					_channel = _channel + 1;
					_curfreqsr = [(call TFAR_fnc_activeSwRadio), _channel] call TFAR_fnc_GetChannelFrequency;
					_curfreqsr = parseNumber _curfreqsr;
					if(!isNil "_curfreqsr") then {
						if( _curfreqsr > 60 && _curfreqsr < 61 ) then {
							hint "60.1 - 60.9 are blocked frequencies.";
							[(call TFAR_fnc_activeSwRadio), _channel, "60"] call TFAR_fnc_SetChannelFrequency;
						};
					};
				};

**Comment by michail-nikolaev** [comment]
any errors on start?
