### ISSUE TITLE
Vehicle long-range problem

### ISSUE THREAD

**Issue by Silente13** [michail-nikolaev/task-force-arma-3-radio#1039]
Hello! How can i set the long range radio into the vehicle?

**Comment by kavinsky** [comment]
You mean in a addon you are making? or in a mission

**Comment by Silente13** [comment]
Im doing a server of Alits Life with some addons inluding some mod. I dont know if you mean this, but my problem is that: i don't know how setting the long range radio into the veichle.

**Comment by michail-nikolaev** [comment]
Is it helps you: https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-For-developers

**Comment by Silente13** [comment]
In userconfig or in other file?

**Comment by michail-nikolaev** [comment]
in mod config...
