### ISSUE TITLE
TF_terrain_interception_coefficient

### ISSUE THREAD

**Issue by Rattray96** [michail-nikolaev/task-force-arma-3-radio#1040]
How can I make it so hill will not affect players radios. can this be added server side ? so will I have to edit the mod and re upload to a wedsite for people to download ?
By Default: TF_terrain_interception_coefficient 7.0
To disable would I change the 7.0 to 1.0 or somthing ?

**Comment by kavinsky** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Variables

**Comment by Rattray96** [comment]
Where do I edit the TF_terrain_interception_coefficient and do I have to edit it on server and client side ?

**Comment by michail-nikolaev** [comment]
yes, change to 0.1

Also, you could set this variable on server in mission.
