### ISSUE TITLE
allowedHTMLLoadURIs

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#1041]
CfgCommands { allowedHTMLLoadURIs[] += { "*radio.task-force.ru*" }; };

**Comment by dedmen** [comment]
I dont see this used in any scripts. If its not needed why add it?
HtmlLoad is never used in the code.

**Comment by kavinsky** [comment]
on earliest versions was a dialog on the main game menu with news about updates of TFAR. but this is right deprecated.

**Comment by dedmen** [comment]
Closing this as its deprecated.
