### ISSUE TITLE
Change radio code ingame

### ISSUE THREAD

**Issue by nucu** [michail-nikolaev/task-force-arma-3-radio#1042]
Add an ingame option to change the radio code. Mostly for pvp gameplay after a radio got captured.
Ability to change it in the radio menu or maybe add this funtion to the MicroDagr.

**Comment by kavinsky** [comment]
Default Freq. and encryption codes can be changed with modules in the editor.

**Comment by michail-nikolaev** [comment]
If radio captured - you could change freq.
