### ISSUE TITLE
Remove the random loading chanel

### ISSUE THREAD

**Issue by Forley** [michail-nikolaev/task-force-arma-3-radio#1044]
Hello, I search for my server how to remove the automatic loading of channels.
to be more clear,
I try to put a predefined channel for all buyers radios and avoid it for the meta-gaming with a person who spawn with a radio and a used frequency.

I already find fn generate Frequencies.sqf script but I do not know the modify?

I would like to know if you are in the ability to help.

Sincerely,
Yanis Forley

**Comment by michail-nikolaev** [comment]
Check here https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables

tf_same_sw_frequencies_for_side
tf_freq_*
tf_freq_*_lr
