### ISSUE TITLE
 Is it possible to constrain speech on a particular frequency ?

### ISSUE THREAD

**Issue by quentdu69** [michail-nikolaev/task-force-arma-3-radio#1045]
Hello,

above all , and I have to say!
I did not want to know TFR , I had a lot of prejudice!
Now ? I will not be playing on a server that does not have the TFR mods ! ^^

♦ Even so , I wonder if I can shrink the word on everyone but some are on a
a radio frequency.

♦ If this is not possible, I would find a way to ensure , that I can choose people who can talk on one frequency, but others can only hear !

Thank you very much for the work that has been done!

Very Sincerely
Quentin

**Comment by michail-nikolaev** [comment]
Hello.

it is possible to do with additonal scripting using an API.

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Functions
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Events

You could listen *OnBeforeTangent* on client, and on tangent press - check frequency using 

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Functions#TFAR_fnc_getSwFrequency

or 

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Functions#TFAR_fnc_getLRFrequency

If frequency is equal to one you want to protect: 

      player setVariable ["tf_sendingDistanceMultiplicator", 0]

and later on *OnTangent* event for release - 

      player setVariable ["tf_sendingDistanceMultiplicator", 1]
