### ISSUE TITLE
in theory, you can have any part of a uniform to have a radio

### ISSUE THREAD

**Issue by kripto202** [michail-nikolaev/task-force-arma-3-radio#1046]
So my group is using the mod OPTRE and they are well known for radios built inside their helmet. I looked around the code and I found out how you guys got the underwater radio to work on the wetsuit. In theory, would it be possible to change up the code to work on the helmet with different radios.

**Comment by michail-nikolaev** [comment]
technically it is possible....

**Comment by michail-nikolaev** [comment]
or do you want to change it via some script?

**Comment by kripto202** [comment]
im working over the scripts to see if it is possible, when i finalize it, ill post it to here to make sure you guys can determine if this is correct
