### ISSUE TITLE
Dead people hear Zeus inside player

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#1048]

**Comment by indiyskiy** [comment]
Fix it plz ^^

**Comment by dedmen** [comment]
Dead people hear Zeus with serious mode enabled.
Plugin should completely mute everything if dead. Apparently doesn't do that.

**Comment by dedmen** [comment]
To note. If the Game Master module is synced to a Unit (Civilian or any other) that is not a Virtual Entity (Systems -> Logic -> Virtual Entities -> Zeus) 
Then the GameMasters position will always be at the unit it was synced with to start with. Atleast my tests showed that I may be wrong.
