### ISSUE TITLE
How to activate Personal Radios on servers without TFAR installed

### ISSUE THREAD

**Issue by rogerxxxx** [michail-nikolaev/task-force-arma-3-radio#1049]
Many players have been using TFAR installed on their client side, while connected to servers without TFAR installed at the server side.

The Long Range (or vehicle and aircraft) radios work without problems for TFAR clients, on servers without TFAR installed.

However, players cannot open the Personal (ie. Short Range) Radio graphical interface.  It looks as if when opening the Personal Radio interface (ie. ALT+P), the personal radios first communicate with the server first and fail prior to displaying the radio graphical interface.  There should likely be a fall back method, allowing players to still see and use the Personal Radio graphical interface rather than just failing completely.

I know (as well as many others), Personal Radios are usable (on servers without TFAR installed) because on one server within the 3D world, the administrator (or another player with apparently some access to administrator functions) could hand players a working personal radio.  So Personal Radios are workable, and maybe just the fact the personal radios are entirely failing upon a simple error, without any fall back option.

**Comment by michail-nikolaev** [comment]
It may be done by some scripting on server side. Is it ok for you?

**Comment by rogerxxxx** [comment]
Can confirm the 509th Parachute (or similar name) server now has a working TFAR, without TFAR being apparently deployed at the server end.  (I didn't specifically read the required modification list when I connected last night, but personal or short range radios were working.)

I enjoy these agnostic server capable modifications.
