### ISSUE TITLE
Blocked Channels

### ISSUE THREAD

**Issue by Glock17-LFX** [michail-nikolaev/task-force-arma-3-radio#1054]
Hi, 
I am running TFR with a Takistan life server...

I was wondering If their is currently any way to set up blocked channels.

I.E:
TSF / West Side - 33.1 - 33.9 is restricted only for them
UN / independent - 57.1 - 57.9 is restricted so only West and independent can access them.

**Comment by kavinsky** [comment]
every side has his own encryption code
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/README_EN#radios
