### ISSUE TITLE
Settings via .hpp and mission parameter

### ISSUE THREAD

**Issue by NemesisRE** [michail-nikolaev/task-force-arma-3-radio#1055]
Setting or changing settings on serverside, on missionbuild or mission play is not so easy in any mod, ACE3 has a pretty well thought system to handle that the call it [setting framework](http://ace3mod.com/wiki/framework/settings-framework.html).

I think this would be a pretty nice addition for TFAR.

kind regards
NemesisRE

**Comment by dedmen** [comment]
will be solved by #1099 
userconfig settings aren't really usable anymore anyway because of the default filePatching settings. Atleast not useful on clientside.
