### ISSUE TITLE
tf_sendingDistanceMultiplicator can not increase the range of transmission

### ISSUE THREAD

**Issue by aeroson** [michail-nikolaev/task-force-arma-3-radio#1056]
TFAR version: 0.9.8

### Problem:
player setVariable ["tf_**sending**DistanceMultiplicator", 1000];
behaves the same as
player setVariable ["tf_**sending**DistanceMultiplicator", 1/1000];
both decrease the range of transmisson

### Expected:
the second one should increase the range of transmisson

### Workaround:
can use tf_**receiving**DistanceMultiplicator instead of tf_**sending**DistanceMultiplicator
player setVariable ["tf_**receiving**DistanceMultiplicator", 1000]; decreases range of transmisson
player setVariable ["tf_**receiving**DistanceMultiplicator", 1/1000]; increases range of transmisson
both work as expected

**Comment by michail-nikolaev** [comment]
Hm.. Are you sure?

player setVariable ["tf_sendingDistanceMultiplicator", 1000] will INCREASE distance 1000 times.

player setVariable ["tf_sendingDistanceMultiplicator", 0.0001] will DESCREAS distance 1000 times.

Could you please recheck?

**Comment by aeroson** [comment]
Yea, I might make a video just for you.

1000 will increase the distance radios think they are at, so for players it will look like the range of the radio transmission is decreased.

I used this code to test:
```
{
	if(isPlayer _x) then {
		_x setVariable ["tf_sendingDistanceMultiplicator", 1000, true];
	};
} forEach allUnits;

```

**Comment by michail-nikolaev** [comment]
I was checked - everything seems to work correctly.

**Comment by Gurkengewuerz** [comment]
same problem here. the variable decrease the range.

**Comment by aeroson** [comment]
Did some investigation:
```
format["%1", 1/10000] == "0.0001"
format["%1", 1/100000] == "1e-005"
format["%1", 100000] == "100000"
format["%1", 1000000] == "1e+006"
```
this value is in the end parsed by ts plugin with
```
int range = std::atoi(tokens[3].c_str());
```
std::atoi can be confused by the 1e... values
