### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by Reekoj** [michail-nikolaev/task-force-arma-3-radio#1057]
Hello,
when i spawn on my server, i get these 2 errors showing up, could you tell me how to fix it please ?

`13:52:56 Error in expression <Namespace setVariable [_variableName, + _value];
missionNamespace setVariable [_>
13:52:56   Error position: <_value];
missionNamespace setVariable [_>
13:52:56   Undefined variable in expression: _value
13:52:56 File task_force_radio\functions\fn_setSwSettings.sqf, line 31`

`13:52:56 Error in expression <tion = (_this select 2);
[_destination, _localSettings, true] call TFAR_fnc_setS>
13:52:56   Error position: <_localSettings, true] call TFAR_fnc_setS>
13:52:56    Undefined variable in expression: _localsettings
13:52:56 File task_force_radio\functions\fn_requestRadios.sqf, line 32`

**Comment by michail-nikolaev** [comment]
could you please check on vanilla missions?

**Comment by kavinsky** [comment]
Closed due to inactivity.
