### ISSUE TITLE
Make Radio can be disable or jam(like EMP situation)

### ISSUE THREAD

**Issue by GodofMonkeys** [michail-nikolaev/task-force-arma-3-radio#1059]
Make Radio can be disable or jam(like EMP situation)

can we get a parameter to set radio disable or jam?
I want to create some EMP situation to let radio down.

It is very funny to see how people deal with these situation.

Can it possible? Thanks^^

**Comment by kavinsky** [comment]
Not possible atm.
see #600

**Comment by kripto202** [comment]
if anything, I think you can do a script where you can remove the radios from the player to simulate a emp i guess.

**Comment by michail-nikolaev** [comment]
https://drive.google.com/file/d/0B08jTAtYhBTyUXB0SnJaQVhfbkk/view?usp=sharing
