### ISSUE TITLE
Restricted channels

### ISSUE THREAD

**Issue by Jordan1414** [michail-nikolaev/task-force-arma-3-radio#1060]
Hello, been looking through the code and issues and we cant figure out how to restrict channels. 
eg
we want cops (west) and medics (independent) to be able to access 33.1 and up too 33.8 but not civs. can someone assist us? Cheers

**Comment by kavinsky** [comment]
you can share same radio types with west and independent. see https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Variables

**Comment by Jordan1414** [comment]
One more issue, does anyone have any code to make it so Personal radios have no range limit? I have tried the APIs but no results

**Comment by michail-nikolaev** [comment]
@Jordan1414 
try
player setVariable ["tf_sendingDistanceMultiplicator", 10000]
