### ISSUE TITLE
Short range radio distance

### ISSUE THREAD

**Issue by Jordan1414** [michail-nikolaev/task-force-arma-3-radio#1062]

**Comment by Jordan1414** [comment]
I have used a few examples to make short range radios distance go across the map but no results. can anyone give me a hand to make it so short range radios transmit across the map. the APIs that i have used have no results.
can someone give me an example code and where to put it.

**Comment by michail-nikolaev** [comment]
Could you try
player setVariable ["tf_sendingDistanceMultiplicator", 100000]

**Comment by Jordan1414** [comment]
Also would anyone know how to restrict certain channels?

**Comment by kavinsky** [comment]
see #1036
