### ISSUE TITLE
tf_no_auto_long_range_radio = 1; lost after new download of 0.9.8

### ISSUE THREAD

**Issue by PierreMGI** [michail-nikolaev/task-force-arma-3-radio#1064]
Hello,
Perhaps you could help me. I'm stuck with this problem. I've got TFAR 0.9.8 several weeks ago on your server. Yesterday, I found the TFAR 0.9.8 (same version I guess) on Steam and I decided on subcribed for and automatic update (all my other mods are already automatically updated on Steam). So, my TFAR is now from Steam at Arma launcher. But, in any basic scenario I test in 3DEN, i get an automatic long range radio. This was not the case before. I checked for that. My userConfig\task_force_radio\radio_settings.hpp is unchanged. I can read tf_no_auto_long_range_radio = 1.

I don't know what to do to avoid removing the mod. Please help!

**Comment by michail-nikolaev** [comment]
Steam version not uses config because of workshop limitations. But you could host non-steam version on server - client will inherit config. Also, it is possible to use module in editor.
