### ISSUE TITLE
Receiving problems

### ISSUE THREAD

**Issue by redcrayonn** [michail-nikolaev/task-force-arma-3-radio#1065]
Hi,

I'm part of a 350+ arma 3 gaming community and we've been having problems using TFAR. At random points certain people cannot hear certain people, despite running the mod on the latest version. It's not a matter of distance, we tested it 50-100m away. It seems completely random. No transmissions will be heard from certain people, while others can.

**Comment by kavinsky** [comment]
How many players connected to the server you have when happens this?

**Comment by michail-nikolaev** [comment]
Maybe something because of TS anti-flood settings?

**Comment by michail-nikolaev** [comment]
Is it somehow related to location? Or totally random?

**Comment by kavinsky** [comment]
@michail-nikolaev anti flood always give error messages? or its just for admins?

**Comment by redcrayonn** [comment]
**How many players connected to the server you have when this happens?**

We observe it happening when there's more then 5 people on the server. 

**Maybe something because of TS anti-flood settings?**

Will check with administrators.

**Is it somehow related to location? Or totally random?**

It is completely random but seems to only occur with long range radios, particularly the  RT-1523G. Distance is not a factor since we've seen it happen when standing right next to people. It would not be audible on long range by certain people, while certain people can hear them.

**Comment by michail-nikolaev** [comment]
@redcrayonn any news?

**Comment by redcrayonn** [comment]
In the last couple of weeks I've been going around telling people to reinstall their TFR. So far so good, haven't encountered the bug since. Might've been a combination of having a newer TFAR version and older plugin. Have noticed something else though. Occasionally it will take 5-7 minutes for certain players to be muted by TFAR. For example; I'll jump into a server and would hear 1 or 2 persons as without TFAR even though it is enabled for both. I would hear them but they would not hear me. This problem dissolves after 5-8 minutes though.
