### ISSUE TITLE
Protected Frequencies - for different factions

### ISSUE THREAD

**Issue by AidenTeran** [michail-nikolaev/task-force-arma-3-radio#1067]
Basically, 

Im looking to create a script that will lock a certain amount of frequencies to different factions for example.

Police and EMS - 30.0-39.9
Civilian -40+

Is this possible and if so does anyone have any idea how to.

**Comment by kavinsky** [comment]
see #1060

**Comment by AidenTeran** [comment]
Okay im a little confused. 

Im no expert at TFR so i will need help as to where or how i place the scripts???/???
