### ISSUE TITLE
does TFAR work with 3den missions now?

### ISSUE THREAD

**Issue by kripto202** [michail-nikolaev/task-force-arma-3-radio#1068]

**Comment by michail-nikolaev** [comment]
as far as I know - yes

**Comment by kripto202** [comment]
still doesnt

**Comment by michail-nikolaev** [comment]
what is wrong with it?

**Comment by kripto202** [comment]
when setting it to advanced settings, on loading the mission, it doesn't move you to the proper channel you have set to and the local talk (where you can hear people from a distance) doesn't work either. Everything else works correctly. This is only happening on 3DEN missions.
