### ISSUE TITLE
Force reinitialise TFR

### ISSUE THREAD

**Issue by Pydrex** [michail-nikolaev/task-force-arma-3-radio#1069]
I am having some major issues with my new mod. When we load in we use an FSM which loads all the data, Once this is done it loads the huds (we have things like flashing blood icons etc for when you're injured), It seems these will go over the top of TFR meaning you can't see the GUI of radios/voice control.

Is there a way to force reinitialise TFR once the player has joined?

**Comment by Pydrex** [comment]
Our hud uses the rscLayer of which class is;

	class playerHUD {
		idd = -1;
		duration = 1e+1000;
		movingEnable = 0;
		fadein = 0;
		fadeout = 0;
		name = "playerHUD";
		onLoad = "uiNamespace setVariable ['playerHUD',_this select 0]";
		onUnload = "uiNamespace setVariable ['playerHUD', displayNull]";
		objects[] = {};
		class controls {
			class RscText_1000: Life_RscText
			{
				idc = 1000;
				text = "Server Name"; //--- ToDo: Localize;
				x = -0.000156274 * safezoneW + safezoneX;
				y = 0.973 * safezoneH + safezoneY;
				w = 0.0670312 * safezoneW;
				h = 0.022 * safezoneH;
				sizeEx = 0.03;
			};
			class RscPicture_1200: Life_RscPicture
			{
				idc = 1204;
				text = "\sndimg\sahrani\icons\Bone.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.676 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				blinkingPeriod = 0.8;
				show = "false";
			};
			class RscPicture_1201: Life_RscPicture
			{
				idc = 1201;
				text = "\sndimg\sahrani\icons\Health.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.456 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				blinkingPeriod = 0.8;
				show = "false";
			};
			class RscPicture_1202: Life_RscPicture
			{
				idc = 1200;
				text = "\sndimg\sahrani\icons\Bleeding.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.511 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				blinkingPeriod = 0.8;
				show = "false";
			};
			class RscPicture_1203: Life_RscPicture
			{
				idc = 1202;
				text = "\sndimg\sahrani\icons\Hunger.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.566 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				blinkingPeriod = 0.8;
				show = "false";
			};
			class RscPicture_1204: Life_RscPicture
			{
				idc = 1203;
				text = "\sndimg\sahrani\icons\Thirst.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.621 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				blinkingPeriod = 0.8;
				show = "false";
			};
			class RscPicture_1205: Life_RscPicture
			{
				idc = 1205;
				text = "\sndimg\sahrani\icons\Headphones.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.731 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				show = "false";
			};
			class RscPicture_1206: Life_RscPicture
			{
				idc = 1206;
				text = "\sndimg\sahrani\icons\Weight.paa";
				x = 0.964063 * safezoneW + safezoneX;
				y = 0.786 * safezoneH + safezoneY;
				w = 0.0309375 * safezoneW;
				h = 0.055 * safezoneH;
				blinkingPeriod = 0.8;
				show = "false";
			};
		};
	};

**Comment by Pydrex** [comment]
Ok, Looking at this more if I run call TFAR_fnc_swRadioMenu it will work making it appear as if it is the keybinds not working

**Comment by Pydrex** [comment]
Resolved,

Removing these lines from my code seemed to fdix it.

removeAllMissionEventHandlers "Draw3D";
removeAllMissionEventHandlers "Loaded";
removeAllMissionEventHandlers "Ended"
(findDisplay 46) displayRemoveAllEventHandlers "KeyDown";
(findDisplay 46) displayRemoveAllEventHandlers "KeyUp";
(findDisplay 46) displayRemoveAllEventHandlers "MouseButtonDown";
(findDisplay 46) displayRemoveAllEventHandlers "MouseButtonUp";

**Comment by michail-nikolaev** [comment]
yep, displayRemoveAllEventHandlers "KeyDown"; will remove TFAR handlers too...
