### ISSUE TITLE
Teamspeak move problems

### ISSUE THREAD

**Issue by izShelby** [michail-nikolaev/task-force-arma-3-radio#1070]
I host a server using TFAR and the plugin works just fine for me and some friends, however two of them suffer from the problem that whenever they connect to the arma server they get moved into the TaskForceRadio channel and after approximately 10s they get moved back. With name change and all.
The only thing showing up in their TS log is 
`task_force_radio    Info    can't center client : invalid clientID`
And their arma 3 rpt only shows
`19:07:59 Unable to get file version size: C:\Program Files (x86)\Steam\steamapps\workshop\content\107410\620019431\task_force_radio_pipe.dll`
which, I've been told, is not an issue.

Is this a problem server side?

//Oh and an edit: When they manually join the channel, their teamspeak description says Connected:Y and Playing:N.
I've linked the problem to the newest version of CBA, since the systems where the problem occurs are using the 2.4.1 while the others are using 2.3.1.

**Comment by michail-nikolaev** [comment]
Thanks for info, will check compatibility with new CBA version.

**Comment by michail-nikolaev** [comment]
Could you try to update both server and clients to new CBA?

**Comment by izShelby** [comment]
Both are the newest version. In other news, Enhanced Movement also stops working if I use the newest version of CBA, so there seems to be a general problem with the update. Maybe a removed script call?

**Comment by michail-nikolaev** [comment]
So, server and all clients on new version?

**Comment by izShelby** [comment]
Yes.

**Comment by michail-nikolaev** [comment]
Could you please try only with TFAR and CBA? Also, is it working for you at local server?

**Comment by izShelby** [comment]
I don't have much time right now, but with the short testing I've done on a blank arma server running a default zeus mission and a blank teamspeak, it worked. So it would be possible there's an incompatibility with some other mod I'm running. Will elaborate once I got time.

**Comment by izShelby** [comment]
Okay, I narrowed the problem down, not to CBA, but the servermod I'm running. (Bear in mind that this STILL only happens with the newest version of CBA)
I ran a test server with no mods at all and a blank TS - Working perfectly. Then I ran it again with all the mods I am using: CBA, TFAR, A2OP, Arma Enhanced Movement, Blastcore: Phoenix, Esseker map, Exile Mod and Ryan's Zombies and Demons - Still working perfectly. However, as soon as I add the -servermod=@exileserver; line to my start parameters, TFAR starts moving me back out of the channel everytime it moves me in, as described in the first post. There seems to be some sort of compatibility issue between exile server, TFAR and CBA and I'm not good enough of a coder to find out what it is.

Also, as described above, Enhanced Movement stops working.

I suppose this is out of your hand? If so, I am sorry for bothering you with it, I should probably have narrowed down the incompatibility in the first place.

Regards,

**Comment by michail-nikolaev** [comment]
"48 "Adam/BIS_fnc_log: [BIS_fnc_addStackedEventHandler] Stack as been updated with ID (CBA_PFH) for Event (onEachFrame) executing Function (cba_common_fnc_onFrame), Replaced: (true)""


Seems like it is conflict of exile mod with new CBA. Also, probably old CBA also could cause issues with new Arma version.

**Comment by izShelby** [comment]
I will take this to their forums then. Thanks for your help.

**Comment by commy2** [comment]
@izShelby 
@michail-nikolaev 

Does this issue persist? I've been told that it happens with the "latest" CBA version.
Can I see a full RPT file?
Thanks

**Comment by michail-nikolaev** [comment]
My bad, full RPT is here: http://pastebin.com/XiwLzzY2

Was caused by old CBA probably...

**Comment by commy2** [comment]
>Community Base Addons v1.20

Yeah. That is definitely not the latest CBA (which is v2.4.1)
We specifically stopped using `BIS_fnc_addStackedEventHandler` because of potential compatibility problems with other addons using the `onEachFrame` command directly.
Unfortunately the Exile devs have a history of not caring about compatibility. They did the exact same with `onPlayerConnected` (Not using BI's stacked eh framework)

I was confused because we now using those "EachFrame" mission event handlers, and those should cause RPT logs like:
```
"48 "Adam/BIS_fnc_log: [BIS_fnc_addStackedEventHandler] Stack as been updated with ID (CBA_PFH) for Event (onEachFrame) executing Function (cba_common_fnc_onFrame), Replaced: (true)""
```
