### ISSUE TITLE
Author and url missing from apex

### ISSUE THREAD

**Issue by ArMaTeC** [michail-nikolaev/task-force-arma-3-radio#1071]
might wanna add to stop the errors
class CfgPatches
{
	class task_force_radio
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = { "CBA_Main", "task_force_radio_items"};
		authorUrl = "https://github.com/michail-nikolaev/task-force-arma-3-radio";
		author="[TF]Nkey";
		url="https://github.com/michail-nikolaev/task-force-arma-3-radio";
		version = 0.9.8;
		versionStr = "0.9.8";
		versionAr[] = {0,9,8};
	};
};

**+		author="[TF]Nkey";
**+		url="https://github.com/michail-nikolaev/task-force-arma-3-radio";

**Comment by dedmen** [comment]
The current config already has 
```author[] = {"[TF]Nkey"};```
is that enough for the author field?

**Comment by ArMaTeC** [comment]
unfortunately not with the new apex there is now only the non array version dependency and authorUrl is changed to url and the addition of name = "bla"

class CfgPatches
{
	class A3_3DEN
	{
		author = "$STR_A3_Bohemia_Interactive";
		name = "Arma 3 Eden Update - Eden Editor";
		url = "http://www.arma3.com";
		requiredAddons[] = {"A3_Data_F_Exp_B","A3_Ui_F"};
		requiredVersion = 0.1;
		units[] = {"Sphere_3DEN","SphereNoGround_3DEN"};
		weapons[] = {};
	};
};
