### ISSUE TITLE
TFR doesn't work on APEX

### ISSUE THREAD

**Issue by Pydrex** [michail-nikolaev/task-force-arma-3-radio#1077]
It seems since CBA has updated and 2.3.1 no longer works on Apex, The TFR allows menus etc but you can't speak nor get moved and get the error 18:33:48 Unable to get file version size: C:\Users\Andrew\Documents\taki\1.00\@task_force_radio\task_force_radio_pipe.dll on client

**Comment by Pydrex** [comment]
2.4.1 (Last CBA) Doesn't load in to the server with TFR on the preview build.

**Comment by Pydrex** [comment]
2.3.1 does but then crashes if you host it due to a string violation

**Comment by Pydrex** [comment]
Issue due to a conflicting OnEachFrame, If possible could this be changed to a stacked handler in the next build?

**Comment by jokoho48** [comment]
i am not sure if you have understand what commy told you. TFAR und CBA uses StackedEH but you have overwrite them not TFAR and not CBA

**Comment by commy2** [comment]
Yes. TFAR is using the `BIS_fnc_addStackedEventHandler`, but using `onEachFrame` by a third party mod can still break it.

**Comment by commy2** [comment]
In which case the third party mod has to be fixed.

**Comment by Pydrex** [comment]
Fixed by Commy

**Comment by michail-nikolaev** [comment]
Thanks, guys!
