### ISSUE TITLE
allUnits is not guaranteed to include allPlayers

### ISSUE THREAD

**Issue by aeroson** [michail-nikolaev/task-force-arma-3-radio#1078]
TFAR gets list of all units from allUnits.
Positions of those units are then send to TS plugin.
If unit position is **not** send to TS plugin, TS plugin thinks unit has **disabled** TFAR.

Problem:
Sometimes your computer doesn't include some players in allUnits array.
Result:
You can hear some players that are ingame as if they had disabled TFAR.

Seems if there is alot of units, Arma 3 goes into some kind of optimization mode and stops sending info about units that are far away.

So if there are 400 units on server and 30 players.
New player joins and spawns far away from me.
This player will not be included in allUnits and TFAR will think this player has TFAR disabled, because it will not get info about his position.
Thus this player will sound as if he had TFAR disabled.

Running this script seemed to fix it:
```
[{
	{ player reveal _x } forEach allPlayers;
},"BIS_fnc_spawn",true] call BIS_fnc_MP;
```

Seems to recur after player (re)connects.
Seems to recur after player respawns.

Can possibly be caused by starting the server with: -bandwidthAlg=2
Can possible be caused by ALiVE doing some behind the scenes optimizations.
Possibly related to Killzone Kid's comment at https://community.bistudio.com/wiki/reveal

Can be fixed by enabling serious mode.

**Nonetheless code should be changed to cope with the fact that allUnits is not guaranteed to include allPlayers.**

**Comment by michail-nikolaev** [comment]
Thanks for investigations
