### ISSUE TITLE
TFAR Arma 3 APEX Issues

### ISSUE THREAD

**Issue by Janl1** [michail-nikolaev/task-force-arma-3-radio#1080]
Hello,

we are using TFAR together with altis life 3.1.4.8 framework and Arma 3 Sneaky Preview of apex.
After a few minutes the player gets kicked out of the TeamSpeak channel.
Is there a way to fix this issue?

Edit:
The tazer action sets the variable _player setVariable ["tf_unable_to_use_radio", true];_ true and after the script finished loading back to false.

**Comment by ripkens** [comment]
Just a hint:
It moves you back into Task Force Radio Channel when you get tasered ...

**Comment by DanielLarusso** [comment]
since a few days my ctrl button is called lctrl in arma 3. so I can't use ctrl+p or crtl+tab anymore.
when I try to rebind them it doesnt work I can't bind lctrl+anything in tfar don't know if it's an tfar issue or an arma issue

**Comment by ripkens** [comment]
DanielLarusso, is this in any way connected with the topic? This issue is about a bug with APEX!!

**Comment by DanielLarusso** [comment]
oh, I've forgot to say that I have this issue since I bought apex

**Comment by michail-nikolaev** [comment]
Are you using latest CBA? Also, are you using Exile mod?

**Comment by Stinkesocke** [comment]
We will update ACE and CBA today to see if it will fix TFAR, Will report.

**Comment by Stinkesocke** [comment]
Its not Exile, its Tanoa APEX with altis life 3.1.4.8

**Comment by michail-nikolaev** [comment]
@Stinkesocke thanks for your investigations!
