### ISSUE TITLE
re texture models

### ISSUE THREAD

**Issue by SharonX4** [michail-nikolaev/task-force-arma-3-radio#1082]
re-texturing long range radios

i am in a clan that made custom uniform for our operations 
and the long rage are in different camo
it is possible that one of our people re textured  the models to fit our uniform?

**Comment by CorruptedHeart** [comment]
It should be possible to retexture models, the following link shows an example of a re-textured backpack.
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio_items/config.cpp#L218-L224

And this one includes a link to the PSD file, I believe. https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/textures/dropbox.txt

**Comment by SharonX4** [comment]
i am asking for permissions
 i know how to do this

**Comment by CorruptedHeart** [comment]
I believe you are perfectly within your rights to do this.

**Comment by SharonX4** [comment]
i would  like to speak with one of the developers please

**Comment by jokoho48** [comment]
he is one of the devs :)

**Comment by SharonX4** [comment]
ohhh sorry :+1: 

any psd for the 1523g?

**Comment by jokoho48** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/tree/master/arma3/%40task_force_radio/addons/textures
