### ISSUE TITLE
Author/ is not a value

### ISSUE THREAD

**Issue by Armilio** [michail-nikolaev/task-force-arma-3-radio#1087]
Since 1.60, BIS removed the array format "author[] = {}" to defining authors in CfgPatches. We are forced to use the string format (author = ""). I saw that in TFR there is that old way to write it, and it's annoying not only because of the pop-up error, but because it can create problem to the mission if you place the TFR RadioBox in the mission. One time, it has made a my mission unplayable.

**Comment by michail-nikolaev** [comment]
fixed in update
