### ISSUE TITLE
Version 0.9.9 not released

### ISSUE THREAD

**Issue by larsrusteberg** [michail-nikolaev/task-force-arma-3-radio#1089]
Is it possible for you to release version 0.9.9 on github here, please?

**Comment by michail-nikolaev** [comment]
will do today

**Comment by Zakant** [comment]
Any updates about this?

**Comment by michail-nikolaev** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/releases/tag/0.9.10

Sorry for delay - totally forgot about this.
