### ISSUE TITLE
0.9.10 Release missing radio_settings.hpp include

### ISSUE THREAD

**Issue by Wyqer** [michail-nikolaev/task-force-arma-3-radio#1095]
I was wondering why the new release didn't load the radio_settings.hpp

Don't know why, but the \addons\task_force_radio\config.cpp hast an empty task_force_radio_settings class.

Release Version:
`class task_force_radio_settings {	
};`
Should be:
`class task_force_radio_settings {
	#include "\userconfig\task_force_radio\radio_settings.hpp"
};`

**Comment by michail-nikolaev** [comment]
it is not possible to ship radio_settings.hpp in steam version...

**Comment by michail-nikolaev** [comment]
will try to do some trick
