### ISSUE TITLE
Issue - "Connected Y Play N"

### ISSUE THREAD

**Issue by MrSniperPhil** [michail-nikolaev/task-force-arma-3-radio#1097]
Hey,

we're running the latest TFAR (0.9.8) and the latest CBA (3.0.0).
Ingame we can use the radios as usual, but direct coms doesn't give directional rather than "global" (like a player without TFAR) sound. Also, everyone has "Connected Y Play N" as the TFAR Status in Teamspeak. Reinstalling the TS-Plugin did not help.
Known Issue? If so, how can we fix it?

Thanks in Advance!
Phil

**Comment by Brain512** [comment]
The exact CBA version we use is 3.0.0.160713.

**Comment by michail-nikolaev** [comment]
Update to steam version
