### ISSUE TITLE
TFAR not compatible with TS API 21

### ISSUE THREAD

**Issue by DerAtrox** [michail-nikolaev/task-force-arma-3-radio#1098]
Hey, i just updated to the latest TeamSpeak version (TS 3.1), which comes with a new API version. 

Will TFAR support API version 21 in the future or will this project die with the new API?

**Comment by FATKIDSLOV3CAK3** [comment]
Would really like to hear that this will be a up coming fix As the community i am apart of as a heavy use of TFR for our mod.

**Comment by ArMaTeC** [comment]
would love to see this fixed also

**Comment by psykzz** [comment]
+1

**Comment by skapytek** [comment]
pls fix this.

**Comment by dedmen** [comment]
see PR #1100 I'll add the finishing touches to that in the next few hours

**Comment by FATKIDSLOV3CAK3** [comment]
Yh i am well aware of it being beta and not full release but i am the kinda of person to see what is coming in updates to come and it is best to try and get this done and or ready for when they push the full release of 3.1.

Better to have it done and ready then still be in the dark or not know about a problem :D

**Comment by dedmen** [comment]
My PR for the update is ready you can compile it yourself or wait till @michail-nikolaev is back from being AFK and does a release.

**Comment by skapytek** [comment]
How can i compile it to get it working with newest ts3 update?

**Comment by skapytek** [comment]
How can i compile it to get it working with newest ts3 update?

**Comment by skapytek** [comment]
How can i compile it to get it working with newest ts3 update?

**Comment by dedmen** [comment]
Here is a compile of my pull-request for 3.1

https://mega.nz/#!Q0EiwJCa!CW6DXdFFCYnY-fVVAwb9YGy_X1uqVrzycbacxm_Neiw
Its compiled with Visual Studio 2015 instead of 2010 in the official builds. And only 64 Bit because im too lazy for more. Use on your own risk.

**Comment by skapytek** [comment]
Hi,
its not working with the newest ts3 update (3.1)
API version is still 20 but it needs version 21

regards

**Comment by dedmen** [comment]
@skapytek  i just tested in my virtual machine. Installed a fresh x64 3.1 client and tried to enable my plugin. worked just fine. Keep in mind its only the 64bit version.. so if you have 32bit installation and both plugins in your plugins directory and only replace the 64bit one it will still use the 32bit one thats not updated.

**Comment by skapytek** [comment]
I reinstalled teamspeak 3.1.
I deleted the 32bit .dll.
It wasnt working

**Comment by dedmen** [comment]
Here a new build 64 and 32 bit
https://mega.nz/#!5sdDjbyA!uHxEQH64tv1j6hD_U57ViMjXqywv40yH1d5zQibbl4Y
I tested the 64bit one in my VM and it appeared to be working

**Comment by skapytek** [comment]
I made a new installation of teamspeak and updated it to version 3.1.
Then i installed TFAR and moved your new 32 and 64bit dll files to the correct folder but its still not working.
Api version is still 20.

regards

**Comment by dedmen** [comment]
Can you please go to your teamspeak directory and right click the teamspeak 3 client executable. Then go to properties and details and tell me whats listed there for "version" should be 3.0.20.0. Which is detected here https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1100/files#diff-ea56a4e50e69abe2ea71f5ef2d502db1R2157 and should return API version 21

**Comment by dedmen** [comment]
@kavinsky Considering the Refactoring project might take a long time we should push this to 0.9.12 milestone. Because we will need this as soon as Teamspeaks 3.1 Client goes into stable.

**Comment by skapytek** [comment]
Hi,
Version is: "3.0.20"
![ts3](https://cloud.githubusercontent.com/assets/11317488/18625218/4fa46bf6-7e4d-11e6-9b17-ad39d62610ec.png)

**Comment by dedmen** [comment]
Can somebody else check this? I cant replicate that on my System.

**Comment by skapytek** [comment]
Maybe you have an idea what i can try to get it working?!

**Comment by skapytek** [comment]
Just copied your 32 and 64bit dll into the .../appdata/... folder and choose overwrite the old files.
Updated teamspeak to version 3.1.
TFAR is now working

![ts3](https://cloud.githubusercontent.com/assets/11317488/18682194/949a1700-7f6b-11e6-9763-50680279182d.png)

Thansk for your help!

**Comment by dedmen** [comment]
Could have helped earlier if i knew that teamspeak was doing derpy
things... Official 0.9.12 pre-release will be out tomorrow that also
contains teamspeak 3.1 support

**Comment by dedmen** [comment]
Fixed with #1100 which was merged into 0.9.12.
Full Release of 0.9.12 end of this week.
