### ISSUE TITLE
Broken Texture Link

### ISSUE THREAD

**Issue by LhuanDula** [michail-nikolaev/task-force-arma-3-radio#1101]
Hi,

it seems that the dropbox links for the backpacks texture is broken.

See here;
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/textures/dropbox.txt

**Comment by dedmen** [comment]
Thats bad... Why are the textures not on github?

**Comment by LhuanDula** [comment]
Yes, but the extracted textures from the pbos are not psds without any layers.

But yeah, ultimately we can do it from the textures.

**Comment by kavinsky** [comment]
lets wait for @michail-nikolaev

**Comment by dedmen** [comment]
https://drive.google.com/drive/folders/0B08jTAtYhBTyMjVNc1ZLTWV3Ymc
https://drive.google.com/drive/folders/0B4u4mj2Iae0EeFFQUXg3UHktQjg

**Comment by LhuanDula** [comment]
Perfect!
Thank you very much :)
