### ISSUE TITLE
TFAR 0.9.11 Server configs are broken

### ISSUE THREAD

**Issue by 1im** [michail-nikolaev/task-force-arma-3-radio#1102]
Greetings,

Since the 0.9.11 update on 16/08/16 ( withSIX), server configs are ignored by the server, and it doesn't have any effect, no matter if we use bool or 1/0
If executed with bool on init.sqf it works like a charm, hence the functions are clearly intact, so our best guess is that something messed up with how the mod handles userconfigs or may be the folder name should have been different than just task_force_radio, we don't know

This issue is hindering gameplay pretty badly, and we would absolutely scream with joy if you will look into it and figure out what went wrong, anyway, absolutely adore your mod,

Best regards, 
Tactical Shift

**Comment by zgmrvn** [comment]
the userconfig file has been discontinued due to steam "uncompatibility", work around already submitted here : https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1099

**Comment by dedmen** [comment]
@zgmrvn are you sure its due to steam "incompatibility" instead of filepatching stuff?
I personally never needed to use the userconfig.

**Comment by zgmrvn** [comment]
one of the reasons :
https://forums.bistudio.com/topic/159393-task-force-arrowhead-radio/?p=3065777

**Comment by kavinsky** [comment]
closable by 0.9.12?

**Comment by dedmen** [comment]
solved by #1099 which is in 0.9.12.
