### ISSUE TITLE
define side for variable

### ISSUE THREAD

**Issue by SharonX4** [michail-nikolaev/task-force-arma-3-radio#1104]
player setVariable ["tf_unable_to_use_radio", true]

i make a pvp with a option to destroy tower

i want that vriable will work only for the side that their tower destroyed (if east bomb tower for west so to west have no radio)

**Comment by dedmen** [comment]
From https://forums.bistudio.com/topic/80134-foreach-over-all-units-in-a-side/
```
{
   if ((side _x) == West) then
   {
     _x setVariable ["tf_unable_to_use_radio", true];
   };
} forEach allPlayers;
```
This disables the radio for all players on West side.
