### ISSUE TITLE
Set Minimum Readable Distance

### ISSUE THREAD

**Issue by 1stLT** [michail-nikolaev/task-force-arma-3-radio#1106]
Hello, I'm planning to create a mission and I need to make the radio kinda not working.
I know that when you're too far away from the other player you sound weak and unreadable.
Is there a way I can set it manually to work when I want?

Thanks in advance :)

**Comment by CorruptedHeart** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Variables

You will want to look at `player setVariable ["tf_receivingDistanceMultiplicator", 2]` and `player setVariable ["tf_sendingDistanceMultiplicator", 0.5]`

**Comment by 1stLT** [comment]
@CorruptedHeart 
I tried these lines you gave me and placed them in the init.sqf file but they didn't work.
So I tried this player setVariable ["tf_terrain_interception_coefficient", 0.5]; and it didn't work either.
I tried all of them together and they still didn't work.
All I want is the sound when that plays when you talk while the radio signal is bad.
