### ISSUE TITLE
Ctrl+P not working, conflict ?

### ISSUE THREAD

**Issue by asuri0n** [michail-nikolaev/task-force-arma-3-radio#1107]
Bonjour,
I have a problem with the mod TaskForceRadio. 1 time 2 radios do not work. The item is existing, you can talk with other players with the mod, but the Ctrl + P does not work (It opens the list of players), I can not change the channel (Num Pad) or anything.
I found a temporary solution, you disable the plugin "Teampseak 3 plugin control" of TS client and reload plugin ... (Who knows why), but it must be done at each times before reaching the server.
I have these errors in the logs:
"Unable to get file size Version: D: \ Steam Game \ steamapps \ common \ Arma 3 Workshop @ VacationGaming \ task_force_radio_pipe.dll"
"Warning: 1279 ms spent in callExtension calling name: "task_force_radio_pipe" function: "SHOW VERSION 0.9.8 mdptfrchannel TFR""
I use the latest version of CBA, the latest version of TFR (0.9.8) ...
Thank you in advance

Mods in my pack ; AGM, Enhanced Mouvement, custom texture mod.

Sorry for my bad english :D

**Comment by asuri0n** [comment]
If I use only @CBA and @TFR, still not working :/

**Comment by dedmen** [comment]
You are running AGM? AGM was last updated for arma version 1.40 where 1.64 will shortly be released. Its outdated for almost a year now.
Are you sure you are running CBA version 3.0.0 ?
Do you also have the newest teamspeak plugin? (0.9.8)

**Comment by asuri0n** [comment]
Yes :/ It's working fine in editor but not completely on my server.

**Comment by dedmen** [comment]
Well there certainly cant be any conflict when you are really only running CBA and TFAR in the latest versions. Did you check all your Arma (non-mod) keybinds if there is any conflicting one?

**Comment by asuri0n** [comment]
Ye I tried everything.
22:02:44 [27236,996.998,1.5,"CBA_VERSIONING: cba=3.0.0.160713, "]
22:02:44 [27237,997.102,1.574,"CBA_VERSIONING_SERVER: cba=3.0.0.160713, "]

Maybe a conflict with Tanoa map ? 

But CTRL P and ALT P radios are not working when you connect for the first time after a reboot. But after the slot is initialised, it's always working ... If you change slot (same side), it's still not working.

Sorry for my bad english :/

**Comment by dedmen** [comment]
Your english is okey.
Yeah.. i dont really know then.. A ton of people play TFAR on Tanoa so the error seems to be specific to you.

**Comment by asuri0n** [comment]
It's a server problem I think. I will reinstall Arma folder

**Comment by dedmen** [comment]
Tell me what the state is after reinstalling.

**Comment by asuri0n** [comment]
Same. :/ But there is same problem with Enhanced Movement (When TFAR doesn't work, EM either), so it's specific to our server :/ but why ...

**Comment by dedmen** [comment]
So it works if you play on another server?

**Comment by asuri0n** [comment]
Yes, it's only on my server.

**Comment by dedmen** [comment]
"Warning: 1279 ms spent in callExtension calling name: "task_force_radio_pipe" function: "SHOW VERSION 0.9.8 mdptfrchannel TFR""
The function shown.. "SHOW VERSION" doesn't even exist... 
Does the problem still exist on version 0.9.12?
