### ISSUE TITLE
PBO Structure refactor

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#1120]
Starting using the development procedures that give us CBA we should change our project structure to fit these.

**Proposal:**
- Change addon structure
  - tfar_core -> /addons/core Here go all TFAR api and basic configs.
  - tfar_radio_`radio_name` -> /addons/radio_`radio_name` A PBO file for every radio.
- Remove debug mission, since we dont need it to debug.
- Move task_force_radio_pipe.dll source to /extensions/task_force_radio_pipe/ and compiled dll in /
- Move TS3 Plugin source to /plugins/source and compiled in /plugins/

**Comment by nikolauska** [comment]
Could you possibly change whole project structure to same as ace, so addons folder would be on root? Debug mission could also be moved inside separate addon that can be used for player to test if tfar is working correctly.

**Comment by dedmen** [comment]
1. exactly that is planned.
2. I think we will completly remove the Debug mission.

**Comment by nikolauska** [comment]
good, didn't see it anywhere mentioned :+1:

**Comment by kavinsky** [comment]
updated.

**Comment by kavinsky** [comment]
#915

**Comment by dedmen** [comment]
This task is done isn't it?
