### ISSUE TITLE
Arsenal save causes duplicate radio ID's

### ISSUE THREAD

**Issue by dedmen** [michail-nikolaev/task-force-arma-3-radio#1123]
zgmrvn [11:45 PM]  
let's say i save my gear with the radio TFAR_r7800_1

zgmrvn [11:46 PM]  
and in a fresh multiplayer game, when a player serlecte a radio, he recieve the TFAR_r7800_1, then i load my gear with the TFAR_r7800_1 too

dedmen [11:49 PM]  
ah i see.. @zgmrvn you have a saved loadout with radio _1 when you load that after another guy already got _1 you now have two _1 radios... Mh.... Dont know how one would fix that... Please create an issue for that

Solution ideas:

zgmrvn [11:54 PM]  
a DialogEventHandler would be better

kavinsky [11:55 PM]  
if we overwrite Arsenal save function we need to check every release they do

dedmen [11:56 PM]  
@zgmrvn please create a issue for that so we can keep notes there

dedmen [11:55 PM]  
if we can catch that a save has just been done.. We can manually iterate through saved loadouts in profileNamespace and change radios there
[11:57]  
But we can attach one to the save button and then do a spawn which then does our profileNamespace stuff

dedmen [11:58 PM]  
because the save is called by the button which will run in unscheduled .. when we spawn we get the next scheduled tick when the save will be done

[11:59]  
but.. that solves the arsenal problem.. not the possible Eden Loadout problem

[11:59]  
would have to check if loadouts in eden missions save with the radio id

**Comment by kavinsky** [comment]
Reference: #313

**Comment by zgmrvn** [comment]
`player addEventHandler ["Take", {}];` is not triggered by VA

**Comment by dedmen** [comment]
We can just iterate through the saved loadouts in profilenamespace before
each missionstart. That would make sure all saved loadouts are clean before
mission start... And you cant get duplicate radios inside one mission if
you started with clean loadouts. You can create corrupt loadouts and load
them again while playing the mission. But that cant create a duplicate
radio id

**Comment by zgmrvn** [comment]
so you could not have a radio in your saved gear ?

**Comment by dedmen** [comment]
Radios yes. But not radios with IDs

**Comment by dedmen** [comment]
But that would not fix the Eden Loadout issue.. If thats even existent.. I'll check that now

**Comment by BryanBoru** [comment]
Although I use Arsenal more than VAS recently, I am excited to see this addressed.

**Comment by dedmen** [comment]
Fix merged in #1139
