### ISSUE TITLE
Move Min and Max distance voice volumen to constants

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#1126]
Right now the min and max voice distance are hardcoded, we should move it to constants.

**locations:**
- https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_onSpeakVolumeChange.sqf#L11
- https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/992/files#diff-f110e2d6b53752e5a3902f20a849c200R247

**Comment by dedmen** [comment]
2e44cf376c085279da9981a9d068bae8221104a1
Still hardcoded but in a central place.
Did you mean variables? People may like that to be configurable.. What do you think?

**Comment by kavinsky** [comment]
now is done as i mean on the issue :)
