### ISSUE TITLE
Remove Divers radios

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#1127]
Remove Divers radio functionality and give the SW and LR radios the hability of transmit underwater.

**Comment by dedmen** [comment]
check wheather player has diving gear in canUseSWRadio/canUseLRRadio. and if underwater and no gear just 
call TFAR_fnc_inWaterHint;
Teamspeak Plugin will take care of switching the sound and range around.

This is basically equivalent to having the radio in a waterproof pouch and a microphone in your diving mask.

I dont know if we want underwater LR Radios.

**Comment by Meiestrix** [comment]
Maybe there is a way to add changeable antennas, or radio settings to solve this.
For example a normal land antenna with 5 Km range and nearly no underwater range,
and a underwater antenna with good underwater range, but a small range on land, for example 1 Km.

**Comment by dedmen** [comment]
We are not trying to be a realistic mod :x just somewhat realistic is enough.. When you have underwater equipment and are underwater you will automatically switch to the underwater antenna

**Comment by dedmen** [comment]
Done. But LR Radio's cant transmit underwater because.. you can't just put your whole backpack into a waterproof pouch.
Also in the process of doing that i Improved the signal strength calculations. Now taking into account when the signal leaves the water. Using underwater calculations underwater. And air/terrain calculations above water.

**Comment by kavinsky** [comment]
normally that kind of stuff goes into dry sacks to prevent water damaging the electronics so this feature is correct.

**Comment by MacKelnuts** [comment]
In v1.0.222, Utilizing the SW radio underwater, does not seem to work.  Was this fully implemented or is it still WIP?  Or is there a specific way to achieve its function?

**Comment by dedmen** [comment]
You can ofc only speak underwater if you can also breathe. But else it should be completly implemented but.. I'll test that. Thanks for reporting.

**Comment by dedmen** [comment]
The scripts are telling Teamspeak that the player doesn't have a SW Radio when he is underwater. But we can still transmit on it ingame so we definetly have one :D

**Comment by dedmen** [comment]
Fixed in df5d6ea8a377f7b47ad92a9ec116f279a6b98453 build 223
