### ISSUE TITLE
Remove old main menu dialog.

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#1128]
There is a dialog on the middle of the main menu.

We have to remove it.

**Comment by dedmen** [comment]
I still cant reproduce this.. Can you maybe provide a screenshot of that dialog?

**Comment by CorruptedHeart** [comment]
I've seen this on the Steam version of TFAR.

**Comment by dedmen** [comment]
was removed in 385f295ae3c57d5fddeeb54284a2ca85296f07fd i think...

**Comment by dedmen** [comment]
@kavinsky resolved?
