### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#1129]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/current_version.txt

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_TaskForceArrowheadRadioInit.sqf#L20

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/mod.cpp#L1

**Comment by dedmen** [comment]
*.md
0.9.7.3 -> 0.9.12
0.9.7 -> 0.0.12

**Comment by dedmen** [comment]
Readmes are bumped but dont forget to update current_version.txt after full release.

**Comment by kavinsky** [comment]
@dedmen thx bro

**Comment by dedmen** [comment]
oops
