### ISSUE TITLE
Spectator can't hear players

### ISSUE THREAD

**Issue by dedmen** [michail-nikolaev/task-force-arma-3-radio#1151]
When in spectator mode you can't hear other players near you.
Questions:
How to detect Spectator mode? :x if anyone knows tell me.

**Comment by LISTINGS09** [comment]
Check if "tf_forceSpectator" variable is true for the player?

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/7c2fc03dcf659c54f0b12a1c4fc98b054b40f4bc/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_forceSpectator.sqf

**Comment by Arcanum417** [comment]
How is this supposed to work ? I have been experimenting with it and I have set and unset the variable from spectator units and no change, cannot hear players and they cannot hear me.

**Comment by dedmen** [comment]
Uhm... That is the whole reason for this issue... it doesn't work. using the TFAR forceSpectator function just makes you deaf and mute.

**Comment by nomisum** [comment]
For Spectator Cams it would be insanely great to be able to hear/speak to other spectators (non directional) but also hear direct speech on your cameras position (directional).

For sure would be the most anticipated feature for my group.

**Comment by dedmen** [comment]
How do i detect if a player is currently in spectator mode? Is there a script command that returns if player is currently in spectator mode? Thats what's holding me off currently. I don't know how to detect that.

**Comment by nomisum** [comment]
Currently ACE3 (as one provider of spec cams) calls TFAR/ACRE by itself in its function : 
https://github.com/acemod/ACE3/blob/master/addons/spectator/functions/fnc_setSpectator.sqf

If you provide an alternative to "ForceSpectator" they could provide a param to call it.

But I fear there is no eventhandler for spectating in general. Afaik its all some kind of camera.

I'm also not sure about
`["ace_spectatorSet", [_set]] call CBA_fnc_localEvent;` and 
`["ace_spectatorStaged", [_set]] call CBA_fnc_localEvent;`

Could this be an event to listen for?

**Comment by dedmen** [comment]
Hm... Okey if ACE is calling TFAR API for that.. That makes things easier.. So just rewrite the Spectator system. On my ToDo for the next days now.

**Comment by LISTINGS09** [comment]
All the spectator scripts I've seen all reference the same function I linked at the start. 

If that function has been called, assume the player is currently meant to be in spectator mode otherwise you'll have to check any number of different things for the various spectator scripts in use (ACE/BIS/F3/CSSA3).

**Comment by theYoursTruly** [comment]
> How to detect Spectator mode? :x if anyone knows tell me.
You can't. It should be the other way around - TFAR provides function/variable that spectator scripts need to run when they start/finish.

**Comment by dedmen** [comment]
Can somebody create me a mission with ACE spectator? I'm not a missionbuilder. I have no clue how to do that ^^

**Comment by SilentSpike** [comment]
I would but am busy studying at the moment, the simple version though:
- Create new mission
- Set respawn mode to base (the one that uses map markers)
- Activate the ace_spectator respawn template (you can do this through editor mission/MP settings)
- Set respawn delay to something significant

With this setup, ace spectator is entered upon death and exited on respawn.

**Comment by dedmen** [comment]
Thanks. Works as expected and i learned something new ^^.
As a heads-up TFAR Spectator will be rewritten. Spectators can hear players just like in Zeus Camera. Config option so that Spectators can only hear friendly units. So dead people can't forward intel.. Although they technically can see the enemy moving.. but eh..
Spectators can hear other Spectators without 3D positioning. As if they were in Teamspeak without TFAR.
No players on the field can hear Spectators at any time.
Thinking about giving Spectators Listen only Radios... But... Probably not gonna happen.

**Comment by Arcanum417** [comment]
@dedmen Sounds great, the listen only radios would be so awesome, maybe just disable the bind or something ?

**Comment by dedmen** [comment]
Problem is giving the Radios. The Spectator doesn't have an inventory to add them to (i think). And if he has an inventory it may be the one of his dead body laying around. We can't use that either to place radios in it.. But.... If his dead body still has radios in its inventory.. We might already have Spectator Radios.. Have to check that.

And i think for it to be complete the spectator should be able to hear also enemy Radios. Which he normally couldn't because of the encryptionCode... Adding 3 Radio types to him would be ugly.. but then.. The Zeus solution already does exactly that..

**Comment by Arcanum417** [comment]
@dedmen I expect Spectator to be zeus as far as TFAR is concerned. (Zeus with muted mike that is) It sounds like the framework is there for zeus, just use it and shape and work out quirks.

**Comment by dedmen** [comment]
In the backend its very different... Zeus is a flying head.. Spectator is a flying Camera without a body. The without a body is the problem maker here

**Comment by Arcanum417** [comment]
@dedmen Well disregard me and my assumptions that something in ArmA was simple...

**Comment by nomisum** [comment]
I love this is being worked on!

One more idea / suggestion / further improvement: Ability to attach the "3D positional ears" to an object / player, so you basically can zoom out and still hear stuff from the interesting players (like commanders) you have chosen before. A script command would be sufficient, no need to implement something fancy.

**Comment by dedmen** [comment]
My test was weird... I tried different ways to get the cameras position.. Most of them gave me player position.. one gave me close to [0,0,0] and the last got me the correct position. It was spectator after death so it should still be attached to my dead body i think,
That is already existent... You can set the function that returns the cameraPosition with a simple setVariable [varname, {return your position and viewdirection here}]
don't know the correct varname right now

**Comment by dedmen** [comment]
Done with 4f06abf92907a12a837c878b538d78e35e74e745.
Not able to use Radio inside spectator.. Maybe someday... #1176

**Comment by DaPlys** [comment]
Sorry to tear up an old subject, but you wrote: "Spectators can hear players just like in Zeus Camera."
How so? Because neither spectators or me as Zeus, can hear the players around the camera. I am not too good with code, so i havent found anything anywhere.. And i havent found any sort of setting box that can change this. I havent changed the settings in my TS or TFAR. 
We only have one guy who can hear others while in Zeus. However, even if he is not in zeus, he can hear the spectators if they are around him. But that shouldnt be an option? And its not because TFAR isnt working. 

Again, sorry to rip this up, but i havent found anything about this anywhere on the net, or this forum..

**Comment by dedmen** [comment]
@DaPlys Check the `Milestone` of this issue. It's `1.0`. You shouldn't expect to experience any of this in `0.9.x`
