### ISSUE TITLE
Display of current voice volume

### ISSUE THREAD

**Issue by dedmen** [michail-nikolaev/task-force-arma-3-radio#1159]
HUD display of current volume. Small head symbol with a number of brackets.
Clientside setting.

**Comment by Bergonius** [comment]
Agreed. This icon is absolute necessary.

**Comment by SageNTitled** [comment]
I can finally get rid of my nasty CTRL+TAB spam habit?

**Comment by dedmen** [comment]
You can also use the Volume modifier keys. Have a special key for shouting. So you don't have to switch your default voice volume.
Whats currently keeping me from implementing this are the icons necessary for that. I'm a horrible designer.

**Comment by SageNTitled** [comment]
I can help with that. Any size/format specification?

**Comment by dedmen** [comment]
Size dunno... maybe 128x128 or 256x256. Its only a small indicator anyway. And shouldn't be very noticable if you don't look straight at it. I also don't know where to put that icon on the HUD. milsim players may want it to be hidden most of the time :x But for now I'll only put that in the top-right corner i think.

**Comment by SageNTitled** [comment]
[Any good?](https://drive.google.com/file/d/0B_qi1_CreU1gZzRId05LdXdTUHc/view?usp=sharing) Download to see the variants.

**Comment by dedmen** [comment]
Can only see one variant :x I don't have Photoshop installed only Adobe Illustrator currently.
Also i should have told you that beforehand... We need 3 "signal bars" for the 3 volume settings.. Or just making the whispering one 0 bars would probably also be fine. Also I'd prefer some kind of face icon with the sound coming out of the mouth. But thats just wishes i can't fulfill myself :D 
The speaker you've done is probably just fine.

**Comment by SageNTitled** [comment]
[Reupload.](https://drive.google.com/file/d/0B_qi1_CreU1gUlZJRGNzaDZvR1E/view?usp=sharing) I may be able to create a face icon in time for 2.0. :)

**Comment by theYoursTruly** [comment]
Here is some [contr-proposition](https://drive.google.com/drive/folders/0B6JJ3fdN7V6NVnpjd1ZQNDl6SkE?usp=sharing) to make it interesting ;)

**Comment by dedmen** [comment]
@theYoursTruly Thank you. You just showed me the perfect position to put @SageNTitled 's speaker icon XD You always have to remember there are Life servers running TFAR. Just some Bars may be confusing to some people.

**Comment by dedmen** [comment]
Implemented in Pre-release 218
