### ISSUE TITLE
Incorrect behaviaour using "Delay releasing push-to-talk" TeamSpeak feature 

### ISSUE THREAD

**Issue by Bergonius** [michail-nikolaev/task-force-arma-3-radio#1161]
**Arma 3 Version:** `stable`
**CBA Version:** `stable`
**Task Force Radio Version:** `stable`

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- In some cases voice wont transfer through radio or transfer into wrong channel, or even into wrong radio. If you have set "Delay releasing push-to-talk" you will get that bug eventually. If you say something in one channel, and say into another channel quickly enough, your second message will be transferred into channel you spoke into first. But for you it will appear as you sending into correct channels. The sound of open and close message will be sent into correct channels though. Works incorrectly for all channels (direct, regular radio channel, additional channel, different radios, etc) 

**Steps to reproduce:**
- Set TS3 option Settings - Options - Capture - Advanced Options -  "Delay releasing push-to-talk" to something long enough. In my case i have the delay set to 0.3s and able reproduce the bug. (probably will reproduce best at 0.5s and above)
- Go to multiplayer with another player
- Stand close enough to hear direct voice.
- Say something in direct channel and then say something into radio.
- Same with different channels - say something in additional channel, then say in regular channel.

**Where did the issue occur?**
- Dedicated Multiplayer

**Comment by dedmen** [comment]
Do you mean Teamspeak Channels or Radio Channels? ^^
When you press the ingame radio key. A message gets sent to Teamspeak about radio type. Teamspeak then sends a Message to your whole channel with the same info. If you press the Radio button in Arma very quickly that message is also sent very quickly to everyone in your channel. Basically simultaneously to your Arma press... In 0.9.12 it really is simultaneously. Your Arma freezes till the Teamspeak Plugin sent the message to the channel.
When receiving the Plugin checks every sample packet for which frequency the sender is on.. One packet is about 5ms of audio.
Can you test if you can reliably reproduce that? maybe with a PTT delay of 1-2 seconds? I am always playing with 0.5 seconds PTT delay didn't encounter that yet.
Can you also write what happens on the "Steps to reproduce"?

**Comment by Bergonius** [comment]
Everywhere i mentioned channels i meant TFAR channels, such as direct voice, radios and its additional chanels.

After you do steps to reproduce your partner will hear both messages in direct voice, but also hear radio open and close beeps in his radio. 

The correct behavior would be partner hears first message in direct voice, and second message in radio, of course. Still not sure if it happens every time, or not. needs to be tested with large release delay values.

If you finding hard time reproducing, i will make a video of it this weekend.

**Comment by dedmen** [comment]
If you are in direct voice Range you should hear everything over direct voice.
With a radio on the same channel you should hear direct voice AND Radio. So... What i understand is that Only direct voice is heard in these cases and the Radio start/end sounds but no actual Radio transmission?

**Comment by Bergonius** [comment]
Then if partner will be outside of direct voice distance, he wont hear anything in his radio except of beeps. Meanwhile transmitting player will think as he talking into radio, as it appearst him  exactly as if he was using radio.

Same with different channels. If you talk into one radio channel, and then quickly enough into other channel, to you it will appear as you speak into two different channels, when in fact your voice is sent only to first radio channel.

That is definitely incorrect behavior.

**Comment by dedmen** [comment]
Okey. Sounds like receiver doesn't get message that sender is transmitting over Radio. Could be Teamspeak spam protection.
so to reproduce Hold PTT. Then release it and quickly press Radio Send button. 
I don't know why that would be a problem.. I don't know behaviour in 0.9.12. But in 1.0 you can hold down...
Okey I can see one issue.. But doesn't seem to be the one you're describing.. When Having a high PTT delay lets say 5 seconds.
You Press direct speech PTT. Then you let go.. and while the PTT delay runs you start a radio transmission..  Even though you are still transmitting (now on radio).. Teamspeak stops transmitting after the PTT delay runs out.

**Comment by dedmen** [comment]
Could not reproduce your channel switching issue... Even if i hold send then change channels and then very quickly let go of send and press it again... It sends on the other channel as expected.
Just if you switch Channel while you are still transmitting.. It will show you you are transmitting on the new channel while you are still on the old. So you have to atleast let go of the Radio button once when switching channels.

**Comment by dedmen** [comment]
Create a new issue if this still happens in 1.0
