### ISSUE TITLE
Transmit to speaker objects

### ISSUE THREAD

**Issue by 1stLT** [michail-nikolaev/task-force-arma-3-radio#1162]
Hello!
I wondered if it's possible to place a speaker object and to transmit through the radio,  and make the speaker object output your voice so other players can hear you through the speaker object.

If it is possible can you please explain me how to do it?

Thanks,
1stLT.

**Comment by dedmen** [comment]
This is possible with the Static Radios Feature in 1.0
Although you can't just make any object to a speaker. But you can just place an Invisible Radio inside or next to the object.

**Comment by 1stLT** [comment]
@dedmen 
Thanks for your quick response!

How can I make that radio invisible and make it default on speakers and full volume by a script?

**Comment by dedmen** [comment]
There is some Eden feature to make objects invisible. I don't know how I'm not a mission builder.
You can't in pre 1.0. You would have to have atleast picked up the radio once and then lay it on the ground again so you can configure stuff on it via scripts.

**Comment by 1stLT** [comment]
@dedmen Thanks for your support :)

**Comment by dedmen** [comment]
I forgot to implement Volume settings for the static radios thingy. I'll keep this issue open to remind me of that.

**Comment by BryanBoru** [comment]
@1stLT in 3den you should uncheck "show model" in the item attributes to make it invisible. it should still work. However in order to pick up the radio once and then lay it on the ground again so you can configure stuff on it via scripts, it might be easier to see it.

**Comment by 1stLT** [comment]
@BryanBoru  Doesn't the object from the 3den editor work? There's an object called AN/PRC-152.
I tried to give it the 
[call TFAR_fnc_ActiveSWRadio] call TFAR_fnc_setSwSpeakers;
line but it didn't work.

**Comment by dedmen** [comment]
No. If you just place a Radio in 3den the Radio is not initialized so you can't set any settings.
You have to pick the radio up. Wait till Arma see's that you have an uninitialized radio, wait till the server sends you an initialized radio and replaces your uninitialized radio. Now you can place the Radio on the ground again and call [radio classname] call TFAR_fnc_setSwSpeakers;
you have to find the classname out yourself while the radio is in your inventory before you place it back on the ground.

**Comment by 1stLT** [comment]
I checked the radio's class name, it says "AN/PRC -152 1" is that correct?
How can I import the radio to the eden editor after I place it on the ground?

**Comment by dedmen** [comment]
no thats the display name not the classname.
You can't.

**Comment by BryanBoru** [comment]
@dedmen thanks for the correction, got so concerned with the invisibility my mind blanked on having a working radio.

**Comment by dedmen** [comment]
Volume setting Implemented. Maximum is 50 meters. Should be enough. Small Radio speakers just aren't that loud.
