### ISSUE TITLE
"Lower Headset" - decrease radio volume.

### ISSUE THREAD

**Issue by Soyaman** [michail-nikolaev/task-force-arma-3-radio#1165]
This is a feature I much loved in ArmA2 ACRE. It was just a simple scroll function that allowed you to essentially lower the radio volume you received.
Great for those times where you're trying to talk to someone but a bunch of info is being passed around irrelevant to you.

I also apologise if this is the wrong place to post it. I've been following you guys for a while but I wasn't sure where to post this.
Thank you!

**Comment by dedmen** [comment]
Duplicate #880
