### ISSUE TITLE
Vehicle mounted radio has different frequencies

### ISSUE THREAD

**Issue by condolent** [michail-nikolaev/task-force-arma-3-radio#1166]
**Arma 3 Version:** `1.64` (stable / rc / dev)
**CBA Version:** `3.1.2` (stable / dev + commit hash)
**Task Force Radio Version:** `0.9.12` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
- I added this code to all my 6 different vehicles:
```
tf_RadioType="TFAR_rt1523g";
tf_hasLRradio = 1;
tf_range=50000;
```

And every vehicle model has a different frequency, and it doesn't seem to work doing ALT+P to open the long range radio so I can change frequencies.. I have no idea why? It's the same sort of radio (TFAR_rt1523g). The cars are from a mod btw, but that shouldn't really matter, right?

**Where did the issue occur?**
- Dedicated Multiplayer

**Comment by dedmen** [comment]
Different frequency is correct. If you didn't set to use same frequencies in the settings.
tf_hasLRradio should be enough

**Comment by condolent** [comment]
But it's weird because short range radios have the same setup for everyone on the same side, same with normal long range aswell. You mean the tf_same_lr_frequencies_for_side = 0; in my userconfig?

**Comment by dedmen** [comment]
userconfig doesnt exist anymore... and `tf_same_lr_frequencies_for_side = 0;` would disable same frequencies

**Comment by condolent** [comment]
Yeah I meant if I changed it to 1. But it didn't work since userconfig doesn't work anymore

**Comment by BryanBoru** [comment]
Is there no easy way to set those userconfig settings server side anymore?

**Comment by dedmen** [comment]
Just go into Game settings.. We are using the CBA settings thingy. Its even easier to set than userconfig

**Comment by condolent** [comment]
How can I set server-side settings in CBA then?

**Comment by dedmen** [comment]
I just told you. "Just go into Game settings" Options -> Game settings and at the bottom Addon settings

**Comment by condolent** [comment]
Oh I had no idea there was server settings in there. Gonna try it out

**Comment by condolent** [comment]
I think there might be an issue with the variable setting which sort of radio the vehicle has mounted. I should be able to press ALT+P to bring up the settings at the very least, but since the lower-right corner says the radio's name is the same as my car; I think it's an issue with the statement of which radio it should have

**Comment by dedmen** [comment]
@condolent As i already said "need to be logged as admin on the server to set them." Please just read. You can't set server settings if you are not logged in as admin or not on the server.
And you radio classname "TFAR_rt1523g" doesn't even exist. It is "tf_rt1523g"

**Comment by condolent** [comment]
Oh ok, that would be why I've experienced some issues.. I've referred to the wiki for classnames, had no idea it has been updated already
