### ISSUE TITLE
0.9.12 Can't Start Dedicated Server

### ISSUE THREAD

**Issue by cuatristapr** [michail-nikolaev/task-force-arma-3-radio#1167]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `3.1.2` (stable / dev + commit hash)
**Task Force Radio Version:** `0.9.12` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- ErrorMessage: File task_force_radio_items\vehicles.hpp, line 0: '/CfgVehicles.Pers': '�' encountered instead of '='

**Steps to reproduce:**
- Happens whenever I try to load a mission on to my server (using HostHavoc). I've been able to use older versions of the mod tho.

**Where did the issue occur?**
- Dedicated 

**RPT log file:**
- http://pastebin.com/B0DGa4Zk

**Comment by dedmen** [comment]
Your pbo's are corrupted. Redownload them.

**Comment by cuatristapr** [comment]
Will do so, and will keep updating accordingly here. Thanks!

**Comment by cuatristapr** [comment]
If I use the 0.9.8 version with these exacts mods, nothing changed, it works flawlessly.

**Comment by dedmen** [comment]
Try to only start TFAR and CBA. Something is wrong with your server

**Comment by cuatristapr** [comment]
Does this version use a serverconfig file on the userconfig area? Older version had one, maybe its creating some conflict?

**Comment by dedmen** [comment]
It doesn't and it doesn't create a conflict if its still there

**Comment by cuatristapr** [comment]
http://pastebin.com/tNcvGvkZ

CBA 3.1.2 (latest version in workshop)
Using the TaskForceRadioDebug.Altis mission

**Comment by dedmen** [comment]
Are you sure you can use dots in folder names? @CBA3.2 ? 
The issue happens before you even start the Mission,
Can you give me the exact sizes of your TFAR pbos?

**Comment by cuatristapr** [comment]
Yes, some of my working missions with previous version of TFAR use dots in their names so we can keep track of mods. We usually do it to avoid conflicts with newer versions which might make our server unplayable. And yes, it starts to load stuff and stops when encounters an error. 
https://gyazo.com/52243fa1b02d7682729b82df71853c64
https://gyazo.com/d1137a3968676f3efaaf595e6c10d6d4
https://gyazo.com/9c59f0fdc1c28f6e0efb386caa245cb5

**Comment by cuatristapr** [comment]
Info from File Manager through the control panel of the server:
https://gyazo.com/b88c5ca033505244092bc85a9e8c9cab

**Comment by dedmen** [comment]
It loads fine if you just disable TFAR? Please boot up your server once without TFAR and send me the RPT

**Comment by cuatristapr** [comment]
http://pastebin.com/xRYyN3kh

**Comment by dedmen** [comment]
I don't know whats wrong... The PBO's look corrupted.. But they have the correct filesize... Can you md5sum the tfar pbo's ? 
thousands of people already switched to 0.9.12 and no one had this problem so far.

**Comment by cuatristapr** [comment]
task_force_radio.pbo: 13762520a236272fe2b6fecee10e880f
task_force_radio_items: 11cfa8c79678d7b2bdd2bb2681f87236

**Comment by dedmen** [comment]
Those are absolutely correct... I am running the exact same files on my Linux server. And i know a group thats running windows server just fine.

**Comment by cuatristapr** [comment]
Could you re-run me through the steps you did to setup the mod? Maybe I forgot something.

**Comment by dedmen** [comment]
I put the modfolder into the serverfolder and added it to the -mod start parameter.. Just like every other mod.

**Comment by cuatristapr** [comment]
Tried again, no success. I might tinker with it a little bit before bothering again. Thanks for your time.

**Comment by cuatristapr** [comment]
I submitted a ticket to HostHavoc to see if they can give me any insight.

**Comment by cuatristapr** [comment]
HostHavoc throwing shade at you guys
https://gyazo.com/d7758338a33d8bd559428387349ebefc

**Comment by dedmen** [comment]
Yeah thats what i would also expect from RPT.. But your files are literally the same as on my server. And its running fine for me.

**Comment by dedmen** [comment]
Problem still there?
