### ISSUE TITLE
Can't stop transmitting when leaving vehicle

### ISSUE THREAD

**Issue by dedmen** [michail-nikolaev/task-force-arma-3-radio#1170]
When transmitting on airborne radio while leaving vehicle you can't stop transmitting. Unless you reenter vehicle and start->stop transmitting again.

**Comment by dedmen** [comment]
Should be solvable by still leaving TangentReleased function available even if not in a suitable vehicle. It won't do harm.

**Comment by dedmen** [comment]
Seems like this was already done..
Test what happens on LR Tangent release after leaving vehicle and not having a radio anymore. I suspect script error because TFAR_fnc_activeLrRadio will return Nil. If that happens 
if isNil exitWith TF_tangent_XX_pressed = false; RELEASE ALL TANGENTS

**Comment by BmanDesignsCanada** [comment]
I've also just noticed this bug. Would it be possible to use the `GetOutMan` event to force the transmission to stop. Waiting for TangentReleased would allow a player to keep holding down transmit when they're outside of the vehicle.

**Comment by SekiAlpha** [comment]
@dedmen hasn't this been fixed?

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1170#issuecomment-287635950

Not sure.

**Comment by dedmen** [comment]
Issue was that
`[_radio select 0, "tf_range"] call TFAR_fnc_getLrRadioProperty)` didn't have a default value. And default default value is empty string. And STRING * NUMBER doesn't work and crashed the script.
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/events/keys/fnc_onLRTangentReleased.sqf#L43

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/c92404cf7edabcb837232384789ebc4a415eeb8b
