### ISSUE TITLE
add intercom system inside vehicle

### ISSUE THREAD

**Issue by kripto202** [michail-nikolaev/task-force-arma-3-radio#1172]
add the function to have an intercom system between pilot, gunner, copilot, and crew. This will allow the heli crew to communicate to each other easily without having to use their radios.

**Comment by dedmen** [comment]
Already done. #974 use search function

**Comment by kripto202** [comment]
#974 has been closed, with ACRE being open source, it should be reopened and use their system as a reference

**Comment by dedmen** [comment]
What? Yeah.. #974 has been closed because it's done. What has this to do with ACRE?

**Comment by kripto202** [comment]
it has yet to be implemented as far as I've seen. It looks like if it is going to be implemented it would be 1.0.  ACRE has their own intercom system and I was saying that it could be a good reference to look at since they currently have it working right now.

**Comment by dedmen** [comment]
Its already done being implemented in 1.0. Thats what I'm trying to say. Most of it in a4397b41438883509d3fb382060f073d14456e43 which also has a ton of other stuff and ebae0c89d1e833bb9cb3afac458934faeacb1d5c.
It is on the Pre-release changelog https://github.com/michail-nikolaev/task-force-arma-3-radio/releases/tag/1.0-PreRelease
