### ISSUE TITLE
Dropbox Link 404s

### ISSUE THREAD

**Issue by BryanBoru** [michail-nikolaev/task-force-arma-3-radio#1175]
**Task Force Radio Version:** `Github/Master`

**Description:**
- On [Github/task-force-arma-3-radio/arma3/@task_force_radio/addons/textures/dropbox.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/textures/dropbox.txt) the links are to [404 pages](https://www.dropbox.com/s/5860wlc3py7jmo4/Backpack_Texture.7z?dl=0).
#

**Comment by jokoho48** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/extra/textures/dropbox.txt
there are the newest downloads. they moved it from Dropbox to Google Drive and they currently not working on the master branch. they working on 1.0

**Comment by dedmen** [comment]
Duplicate #1101. Thanks @jokoho48

**Comment by BryanBoru** [comment]
Copy. I am already in Slack and was just looking around the files. Thanks for the clarity.
