### ISSUE TITLE
use TFAR system with Usung radio backpacks

### ISSUE THREAD

**Issue by 1stLT** [michail-nikolaev/task-force-arma-3-radio#1177]
Hello,
I'm creating a mission based on the war in Vietnam.
I'm using the Unsung mod and the apparently the radio backpacks in this mod are not working with TFAR.
Is there a way to make the backpacks work with TFAR?

Thanks!
1stLT.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-For-developers

**Comment by 1stLT** [comment]
@dedmen  Thanks! :)
Can you please send me alink for the discord server?

**Comment by dedmen** [comment]
#1116  https://discord.gg/8emCVsz
