### ISSUE TITLE
Two servers, two channels

### ISSUE THREAD

**Issue by exploadead** [michail-nikolaev/task-force-arma-3-radio#1180]
Доброго времени суток! Это действительно лучшая рация. У вас на сайте не работет отправка сообщения разработчику. Поэтому пишу сюда - один вопрос: У нас есть два сервера, на которых хотим использовать рацию по полной программе, то есть чтобы людей переносило в запароленый канал автоматически, чтобы они не слышали мёртвых и тд. На одном сервере уже это работает, в ТС создан канал TaskForceRadio с паролем 123, и люди заходящие на сервер игры и сидящие при брифинге в другом канале автоматически перебрасываются. Теперь вопрос - а как сделать два таких канала для двух игровых серверов? Одних людей будет в один канал перебрасывать, других в другой... Но если название и пароли одинаковые, то как плагин поймёт кого куда перебросить?)

**Comment by kavinsky** [comment]
Please use english.

**Comment by dedmen** [comment]
You can use the TFAR module to set the Name of the Teamspeak channel.. Just use different Channel names.
