### ISSUE TITLE
Addition of server side config for direct voice fade distance

### ISSUE THREAD

**Issue by rufjame** [michail-nikolaev/task-force-arma-3-radio#1181]
Is it possible to add a config server side to change how far direct voice travels as the volume fades?
Would be nice to be able to bump up direct voice on occasion a little bit so people within 30-40m can hear the person talking.

Currently people sound fine right in front of you but 30m away they seem quieter than they should even when yelling is set.

E.G
1.0 - As it is now
0.5 - Voice travels twice as far for each db it drops in TS?

**Comment by dedmen** [comment]
the current voice distance is inside the variable `TF_speak_volume_meters` which may be different for each client depending on their whispering/yelling setting.
There is also `TF_speak_volume_level` that is either "whispering","yelling" or "normal".
The volumes that are set when switching your volume using the hotkeys are hardcoded to 5,20,60
but you can just change the `TF_speak_volume_meters`  variable to 80 for example.. and then the normal volume dropoff curve will be applied over 80 meters. But it will be reset to the default value again when the player changes his volume

**Comment by dudakov** [comment]
> The volumes that are set when switching your volume using the hotkeys are hardcoded to 5,20,60
But what is the problem to put this values into config?
It's a good practice to put settings into config. So someone can adjust these settings by changing config, but not changing the code and maintaining the own copy of addon source code.

**Comment by dedmen** [comment]
no real need for that i guess. Human hearing range is just something thats constant i guess ^^
