### ISSUE TITLE
Whenever I download TFAR, there's only ever one folder in the zipped file: @task_force_radio. Ive watched countelss vides and read several forums but no one else seems to have this problem. Please help.

### ISSUE THREAD

**Issue by Church103** [michail-nikolaev/task-force-arma-3-radio#1182]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** `x.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by BryanBoru** [comment]
Where are you downloading the addon from? Github? Steam? Armaholic? PlayWith? etc...

**Comment by dedmen** [comment]
There is supposed to be one folder in there. You put that into your Arma folder just like any other Mod out there.
