### ISSUE TITLE
Teamspeak 3.1 released today but TFAR not compatible

### ISSUE THREAD

**Issue by C0kkie** [michail-nikolaev/task-force-arma-3-radio#1186]
**Arma 3 Version:** `newest / stable` 
**CBA Version:** `newest / stable` (stable / dev + commit hash)
**Task Force Radio Version:** `newest 9.12` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
I downloaded the new stable 3.1 teamspeak version but the tfr plugin is not compatible: 
Api version is not compatible: 20 (newest: 21)

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by dedmen** [comment]
According to Downloads page from Teamspeak.com 3.1 isn't released yet. Latest beta i can find is from 16.12.2016 which i have on my development machine and it can run the 0.9.12 plugin just fine. Investigating further...

**Comment by C0kkie** [comment]
its official. I downloaded it from the stable channel. They write the stable release will be released in stages

**Comment by dedmen** [comment]
I can't find it anywhere.. Neither in their Forum nor their downloads page nor their 4players ftp.
Can you please go to your Teamspeak directory.. Right-click your ts3client.exe go to preferences and details and send me the full version number that is displayed there?

**Comment by C0kkie** [comment]
Yes ofc. Fileversion: 3.1.0.0

there was also a teamspeak news in the bottom of the teamspeak

**Comment by dedmen** [comment]
Ahh thank you.. I know what's wrong.. I'll get a new Plugin build right now.

**Comment by C0kkie** [comment]
alright, nice =)

**Comment by dedmen** [comment]
[TFAR_plguins_0.9.12_3.1compat.zip](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/694050/TFAR_plguins_0.9.12_3.1compat.zip)
There ya go.. These "should" work. Couldn't test because i don't have access to Teamspeak 3.1 yet.

**Comment by C0kkie** [comment]
Yep works for me

**Comment by dedmen** [comment]
Much thanks for getting an issue fixed because it got to be a real issue ;) Will keep this open so everyone sees it.. hopefully.

**Comment by mmetully** [comment]
http://forum.teamspeak.com/threads/128756-TeamSpeak-3-Client-3-1-0-released-Staged?p=440272#post440272

They are doing a staged rollout. Your patch worked for me. I am also running stable.

**Comment by Himeki** [comment]
I had the 3.1 update pop up when I started TS3 this morning and among other frustrations this popped up.

Came here intending to post the same issue, nice to see it's already fixed.

**Comment by CarterDavison** [comment]
I hate to be that guy, but where do I put the patched .dlls?

**Comment by Himeki** [comment]
TS3 Folder>Config>Plugins

**Comment by makis83** [comment]
Could you guys please update the version 0.9.**2** which is currently being used on WOG A2 server.
Thanks in advance.

**Comment by dedmen** [comment]
@makis83 no. ;) If you want to play on a horribly outdated version then thats your problem.. Unless its a typo for 0.9.12.. in that case.. this is already 0.9.12

**Comment by makis83** [comment]
@dedmen I'm sure there are still servers people playing OFP and A1. Depends on habits :)
Thx for the hope. Will be waiting.

**Comment by kavinsky** [comment]
@makis83 The A2 port was done by Levrex not by us, also he added alot of more radios to it. You should ask him.

**Comment by Tisor** [comment]
Patched dlls are not working for me. I'm running 3.1.0.1 with the patchs provide above by dedmen.

Still get the "Api version is not compatible: 20 (Actual: 21)".

Yes, I'm sure I have overwriten the correct ones and so on.

**Comment by dedmen** [comment]
3.1.0.1 is already out? You really really sure you replaced the correct ones? they are in appdata. 
Have to get my hands onto 3.1.0.1 to check that...

**Comment by makis83** [comment]
@kavinsky thx for the info. I was told we already got the updated version.

**Comment by C0kkie** [comment]
i am using the 3.1.0.1 and taskforce is working @dedmen  @Tisor

**Comment by agorapolis** [comment]
Hello, can you update the ts3_plugin installer for the 0.9.12 please ?

**Comment by thorwe** [comment]
To clarify, user addons are - depending on your selection during installation - installed by the 3.1 package installer to either %APPDATA%/TS3Client/plugins or [YourTeamSpeakFolder]/config/plugins ("portable").
The [YourTeamSpeakFolder]/plugins folder still exists for the plugins that are delivered with the client (better for machines with several user accounts).
The locations were added primarily to be able to install .ts3plugin/etc files without UAC annoying the hell out of everyone, especially with the automatic addon updates for addons installed from within the client.

dll loading from the new location is preferred over the old one, e.g. if you have an old something.dll in [YourTeamSpeakFolder]/plugins and a new one in %APPDATA%/TS3Client/plugins, the client will load the new one. The other way round ain't healthy.

**Comment by Mihax209** [comment]
@dedmen Hey, I updated my TS to version 3.1.0.1 (but the same thing happened on 3.1 as well), I installed the updated .dll file in the TS plugin folder. It almost works apart from not hearing any of the TFR sounds. That is, I can hear the radio chatter (with distorted speech as per usual) for short range and long range, but I can't hear any of the "cghh" sounds for the transmission start and end (beeps, for the long range).

I checked the TS log, and it had a bunch of errors from TFR, maybe you could help me (and others, I assume) resolve it. I checked with another guy who updated TS and installed the updated .dlls and he had the same problem with same error messages.

Thanks.
![screenshot_22](https://cloud.githubusercontent.com/assets/8918186/21938575/9703f82c-d9c4-11e6-94f1-3a3f965e52c6.png)

**Comment by Tisor** [comment]
The new location has the deal, I always have add plugins to Program Files, never heard about AppData.

Is working now. Sorry for the inconvenience.

**Comment by coachwn** [comment]
Had to roll TS back from 3.1 to last known good config since it was creating all kinds of errors on my machine. Hell I hadn't had a BSOD in nearly 4 years since starting to run Win10 test versions and within 2 hours of TS 3.1 showing up on my system I got a BSOD and it was all related to that messed up change in the code they have. I now can not get the update since it says that "you are running the latest version" when I do the update check on TS.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/releases/tag/0.9.12
the TeamspeakPlugins.zip have been updated to the 3.1 compat dlls and I've added a Plugin installer to the Downloads that will install the new Plugins.

**Comment by SSederberg** [comment]
Teamspeak has updated to 3.1.4 and TFAR is incompatible via issue #1246

**Comment by dedmen** [comment]
@SSederberg Just played 2 days ago with a couple People running 3.1.4. Worked fine. Problem is 3.1.4 Plugin system is somewhat bugged. In that it tells you the Plugin is enabled but really isn't. Nothing on the Plugin Interface changed in 3.1.4

**Comment by SSederberg** [comment]
@dedmen Thanks for the heads up, I'll make sure my greenhorns (and the rest of my unit) know.

**Comment by tris111** [comment]
The TFR and TFAR are two different mods that why its not working. here
http://steamcommunity.com/sharedfiles/filedetails/?id=894678801&searchtext=Task+Force+Arrowhead+Radio
http://steamcommunity.com/sharedfiles/filedetails/?id=620019431

**Comment by dedmen** [comment]
@tris111 Some people have a brain. Some people don't. That often causes problems.
