### ISSUE TITLE
Zeus falling sound issue

### ISSUE THREAD

**Issue by callofmarty** [michail-nikolaev/task-force-arma-3-radio#1189]
Arma 3 Version: newest / stable
CBA Version: newest / stable 
Task Force Radio Version:  dev 1.-1.0.168

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
When using Zeus as entity i hear falling sound when i go above certain height.

**Steps to reproduce:**
Create zeus as entity and play with it in editor or any other scenario.

**Where did the issue occur?**
everywhere 

**RPT log file:**

**Comment by dedmen** [comment]
Ahh now i know why it would disable simulation on curators. Will fix shortly

**Comment by callofmarty** [comment]
Very nice! Let me know where adn when can i download the fix for it. Thx

**Comment by dedmen** [comment]
should(TM) be fixed next release.
