### ISSUE TITLE
Speak to additional channel via "T" key not working

### ISSUE THREAD

**Issue by mikehudak** [michail-nikolaev/task-force-arma-3-radio#1191]
**Arma 3 Version:** `1.66.139586` (stable)
**CBA Version:** `3.1.2` (stable)
**Task Force Radio Version:** `1.-1.0.168` (dev)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
- When trying to talk to additional channel via "T" key (default key) I can't speak to radio and radio is not responding to command (no hint to transmitting is displayed ). Not working on short wave and long wave radio either. Also tried to change key binding with no effect.

**Steps to reproduce:**
- Set additional channel on radio
- Switch to different channel
- Try to speak to additional channel via "T" key (default key)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**RPT log file:**
http://701sog.cz/cache/tfar_test.rpt

**Screenshoot:**
http://701sog.cz/cache/tfar_test.png

**Comment by Robdemi** [comment]
Can confirm I'm having same problem.

**Comment by BryanBoru** [comment]
I use it extensively in my unit's operations, including yesterday. Have had no issues. Are you sure there is not a conflicting mod overwriting CBA keybindings? Have you tried running with just TFR/CBA combo?

**Comment by BryanBoru** [comment]
Are you running either of the recent TS3 updates? 3.1 or 3.1.1?

**Comment by mikehudak** [comment]
This report is created only with TFAR and CBA addons. Using TS3 3.1

**Comment by Robdemi** [comment]
I also tried it with the newest version of CBA w/e version that may be. I also tried an older version of CBA from months ago. Nothing changed it. I'm still unable to use talk on additional channel. I have also tried rebinding then as well. Nothing worked.

**Comment by Robdemi** [comment]
I'm also using USA keyboard if that makes any difference.

**Comment by dedmen** [comment]
I'm interested how you got TS 3.1 with the 168 pre-release... because that's not compatible with TS 3.1.
Also the cause is a known Script error in a TFAR file.. As shown in the screenshot and RPT... Why are you guys saying it might be CBA? It's not.. It's clearly showing a Script error inside TFAR and thats exactly what the error is. It has nothing to do with CBA or Teamspeak. So please don't confuse people by saying it might be CBA or Teamspeak or the Keybinds. I already fixed it yesterday evening. But i currently can't do a new Pre-release build.

**Comment by dedmen** [comment]
Also 3ee31717a25d1fc0a9a87d226497fc799a73521f

**Comment by mikehudak** [comment]
Can we have pre-release with this fix?

**Comment by dedmen** [comment]
> Also I currently can't do a new Pre-release build on our buildserver. But i will do a manual one on my local machine soonish.
Just got the build server fixed.. It's building right now..

**Comment by dedmen** [comment]
Pre release 188 just got released and contains the fix
