### ISSUE TITLE
TFR radios unable to be removed from player using code

### ISSUE THREAD

**Issue by RogueDGA** [michail-nikolaev/task-force-arma-3-radio#1192]
This is more of a question than anything but I guess you could call it an Issue. I'm trying to add some code into a script that strips players of their gear, everything else is finished and working however I'm unable to find the TFR radios in "weapons player;" "items player;" and "assignedItems player;" , in fact no matter what code I try it stays on the player, if I add an "ItemRadio" to the player and remove it using code it gets replaced by a TFR radio (which cant be removed by code). I'm just wondering if there's a line of code that works to remove the players radio and places it on the ground, and if not have you guys done this intentionally?

**Comment by dedmen** [comment]
A players Radio is always inside assignedItems or items just like any other item too.

**Comment by RogueDGA** [comment]
Well I guess you can make this an issue because it's not showing up or removing from the player for me

**Comment by dedmen** [comment]
how are you trying to remove them? It's not an issue. They are in there.. for real.

**Comment by RogueDGA** [comment]
ive tried these 
`player removeItem "tf_anprc152";`
```
if("TFAR_anprc152" in (assignedItems player)) then {
hint "found the radio";
} else {
hint "its not here";
};
if("TFAR_anprc152" in (items player)) then {
hint "found the radio";
} else {
hint "its not here";
};
``` these gave me the hint "its not here"

**Comment by dedmen** [comment]
Its correct that these don't work. Because the classname won't be
tf_anprc152. It will be tf_anprc152_id where id is a number between 0 and
1000 which you should already have noticed if you looked what was returned
by `items player` or `assignedItems player` which you apparently didn't
although you were saying you did..
You can use `classname call TFAR_fnc_isRadio` which will return true if
that item is a Radio.
For example `"tf_anprc152_37" call TFAR_fnc_isRadio` will return true.

**Comment by dedmen** [comment]
Also the classname is tf_anprc152 in TFAR 0.9.x but in 1.0 it will be
TFAR_anprc152 so it's a bad idea to scan by classname.

**Comment by nomisum** [comment]
@dedmen btw will the classname_id system stay the same? (I'm using it to give my telephones a unique frequency offset depending on the ID.) I dont care if the prefix changes tho.

**Comment by dedmen** [comment]
It will stay the same as long as BI doesn't provide a better solution.. Which will probably mean till Arma 4 it will stay like this.

**Comment by Reekoj** [comment]
@dedmen 
Can you use `"classname+ID" createVehicle getpos player` to spawn a radio on the floor after removing it from the inventory with the help of TFAR_fnc_isRadio in a foreach on assignedItems player and items player ? If it's possible, will the radio stay on the same frequency ?

**Comment by dedmen** [comment]
@Reekoj if you spawn exactly that Item on the ground yes. But The Radios are not vehicles they are weapons. I don't know how Arma likes if you createVehicle a Weapon. But you can createVehicle a WeaponHolder and add the Radio into that. That is actually a requirement for Speakers to work. That the Radio is inside a WeaponHolder.

**Comment by Reekoj** [comment]
Oh ok great. Thank you for the help !

**Comment by dedmen** [comment]
If you need scripting help it's always good to ask in our Discord #1116
