### ISSUE TITLE
Question: Divers Transmitter class name

### ISSUE THREAD

**Issue by Guy-Markman** [michail-nikolaev/task-force-arma-3-radio#1193]
What is the class name of the transmitter? TFAR_Transmitter not working, and it's not in the API

**Comment by dedmen** [comment]
There is no Divers Transmitter. What do you mean by that?

**Comment by dedmen** [comment]
That is the Rebreather the default Arma one

**Comment by dedmen** [comment]
In TFAR 1.0 you need to have a short-range Radio that does the transmitting

**Comment by dedmen** [comment]
If you have questions or anything please use our Discord #1116 Github issue reports are meant for issue reports.

**Comment by Guy-Markman** [comment]
Another question, what is the right classname for rt1523g

**Comment by kavinsky** [comment]
if you are using 0.9.X version is `tf_rt1523g` wiki is updated to new unreleased version 1.X
