### ISSUE TITLE
Private Exile Server: "No task force radio deployed on server"

### ISSUE THREAD

**Issue by TheRavenBlue** [michail-nikolaev/task-force-arma-3-radio#1194]
(Hosted on a decicated server in my home)
Hi!
I have a problem with TFAR and Exile, I have enabled CBA support in the Exile config:
`		// Set this to 1 if you want to have CBA support`
		`useStackedEH = 1;`
But when I join the server I can hear it move me to the TaskForceRadio channel (in loading screen), then I see the error "No Task Force Radio deployed on sever" and it moves me back to the previous channel.
I would really want this to work on my Exile server it would bring a lot of extra "realism" when fighting against Zombies.

**Comment by dedmen** [comment]
Well... Is TFAR running serverside? It probably is but... Check twice to be sure.
Which version of TFAR are you using?
As you get moved to the TFAR channel everything is apparently working.. And then something is stopping it.. I'm guessing its some Exile script that purposefully stops TFAR's scripts.
I have no Idea of Exile I just know it's very unfriendly to most Mods...

**Comment by TheRavenBlue** [comment]
I can see TFAR ingame and when pressing caps lock I can see "Transmiting" so it is running server side.

**Comment by dedmen** [comment]
Caps lock when Transmitting and seeing the UI's is clientside.

**Comment by TheRavenBlue** [comment]
I already did ask there without any help, I changed from TFR to ACRE2 and now it works fine! Thanks for the help anyway!

**Comment by dedmen** [comment]
Good luck.

**Comment by dedmen** [comment]
I found the Problem though.. Exile is using this https://community.bistudio.com/wiki/onEachFrame and that is breaking any Stacked Eventhandlers which is what TFAR was using till 0.9.12. Either you remove that From Exile or you use TFAR 1.0 which is still beta or you use ACRE.
