### ISSUE TITLE
Task Force Radio not working on certain missions.

### ISSUE THREAD

**Issue by yurivw** [michail-nikolaev/task-force-arma-3-radio#1195]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**Task Force Radio Version:** `v0.9.12` (stable)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@MCC Sandbox 4`
- `@Advanced Urban Rappelling`
- `@Advanced Sling Loading`
- `@Advanced Rappelling`
- `@Advanced Towing`
- `@Ares mod- Achilles Expansion`

**Description:**
- On certain missions, for example any DUWS mission the radio stops working completely. 
In Teamspeak it will say Connected Y Play N
I CAN play other missions with the same mods and the same people.

**Steps to reproduce:**
- Load up any DUWS mission, check Teamspeak.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**RPT log file:**
- To be added.

**Comment by dedmen** [comment]
Can you lik me one of these DUWS missions?

**Comment by yurivw** [comment]
Certainly.

**Tanoa**
`https://steamcommunity.com/sharedfiles/filedetails/?id=778257506&searchtext=`
**Unofficial V1.22**
`https://steamcommunity.com/sharedfiles/filedetails/?id=285488366&searchtext=DUWS`
**DUWS Rebirth**
`https://steamcommunity.com/sharedfiles/filedetails/?id=393315278&searchtext=DUWS`
**The original one**
`https://steamcommunity.com/sharedfiles/filedetails/?id=167274881&searchtext=DUWS`

**Comment by dedmen** [comment]
try this one
[tfar_duws_rebirth.zip](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/716917/tfar_duws_rebirth.zip)

**Comment by yurivw** [comment]
Hey, that works! 
Did you find that anywhere or did you edit the mission? If so, what exactly did you do so I can try it on the other missions as well.

**Comment by dedmen** [comment]
I told you. look for `onEachFrame` in the mission. In the DUWS one it was in initHQ\drawicon.sqf just remove that one line.
