### ISSUE TITLE
Short Range Radio Dialog Does Not Open With Multiple Radios in Inventory or Outside Radio Slot

### ISSUE THREAD

**Issue by MSGTJohnson357** [michail-nikolaev/task-force-arma-3-radio#1196]
**Arma 3 Version:** `1.66.139586 stable`
**CBA Version:** `3.1.2.161105` 
**Task Force Radio Version:** `1.-1.0.193`

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@ace3`
- `@RHSAFRF`
- `@RHSUSAF`
- `@RHSGREF`
- `@SMA V2.7.1`
- `@TRYK(ver 0.95 fix3) [TRYK's Multi-play Uniforms]`
- `@VSM - Accessory Pack`
- `@VSM_Uniforms`
- `@VSM_VestsHelmets`

**Description:**
- If you have more than one radio, such as one in the radio slot, and one in your uniform, you cannot open either radio, no matter which is set as active. Choosing the settings option on either radio does nothing.
- If you have a single short range radio outside of the radio slot (eg. in your uniform/vest), and is not set as active, you cannot open the dialog to edit the settings.
- Issue is only limited to short range handheld radios. Everything works fine with long range, and selecting another radio within a vehicle.

**Steps to reproduce:**
- Add two handheld radios to your loadout
- Open the short range dialog
- Select settings from either radio
- Dialog doesn't open up
OR
- Add one handheld radio to your inventory, outside the radio slot
- Open the short range dialog
- Select settings
- Dialog fails to open

**Where did the issue occur?**
- Self-Hosted Multiplayer

**RPT log file:**
- http://pastebin.com/YXxab08R

**Comment by dedmen** [comment]
Reworked the ShortRange radioList function... I could have sworn I've read this exact issue report yesterday.. But apparently you only posted this today ^^
Expect fix this evening (GMT) or tomorrow.

**Comment by dedmen** [comment]
Very interesting.... The UI does two things on clicking the button.. setting a variable and calling a function.. The variable is being set and if i call the function manually it also works fine
