### ISSUE TITLE
Getting unable to get file version size.

### ISSUE THREAD

**Issue by XDARKMCX** [michail-nikolaev/task-force-arma-3-radio#1202]
So for past month I have been getting kicked on servers that require task for radio downloaded through steam workshop. http://pastebin.com/hj6Rq19V is the link the rpt file which indicates unable to get file version size: C:\Program Files (x86)\Steam\steamapps\common\Arma
3\!Workshop\@task_force_radio\task_force_radio_pipe.dll. So this problem only persists on tfar mod when launched through arma 3 launcher. When I download a modpack throught arma 3 sync and also download tfar throught thats it also persists.  Can you please fix this problem I'm getting on latest arma 3, cba and tfar version.
http://pastebin.com/hj6Rq19V

**Comment by dedmen** [comment]
"unable to get file version size" gets printed almost always and is not an error
I can't see anything about you getting kicked in your RPT.

**Comment by dedmen** [comment]
Closing because no answer for a month.
