### ISSUE TITLE
Try to set Nick Name and Cant Talk Or hear [fixed]

### ISSUE THREAD

**Issue by Emillacour** [michail-nikolaev/task-force-arma-3-radio#1203]
**Arma 3 Version:** `1.66` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** `9.12` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio
- @La Coya Life (work fore Others )

**Description:**
-  On teamspeak it keeps trying to set nickname and ingame cant talk and cant hear .... 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated Arma Life Severs

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Emillacour** [comment]
i just Reinstallet MY pc and now it dont work I dit have it working on my pc before and Working but after a Total PC wipe It dont :) thanks Fore help ... i have Tryed Meny Things

**Comment by dedmen** [comment]
Your english awful. Hurts eyes. 
It keeps trying to set your nickname? go into Teamspeak in your Nickname field and press Enter.

**Comment by Emillacour** [comment]
arh i know :) sorry for thad ... but i cant talk ingame

**Comment by dedmen** [comment]
Do you get any error message ingame? on the bottom right? 
What do you mean by you can't talk? I'm sure you can open your mouth. Do other people not hear you? does the blue light in Teamspeak not light up?

**Comment by Emillacour** [comment]
the blue light do light up and other cant hear me and when i do enter in my name box it just op up agen

**Comment by Emillacour** [comment]
dedmen is there a teamspeak i can join to talk to you on so i can tell you :)

**Comment by dedmen** [comment]
What is your ingame Name? Does it end with a Space?

**Comment by dedmen** [comment]
When teamspeak tries to set your name and that box comes up. Click into the box. and press CTRL+A and CTRL+C and paste that here

**Comment by Emillacour** [comment]
it is emil la cour

**Comment by Emillacour** [comment]
no space
but i cant talk and others cant hear me and i cant hear them

**Comment by Emillacour** [comment]
oh got i fixed ! There was a problmen with my Firewall it dit block the code
