### ISSUE TITLE
TS3 Plug In mac voice volume cap

### ISSUE THREAD

**Issue by BryanBoru** [michail-nikolaev/task-force-arma-3-radio#1204]
**Arma 3 Version:** `1.66`
**CBA Version:** `3.1.2`
**Task Force Radio Version:** `3.9.12`
**TS3 Version:** `3.1.0.1`
**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- dramatic TS3 voice volume limiting when TFAR Plug In is enabled.

**Steps to reproduce:**
- Use TS3 out of game with TFAR plug in enabled in TS3. Then disable TS3 and hear the dramatic increase in max voice volume in TS3.

**Where did the issue occur?**
- all environments
- i can imagine this is a necessary evil for TFAR use, but i do not conceptually understand how.

**RPT log file:**
- Don't think an RPT is relevant

**Comment by dedmen** [comment]
TFAR shouldn't do anything to the Audio when not connected to the game. Someone reported this a few Months ago so this is probably a duplicate issue. And it's also very likely already fixed.

**Comment by BryanBoru** [comment]
I try to reproduce this with TFR 3.1 plug-in on TS3 3.1.0.1 and confirm it has been corrected, thanks again.
