### ISSUE TITLE
Failed to Install Add-On

### ISSUE THREAD

**Issue by Megabyte70** [michail-nikolaev/task-force-arma-3-radio#1206]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** `x.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
-As simple as i can say, i can't even install it. "Failed to install add-on. Do you want to retry as Administrator?" It keeps saying that should retry it as Administrator, but i am the admin.

**Where did the issue occur?**
- Every time i try to install it.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by dedmen** [comment]
Close Teamspeak before installing the Plugin.

**Comment by FiViK** [comment]
thank u bro
