### ISSUE TITLE
cba settings need to be included in preInit

### ISSUE THREAD

**Issue by bux** [michail-nikolaev/task-force-arma-3-radio#1207]
**Arma 3 Version:** `1.66`
**CBA Version:** `3.1.2`
**Task Force Radio Version:** `0.9.12`
**Mods:**
- `@CBA_A3`
- `@ace`
- `@task_force_radio`

> commy2 [1:30 PM] 
> TFAR has to use cba_settings_fnc_init on preInit
> They're doing it on postInit
>The settings don't exist in 3den, so using mission settings will not work with TFAR.
> And neither will setting them in the main menu.

**Comment by dedmen** [comment]
Already fixed in 1.0. We just decided not to do another 0.9.x build anymore
