### ISSUE TITLE
Speech/hearing not returning to Zeus player when AI Released from Remote Control

### ISSUE THREAD

**Issue by Saborknight** [michail-nikolaev/task-force-arma-3-radio#1211]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**Task Force Radio Version:** `1.0-rc209` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@ace3`
- `@adv_urban_rappeling`
- `@asdg_attachments`
- `@burnes_mk10`
- `@em`
- `@fa18_a3`
- `@firewill_f15`
- `@firewill_sar`
- `@laxemann_dynasound`
- `@l_es`
- `@l_immerse`
- `@l_suppress`
- `@mrt_accfncs`
- `@NIArsenal`
- `@project_opfor`
- `@rhs_afrf`
- `@rhs_usaf`
- `@sma`
- `@stui`
- `@usaf`
- `@VSM_Accessory_pack`
- `@vsm_uniforms`
- `@vsm_vests_and_helmets`
- `@wef`

**Description:**
- Once the steps below (not the last step) have been completed, the player next to you can still hear you as if you're still controlling the AI. This requires an exit and re-enter to the Zeus interface for your voice to return to your own body. This isn't a pressing issue, just a little annoying and would probably need fixing before final 1.0 release :)

**Steps to reproduce:**
- Enter the game with Zeus powers.
- Place an AI unit down
- Remote control unit
- Release controls of unit (Which returns you to Zeus interface)
- Try to speak to the person next to you, your voice will still be with the AI and you'll still be hearing as if you're the AI
- Leave and re-enter Zeus interface, problem is fixed now.

**Where did the issue occur?**
- Hosted on a single box by a dedicated admin Multiplayer

**Comment by dedmen** [comment]
`Release controls of unit` By pressing the Z button right? Or via Esc or something?

**Comment by dedmen** [comment]
See https://github.com/CBATeam/CBA_A3/issues/615

**Comment by Saborknight** [comment]
I did it via two different methods, pressing `Z` (which for other English keyboards would be `Y`), and using the scroll option `Release Controls`

**Comment by dedmen** [comment]
Fixed in CBA 3.3 released 2 days ago.
