### ISSUE TITLE
1.-1.0.214 Doesn't work at all

### ISSUE THREAD

**Issue by Arcanum417** [michail-nikolaev/task-force-arma-3-radio#1214]
Works for nobody in our unit,
no positional audio, doesnt switch to TaskForceRadio channel, no radio clicky sounds, 00 in game right bottom corner (newest cba, stable arma)

**Comment by dedmen** [comment]
Thanks for these very extensive and helpful bug report.

**Comment by Arcanum417** [comment]
I know I am retarded, leave me be :D 

Tried 216 seems to work....

**Comment by dedmen** [comment]
Yeah... 214 has known bugs and isn't considered stable. And is also outdated right now...

**Comment by Arcanum417** [comment]
Found the problem
We are using rsync to distribute addons to players and .pbos have the same modify time as the old realese.
So all clients had the old addon. No idea how that happened, but I would appreciate if the last modify date on changed files would be new one.
