### ISSUE TITLE
No Radio Deployed On Server

### ISSUE THREAD

**Issue by JordehDevs** [michail-nikolaev/task-force-arma-3-radio#1215]
For some reason it does not load TaskForceRadio, Like the server runs it, and the players run it and there is a channel named "TaskForceRadio" and i installed the addon but for some reason it says "Radio is not deployed on this server" 

Any help?

**Comment by dedmen** [comment]
Did you load the Mod on the Server? Are you sure you are running the Mod on the Server? Are you really really sure?

**Comment by JordehDevs** [comment]
https://gyazo.com/d0057d24583e6e0b5f7678eecdb1bf43

**Comment by JordehDevs** [comment]
yes im sure

**Comment by dedmen** [comment]
You are sure? You mean that you have entered these in your Server providers settings Panel has to mean they are also loaded? Maybe your server Provider has a error on their side. Also you are loading the Mods twice. You should have nothing in the serverMods section.

**Comment by JordehDevs** [comment]
kk ill try without it

**Comment by JordehDevs** [comment]
same error

**Comment by dedmen** [comment]
Are you sure that CBA is working? And Again. What TFAR and CBA versions are you running

**Comment by JordehDevs** [comment]
TFAR v0.9.12 (Latest) and Cba 3.1.2 (i think)
