### ISSUE TITLE
Not Hearing Others

### ISSUE THREAD

**Issue by JordehDevs** [michail-nikolaev/task-force-arma-3-radio#1216]
Ok, so yesterday I couldnt yet the mod to work at all but now it works and is connected and its deployed although Im Zeus and im the the same freq on a long range radio and channel and the ground team has one and nobody can hear me unless use use normal voice chat any ideas?

**Comment by JordehDevs** [comment]
and also it auto mutes people in the "TaskForceRadio" channel

**Comment by dedmen** [comment]
Are you using the correct Radio? Opfor Radios can't communicate with Bluefor Radios.
Please stop missusing this for your Problems. Github issues are meant for reporting issues with the Mod. And not Problems with your understanding on how the Mod works or how to use it.
I'd prefer if you would ask on Discord. Thanks. https://discord.gg/8emCVsz
