### ISSUE TITLE
Radio duplication issue with 1.0.216

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1217]
**Arma 3 Version:** `1.66`
**CBA Version:** `3.2.1.170227`
**Task Force Radio Version:** `1.-1.0.216`

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- A radio that's either added to inventory via linkItem-command or double click from container is duplicated in inventory as soon as it's being replaced. The ID of the instanciated radios are the same
If you pull it to your inventory (and not on the linkedItem-Slot) or add it via addItem you just get one instanciated version of the radio.

**Steps to reproduce:**
player linkItem "ItemRadio";
or
player linkItem "TFAR_anprc152";
-> Two instanciated radios with the same ID, one in the linkedItem-Slot and one in the inventory.
player addItem "ItemRadio";
or
player addItem "TFAR_anprc152";
-> One instanciated radio in the inventory.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/6bcfb24bb98f2e572db729f884a192d2d9eddb64#diff-df71d93b827ddd11118272b9ded5cb17R77
TFAR_RadioReqLinkFirstItem get's reset at https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/6bcfb24bb98f2e572db729f884a192d2d9eddb64#diff-df71d93b827ddd11118272b9ded5cb17R67
Thanks for the report.

**Comment by dedmen** [comment]
Fixed in b217
