### ISSUE TITLE
TFAR_SameLRFrequenciesForSide not working

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1218]
**Arma 3 Version:** `1.66`
**CBA Version:** `3.2.1.170227`
**Task Force Radio Version:** `1.-1.0.216`

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
If I use ["TFAR_SameSRFrequenciesForSide", true, true, "server"] call CBA_settings_fnc_set; it works fine for SW-radios, but ["TFAR_SameLRFrequenciesForSide", true, true, "server"] call CBA_settings_fnc_set; does not work for LR-radios.

**Steps to reproduce:**
Execute
["TFAR_SameLRFrequenciesForSide", true, true, "server"] call CBA_settings_fnc_set;
and every LR radio (be it backpack or in a vehicle) will still have random frequencies.
It doesn't work with any way of setting TFAR_SameLRFrequenciesForSide be it via editor settings, settings.sqf or however.

**Comment by TheLukio** [comment]
Try disabling random generation of LR frequencies.
<side_settingsvar> = false call TFAR_fnc_generateLRSettings;

**Comment by Pergor** [comment]
That's already in place.
The frequencies, even if they're randomly generated, should be the same for every radio of the same side, hence the bug report.

**Comment by dedmen** [comment]
`(_x getVariable ["tf_lr_frequency",false]) isEqualTo false` 
vs
`(_x getVariable "tf_lr_frequency") isEqualTo false`

**Comment by dedmen** [comment]
Fixed in build 219

**Comment by dedmen** [comment]
Side effect. Every group should have the same default frequencies. Due to bug even that was not happening. Every member in group had his own frequencies.
