### ISSUE TITLE
Cant access Zeus

### ISSUE THREAD

**Issue by BrenSilent** [michail-nikolaev/task-force-arma-3-radio#1221]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**Task Force Radio Version:** `1.0.217` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- You cant access Zeus while TFAR is loaded. In Singleplayer it shows you a message in the lower right corner that you cant use your Radio underwater. In MP it just does nothing.

**Steps to reproduce:**
- Place Unit
- Place Zeus Game Master module
- Set unit as owner of the module
- Start game and try to access Zeus with "Z" Key

**Where did the issue occur?**
- SP/local MP both x32 and x64 client

**RPT log file:**
- http://pastebin.com/5GnRHfwF

**Comment by BrenSilent** [comment]
Issue occurs when using a German keyboard as the "Z" input becomes "Y" which is a default keybind for "LR Transmit Additional". Deleting this keybind solves the issue.

**Comment by john681611** [comment]
As another note when on hardcore mode it kicks you out of the channel every-time you enter zeus making it annoying and obvious when Zeus is active

**Comment by dedmen** [comment]
@john681611 That's why I added a configurable Plugin timeout setting. Just up the timeout and it won't kick you anymore.

**Comment by john681611** [comment]
Where can i find the setting?

**Comment by dedmen** [comment]
CBA Settings in 1.0 Pre-release

**Comment by dedmen** [comment]
Got an Idea for the new default keybind? I'm thinking Shift+T which should be quite intuitive as LR is Shift+Caps (Right? or was it CTRL+Caps?)

**Comment by john681611** [comment]
> CBA Settings in 1.0 Pre-release

Ah ok I'll wait for Full release then.

> Got an Idea for the new default keybind? I'm thinking Shift+T which should be quite intuitive as LR is Shift+Caps (Right? or was it CTRL+Caps?)

To activate what?

**Comment by dedmen** [comment]
Fixed in build 219
