### ISSUE TITLE
Cant install TFR plugins with 0.9.12 

### ISSUE THREAD

**Issue by spm978** [michail-nikolaev/task-force-arma-3-radio#1222]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**Task Force Radio Version:** `0.9.12` (stable)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- My TFR just straight up does not work i have never gotten it to work correctly but the main reason right now is the the teamspeak plugin installer when i try to install it when i download TFR from the website and go to the teamspeak folder and try to run the app but it will not run. It asks me how i want to open the ts3 file and it gives the option " "D:\Teamspeak3\package_inst.exe" "%1" and i dont have a file there named that  

**Steps to reproduce:**
- Not sure 
**Where did the issue occur?**
- Computer itself
![screenshot 1](https://cloud.githubusercontent.com/assets/26496632/24068610/5666bcc2-0b61-11e7-9cd7-6dc1757d6a57.png)

**Comment by kavinsky** [comment]
Try doing right click on the link and click "Download link as".

**Comment by dedmen** [comment]
May need to reinstall Teamspeak so it get's the right path for the package installer again.
Or you can unpack it by opening the plugin installer file with 7Zip or Winrar and manually place the plugins in the Teamspeak folder.
Or you can manually drag&drop the plugin installer file onto the package_inst.exe in your Teamspeak directory.
