### ISSUE TITLE
All vehicles have LR radio

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1223]
**Arma 3 Version:** `1.68 (64bit)`
**CBA Version:** `3.2.1.170227`
**Task Force Radio Version:** `1.-1.0.217`

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
All vehicles have LR radios

**Steps to reproduce:**
Put a playable unit down in the editor, place a vehicle that's not supposed to have a LR radio (like a kart or something) next to it, start mission, get in kart, open LR radio.

**Additional information**
Setting VEHICLE setVariable ["tf_hasRadio", false]; has no effect.

**Comment by dedmen** [comment]
Reproduced with Quad Bike... I wonder why nobody noticed that yet ^^

**Comment by dedmen** [comment]
For some dumb reason I removed the hasVehicleRadio check when trying to get the Radio from a vehicle... Must have been tired when coding that...
https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/f863ecf35616af4551e9adf02f76c70b1cbbd41d#diff-f5fd6808be4322fd12b773c7ae251cb5L24
Maybe I'm always coding while tired.. I should stop doing that...

**Comment by dedmen** [comment]
1.0 build 224
