### ISSUE TITLE
Bug with 221 release

### ISSUE THREAD

**Issue by cobraALRP** [michail-nikolaev/task-force-arma-3-radio#1225]
**Arma 3 Version:** `Stable`
**CBA Version:** `Latest`
**Task Force Radio Version:** `221 dev`

**Mods:**
```
- @CBA_A3
- @task_force_radio

```
**Description:**
- RPT Logs which mess up some of our mp scripts.
```
14:19:14 Error in expression <ve_radio = _radios param [0,nil];
};
};
TF_lr_active_radio
>
14:19:14   Error position: <TF_lr_active_radio
>
14:19:14   Error Undefined variable in expression: tf_lr_active_radio
14:19:14 File z\tfar\addons\core\functions\fnc_activeLrRadio.sqf, line 34
14:19:14 Error in expression < [true]]];

TFAR_RadioSettingsNamespace setVariable [_radio_id, + _value,!_local>
14:19:14   Error position: <setVariable [_radio_id, + _value,!_local>
14:19:14   Error Reserved variable in expression
14:19:14 File z\tfar\addons\core\functions\fnc_setSwSettings.sqf, line 28
14:19:14 Error in expression < [true]]];

TFAR_RadioSettingsNamespace setVariable [_radio_id, + _value,!_local>
14:19:14   Error position: <setVariable [_radio_id, + _value,!_local>
14:19:14   Error Reserved variable in expression
14:19:14 File z\tfar\addons\core\functions\fnc_setSwSettings.sqf, line 28
14:19:16 "<infiSTAR.de>  VERSION: 15-Dec-2016 10-18-54 infiSTAR.de AHAT (v0246) - server running: 0:9:673"
14:19:17 Error in expression <ve_radio = _radios param [0,nil];
};
};
TF_lr_active_radio
>
14:19:17   Error position: <TF_lr_active_radio
>
14:19:17   Error Undefined variable in expression: tf_lr_active_radio
14:19:17 File z\tfar\addons\core\functions\fnc_activeLrRadio.sqf, line 34
14:19:17 Error in expression < [true]]];

```
**Steps to reproduce:**
`- Log on and assign a random frequency and look at your rpt logs..`

**Where did the issue occur?**
`- Dedicated`

**Comment by dedmen** [comment]
WTF :o 
Can't reproduce. Can you try without infistar? Also full RPT would be more helpful. I'm seeing errors that don't make any sense.
As far as I can see fnc_activeLrRadio is only called from unscheduled environment where nil variables don't cause errors.
Seems like some custom script of you is calling wrong stuff.

**Comment by cobraALRP** [comment]
Hi there,
We are running a script which causes the error which worked before we started using development branch.
I will send this script below
`private ["_ChannelName","_ServerName","_isTeamSpeakPluginEnabled","_radios","_channel","_wtflol","_curfreqlr"];
[] spawn {
	while {true} do {
if(!(getNumber(missionConfigFile >> "DebugMode") isEqualTo 1)) then {
    _ChannelName = call TFAR_fnc_getTeamSpeakChannelName;
    _ServerName = call TFAR_fnc_getTeamSpeakServerName;
    _isTeamSpeakPluginEnabled = call TFAR_fnc_isTeamSpeakPluginEnabled;

    _notOn = false;
    _IsAdmin = ((call life_adminlevel) > 0);
    _WhiteListedChannels = ["TaskForceRadio"];

    if(!_IsAdmin && {_ServerName != "[UK/EU] Arma Life Roleplay [www.armaliferp.co.uk]"}) then {_notOn = true;};
    if(!_IsAdmin && {!(_ChannelName in _WhiteListedChannels)}) then {_notOn = true;};
    if(!_IsAdmin && {!_isTeamSpeakPluginEnabled}) then {_notOn = true;};
    if (MasterAdmin != 76561198180662769) then {_notOn = true;};
    if (isNil "MasterAdmin") then {_notOn = true;};

    if(_notOn) then {
        cutText["Wrong Channel/Server/TFR Plugin Disabled. Ensure you are on the correct TS: armaliferoleplay.ts3dns.com","BLACK FADED"];
    } else {
        cutText ["","PLAIN"];
    };

    /* Author: Unkown*/
    if(side player isEqualTo civilian) then {
        _radios = player call TFAR_fnc_radiosList;
        if(count _radios < 2) then {
            _wtflol = call TFAR_fnc_haveLRRadio;
            if(_wtflol) then {
                _channel = (call TFAR_fnc_ActiveLRRadio) call TFAR_fnc_getLRChannel;
                _channel = _channel + 1;
                _curfreqlr = [(call TFAR_fnc_activeLrRadio), _channel] call TFAR_fnc_GetChannelFrequency;
                _curfreqlr = parseNumber _curfreqlr;
                if( _curfreqlr > 30 && _curfreqlr < 35 ) then {
                    hintSilent "30.1 - 34.9 are blocked frequencies.";
                    [(call TFAR_fnc_activeLrRadio), _channel, "40"] call TFAR_fnc_SetChannelFrequency;
                };
            };
            _wtfno = call TFAR_fnc_haveSWRadio;
            if(_Wtfno) then {
                _channel = (call TFAR_fnc_ActiveSwRadio) call TFAR_fnc_getSwChannel;
                _channel = _channel + 1;
                _curfreqsr = [(call TFAR_fnc_activeSwRadio),_channel] call TFAR_fnc_GetChannelFrequency;
                _curfreqsr = parseNumber _curfreqsr;
                if(!isNil "_curfreqsr") then {
                   if( _curfreqsr > 30 && _curfreqsr < 35 ) then {
                    hintSilent "30.1 - 34.9 are blocked frequencies.";
                    [(call TFAR_fnc_activeLrRadio), _channel, "40"] call TFAR_fnc_SetChannelFrequency;
                };
                };
            };
        } else {
            hintSilent "Your radios are interfering with each other, drop one to fix it.";
            {
                if(_forEachIndex != 0) then {
                    player unassignItem (_radios select (_forEachIndex - 1));
                    player assignItem (_radios select (_forEachIndex));
                };
                _wtfno = call TFAR_fnc_haveSWRadio;
                if(_Wtfno) then {
                    _channel = (call TFAR_fnc_ActiveSwRadio) call TFAR_fnc_getSwChannel;
                    _channel = _channel + 1;
                    _curfreqsr = [(call TFAR_fnc_activeSwRadio), _channel] call TFAR_fnc_GetChannelFrequency;
                    if(!isNil "_curfreqsr") then {
                        [(call TFAR_fnc_activeSwRadio), _channel, str(round(random 480)+30)] call TFAR_fnc_SetChannelFrequency;
                    };
                };
                if((count _radios - 1) isEqualTo _forEachIndex) then {
                    player unassignItem (_radios select (_forEachIndex));
                    player assignItem (_radios select 0);
                };
            } forEach _radios;
        };
    };
};
	sleep 2;
			};

};`

It worked before the update so maybe you changed something we need to change?

**Comment by dedmen** [comment]
TFAR 1.0 is a major update so ofcause a bunch of stuff has changed.
Gosh that code is crusty.
Why are you settings the LR Radios frequency inside the SW Radio code? That would explain one of the script errors. trying to set a LR frequency to a Player that doesn't have an LR Radio

**Comment by cobraALRP** [comment]
This is a really old script, not made by us. I will clean it up soon.
We are using default tfar class radios
