### ISSUE TITLE
TS crash upon join (Dev)

### ISSUE THREAD

**Issue by cobraALRP** [michail-nikolaev/task-force-arma-3-radio#1227]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `Latest` (stable / dev + commit hash)
**Task Force Radio Version:** `2.22 Dev` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
`- TS crashes when loading into the TS server
`
**Steps to reproduce:**
```
- Load teamspeak with the addon loaded
- To fix simply disable the plugin before joining then reenable it when in
```

**Where did the issue occur?**
`- TS`

**Comment by dedmen** [comment]
Can you please upload the crash report? Also what is TFAR version `2.22 dev`?

**Comment by cobraALRP** [comment]
Where do I find them, there is none in the usual place?
And 1.-1.0.222.zip dev sorry.

**Comment by dedmen** [comment]
Teamspeak should show you the path to where the crash dumps are located when it crashes. They are usually stored in the Documents folder. Or maybe in Appdata\Roaming\Teamspeak

**Comment by cobraALRP** [comment]
It appears to have stopped after the recent TS update, will update if this changes

**Comment by cobraALRP** [comment]
Nevermind, still happening. Here is the dumps from the past few days (Found them all now)
https://drive.google.com/file/d/0B9NEiDRycakXd1pxWXB2LWJId1U/view?usp=sharing

**Comment by dedmen** [comment]
Literally none of these crashes seem to be caused by TFAR. It doesn't crash if you don't have TFAR loaded?
Are you running Windows 10?
These crashes look a lot like recent Arma x64 Crashes that happened to people on Windows 10. And it seems to be crashing inside Windows code. So I'd say Windows 10 is causing these crashes. You should maybe forward these crashdumps to Teamspeak. Maybe they know more.

**Comment by cobraALRP** [comment]
Yeah, works fine without TFAR enabled.
I am using Windows 10 (Latest update)

**Comment by dedmen** [comment]
Could very well be that these crashdumps where not the correct ones to the crashes. But there are several dozen people playing with the same TFAR version on latest Windows 10 who don't have problems.
Could also be caused by AV if it's not windows.

**Comment by cobraALRP** [comment]
Alot of people in my community are experiencing issues, it is certainly not something that happens every time you connect. I will update if the situation evolves, as of right now it is not a major issue anyway.

**Comment by dedmen** [comment]
Would also be nice to see crash dumps of the other people in your community. Maybe their crashdumps have more useful data.
