### ISSUE TITLE
Pipe closed by ts

### ISSUE THREAD

**Issue by Neon2** [michail-nikolaev/task-force-arma-3-radio#1228]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**Task Force Radio Version:** `0.9.12 stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio
-'@servercustommod

**Description:**
- pipe closed by ts

**Steps to reproduce:**
- join the server and be in TaskForceRadio channel.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Client RPT log = https://codeshare.io/5Mky6Q

**Comment by dedmen** [comment]
Well.. I'd guess that message means that Teamspeak closed the pipe for some reason. Teamspeak client log is needed in that case. But I suppose it doesn't show anything useful.

**Comment by Neon2** [comment]
@dedmen 
[CLIENT LOG TS.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/869492/CLIENT.LOG.TS.txt)

**Comment by dedmen** [comment]
No error in there :/ And old 0.9.12 error messages also aren't that helpful. Try running Teamspeak or Arma as Admin and see if that solves anything. Since when do you have that issue? Recent TFAR or Windows update or just getting started with TFAR?

**Comment by Neon2** [comment]
@dedmen 
Rebuilding the Server, I think it was that the server was running on outdated files. But if I keep getting it I will reopen this!

**Comment by dedmen** [comment]
Pipe closed is completly unrelated to server files :o But.. If that fixed it... You probably did something else. Maybe even a computer restart fixed it.
