### ISSUE TITLE
TFAR Refusing to connect to Arma 3

### ISSUE THREAD

**Issue by Oogle** [michail-nikolaev/task-force-arma-3-radio#1234]
**Arma 3 Version:** `1.68.141112` (stable)
**CBA Version:** `3.2.1.170227` (stable)
**Task Force Radio Version:** `0.9.12` (stable)
**Mods:**
https://i.gyazo.com/1cee98f6d61ff6e16415b39a65564486.png

**Description:**
https://i.gyazo.com/1d4641dcbd8de73dcd11d45afdce0568.png
http://i.imgur.com/km4hjWM.gifv
- The TFAR plugin refuses connect to my arma 3. When  I launch the game the TS3 plugin just says "Connect N Play N". In game a permanent black box sits in the right corner. I have attempted to fix the problem in the single player editor, multiplayer editor, and a dedicated server. When I play on a dedicated server I hear everyone as though my plugin never loaded.
I have provided some images showing exactly what is happening.
I launch Arma 3 and TS 3 as admin. I have also loaded the 3.1 compatibility files. My TS version is 3.1.0.1.

**Steps to reproduce:**
- Launch Arma 3 and TS 3 as admin. Load into a server. Attempt to talk.

**Where did the issue occur?**
- Dedicated and Self-Hosted Multiplayer

**RPT log file:**
- https://pastebin.com/BYLNak0D

**Comment by dedmen** [comment]
The RPT doesn't show you connecting to a Server or Starting a mission.
Sounds like your Arma is not loading the `task_force_radio_pipe.dll`

**Comment by coachwn** [comment]
We have the same issue happening to myself and several others in our community and its only started within the last 24 hours. We all have the 64bit task_force_radio_pipe.dll file loaded and are all running the 64bit version of Arma.

**Comment by SSederberg** [comment]
Within the last 24 hours? A TS update has occurred, in the same time frame. Have you tried reverting back to a [previous version of TS](http://ftp.4players.de/pub/hosted/ts3/releases/)?

**Comment by john681611** [comment]
Potential dll battle eye block again?

**Comment by coachwn** [comment]
Sorry should have said this started prior to the latest update. The thing that fixed it for me was going to the pre-release TFAR version 245 linked in the releases section. I even went so far as to uninstall Teamspeak and see what happened with a fresh version of that and CBA.

**Comment by dedmen** [comment]
Last Teamspeak update didn't change anything concerning Plugins.
`We have the same issue happening`
Are you sure it's the same?
Battleye block is a dark box without text in the bottom right.
If it has any text it is something different.
The 1.0 pre-release is better than 0.9.x anyway ^^. So if that works for you that's very good.
