### ISSUE TITLE
Volume Indicator Transparency Slider value shown switching between 0 and 1

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1236]
**Arma 3 Version:** `1.68_x64`
**CBA Version:** `3.2.1.170227`
**Task Force Radio Version:** ` 1.-1.0.235`

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- The Volume Indicator Transparency Slider value that is being shown in the cba menu switches between 0 and 1, while the actual set value depends on the position of the slider. Minor cosmetic problem, but still...

**Steps to reproduce:**
- Move the slider up and down. >0.5 it switches from 0 to 1 and <0.5 it switches to 0. If you manually type in a value, it reverts to either 1 or 0. In either case the transparency is set to the desired value and the shown numerical value has no effect.

**Comment by dedmen** [comment]
Fixed in 9d8090c70dbaf764d703c40ac35b45d4000e1daf
Will be in 1.0 whenever the Receiving HUD is done. Shouldn't be tooo long.
