### ISSUE TITLE
Unable to get tf_no_auto_long_range_radio to function (64 bit)

### ISSUE THREAD

**Issue by cruss60** [michail-nikolaev/task-force-arma-3-radio#1237]
tf_no_auto_long_range_radio = true; doesn't work in the init.sqf anymore. Is there a fix?

**Comment by john681611** [comment]
> tf_no_auto_long_range_radio doesn't exit anymore since build 139
Just hunting down the code to do it

**Comment by john681611** [comment]
Try this #1160

**Comment by dedmen** [comment]
You know.. There is a reason why that issue template wants you to write down which versions of Mods you are using. I'd just assume you are running latest stable. Which means. No you are lying. It still works fine never changed anything on it.
