### ISSUE TITLE
Suggestion for tfar_ai_hearing

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1239]
Taking a closer look at tfar_ai_hearing, I would suggest adding the following code to the evh, so AI won't just 'notice' the players presence, but act on it as well. Of course it should only work if the ai is enemy and not already reacting. The modified code is enclosed in `//ADDED CODE:` and `//END OF ADDED CODE.`

https://pastebin.com/P7y3J8WS

**Comment by dedmen** [comment]
I don't want to manipulate how the AI works. If the AI knows there is someone where but decides not to check then that's how it is. Letting AI run blindly around a corner and get shot down is not that good as when it camps around a corner and waits for the Player

**Comment by dedmen** [comment]
I don't want to manipulate how the AI works. If the AI knows there is someone where but decides not to check then that's how it is. Letting AI run blindly around a corner and get shot down is not that good as when it camps around a corner and waits for the Player.
Plus! AI doesn't know if there is a enemy or a friendly that just spoke. Why would he run towards an Enemy but not towards a Friendly if he doesn't even know what Faction that unit is he heard.

**Comment by Pergor** [comment]
Got it.

But I'm so gonna send my AI around now! :D

**Comment by dedmen** [comment]
Feel free to. That's what Eventhandlers are made for ^^
