### ISSUE TITLE
Suggestion : Upload on Steam Workshop

### ISSUE THREAD

**Issue by S0klen** [michail-nikolaev/task-force-arma-3-radio#1240]
I just want to know if you think upload Pre-Release version on Steam Workshop or if you wait a New Release for production intent to do that.

**Comment by dedmen** [comment]
It... Already is on Steam workshop. http://steamcommunity.com/sharedfiles/filedetails/?id=894678801

**Comment by S0klen** [comment]
Thanks for your link ! Can you upload the latest version .235 ?

**Comment by dedmen** [comment]
It will be updated whenever I have time, I don't right now. Requests for updates on that workshop item are useless.
