### ISSUE TITLE
bug issue : AI zeus controlled / position of the player

### ISSUE THREAD

**Issue by voodoo23** [michail-nikolaev/task-force-arma-3-radio#1242]
**Arma 3 Version:** `1.68
**CBA Version:** `3.2.1
**Task Force Radio Version:** 1.0.235

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
Two close players using zeus are controlling an IA. After they release the control of the IA, they cannot speak to each others or use their radio unless they disable the zeus mode. It seems the game consider they are still located at the IA location and they can hear any players around the past controlled IA.

**Steps to reproduce:**
Place 2 players with a zeus module synchronized. Take control of an IA and try to speak to each other after leaving the control of the IA.

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
Duplicate #1211 
https://github.com/CBATeam/CBA_A3/issues/615
