### ISSUE TITLE
Keybind doesnt work anymore, no rogerbeep in mission

### ISSUE THREAD

**Issue by TTTRedd** [michail-nikolaev/task-force-arma-3-radio#1243]
**Arma 3 Version:** `1.68 stable` (stable / rc / dev)
**CBA Version:** `3.2.1 stable` (stable / dev + commit hash)
**Task Force Radio Version:** `1.0.235` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@Ace3 3.9.0`

**Description:**
- Keybind "Alt+Insert" to transmit additional SR and Keybind "Alt+J" to transmit additional LR doesnt work anymore. No rogerbeep on SR and LR, can hear it once when switched on missionstart in TFAR channel but not in the mission.

**Steps to reproduce:**
- Start game with mods above

**Where did the issue occur?**
- Everywhere

**Comment by dedmen** [comment]
Still issue?

**Comment by TTTRedd** [comment]
Rogerbeep ist immer noch keiner da, Tastenbelegung kann ich nicht sagen,
hab mittlerweile an eine andere gewöhnt.

MfG Redd

Am 03.11.2017 12:08 schrieb "Dedmen Miller" <notifications@github.com>:

Still issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1243#issuecomment-341675288>,
or mute the thread

**Comment by dedmen** [comment]
Can you send me the output of `/tfar diag` in Teamspeak chat?
most importantly the `pluginPath` under `TFAR` category.

**Comment by TTTRedd** [comment]
Of course, next time we play.

Am 03.11.2017 14:23 schrieb "Dedmen Miller" <notifications@github.com>:

**Comment by dedmen** [comment]
No need to play for that. Can also be done without playing. Just needs TFAR plugin enabled.

**Comment by TTTRedd** [comment]
Installing a fresh Windows 10 solved the roger beep problem
