### ISSUE TITLE
Pipe was closed by TS, Error (in game)

### ISSUE THREAD

**Issue by GuillaumeErhard** [michail-nikolaev/task-force-arma-3-radio#1246]
**Arma 3 Version:** `1.68.141205 ` (stable)
**CBA Version:** `3.2.1` (stable)
**Task Force Radio Version:** `0.9.12` (stable)
**TeamSpeak:**` 3.1.3` and `3.1.4` 
**Mods:**
- `@3cb`
- `@ace`
- `@CBA_A3`
- `@CK_Core`
- `@CK_Pack`
-  `@CUP_Terrains_Core`
- `@CUP_Terrains_CWA`
- `@CUP_Terrains_Maps`
- `@FFAA`
- `@JSRS`
- `@NIarms`
- `@RHSAFRF`
- `@RHSGREF`
- `@RHSSAF`
- `@RHSUSAF`
- `@task_force_radio`

**Description:**
- When connecting to a game I immedialty get the error message in game : " pipe was closed by TS".  and nothing to be seen on the teamspeak program. Even tough I enabled the plugin on TS, reloaded, and started the program as admin, no indication are to be seen, when I am clicking on someone to see what version of the plugin they are using.

**Steps to reproduce:**
- 64 bits install following the thorougly and at multiple times the instructions on the sites, and after re-installing teamspeak several time to be sure it was not a corrupted download. 

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Log thrown by TS I found 
[Client Log.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/924249/Client.Log.txt)

**Comment by SSederberg** [comment]
Have you tried disabling all of your mods except for TFAR to see if they might be causing conflicts? I'm currently running TS 3.1.1.1 and it works just fine. I suspect TFAR isn't updated for 3.1.4.

**Comment by GuillaumeErhard** [comment]
I used those mods for a private sever, and they were necessary for our games. I downgraded the version of Teamspeak to 3.1.1.1 though and it seems to work.

Thanks for your inputs @SSederberg :)

**Comment by GuillaumeErhard** [comment]
I used those mods for a private sever, and they were necessary for our games. I downgraded the version of Teamspeak to 3.1.1.1 though and it seems to work.

Thanks for your inputs @SSederberg :)
