### ISSUE TITLE
Teamspeak 3 package loss

### ISSUE THREAD

**Issue by JuanAdamuz** [michail-nikolaev/task-force-arma-3-radio#1254]
**Arma 3 Version:** LAST
**CBA Version:** LAST
**Task Force Radio Version:** LAST

**Mods:**
- Custom Mods
- `@task_force_radio

**Description:**
- When our players play in the game, the teamspeak 3 starts to get laggy due to package loss only when taskforce is running. Without taskforce teamspeak is fine

**Comment by dedmen** [comment]
TFAR doesn't cause package loss.
also 
```
Arma 3 Version: LAST
CBA Version: LAST
Task Force Radio Version: LAST
```
Completly invalid

```
Mods:

    Custom Mods
    `@task_force_radio`
```
also invalid. If you want to do a bugreport do it right or leave it.
