### ISSUE TITLE
Feature Request - Zeus-TFR proximity chat

### ISSUE THREAD

**Issue by CabooseStiffler** [michail-nikolaev/task-force-arma-3-radio#1255]
Hello,

Something that I have been always looking for is the ability to be able to fly over to a group of players as Zeus and be able to hear what they're saying.
I am aware of having radios to communicate to troops but that isn't what I'm after, I just want to hear the players locally, and use radios to talk to them separately.

**Comment by dedmen** [comment]
Already available. AFAIK always worked with Zeus Logic. With Zeus Unit you can set a checkbox on the specific unit in 3DEN. When that unit enters Zeus Interface his ears will be in his Camera.

**Comment by chris579** [comment]
Only for comprehension, will you be able to hear both, players around your real unit and in Zeus or only the units you're flying over? If you can only hear players you're flying over what about an option to toggle this? Imagine a scenario where you're a Zeus operator and still in the field and you want to hear both.

**Comment by dedmen** [comment]
@chris579 no not both. Only one. I can add a hotkey to toggle that.
Problem is that a player can only be at one place at a time. Which is logical.
Can you please create a new issue about adding a hotkey to toggle it?

**Comment by chris579** [comment]
Done https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1270
