### ISSUE TITLE
Radio Doesn't Reset After Returning To Curator Cam From RC

### ISSUE THREAD

**Issue by Snak3Doc** [michail-nikolaev/task-force-arma-3-radio#1262]
**arma 3 1.70 Jet DLC 
**CBA Version:** 3.3.1.170504
**ACE3 Version:** 3.9.2
**task_force_radio **1.-1.0.243**

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- When releasing control of an RC unit and returning to curator camera the curator still has the radio and settings of the unit they were controlling until they reload the curator interface.

**Comment by dedmen** [comment]
Which CBA version are you really running?

**Comment by Snak3Doc** [comment]
Ahh didn't realise they had released a new version, and also didn't know the version was in the bisign, I'll see how it goes after I update later today.

**Comment by dedmen** [comment]
Status?

**Comment by BmanDesignsCanada** [comment]
I couldn't replicate with 244, trying to is how I discovered #1265

**Comment by Snak3Doc** [comment]
Latest CBA update fixed it thanks
