### ISSUE TITLE
Get list of LR radios

### ISSUE THREAD

**Issue by BmanDesignsCanada** [michail-nikolaev/task-force-arma-3-radio#1264]
Examples below from TFAR `1.-1.0.224`

Getting the list of long range radios returns completely different output compared to getting short range radios.

```
player call TFAR_fnc_radiosList
["TFAR_anprc152_1"]
```

```
player call TFAR_fnc_lrRadiosList
[[1c222665600# 1675083: clf_nicecomm2.p3d,"radio_settings"]]
```

Is there a better way to get a list of the LR radios? SW info can be taken from CfgWeapons. I need the similar info for LR radios.

**Comment by dedmen** [comment]
What?
A LR Radio is an Array. TFAR_fnc_lrRadiosList returns all LRRadios.
What SW Info do you mean?
Why do you create issues for stuff that are not Issues? Issues are for reporting Problems not for asking questions.
If you wanna ask Questions join Discord. https://discord.gg/8emCVsz

**Comment by BmanDesignsCanada** [comment]
I'd recommend putting that discord link in the readme, I did try to find one before opening this issue,

**Comment by dedmen** [comment]
If you searched for `Discord` or `Slack` using the Github search box at the top you would've found it.
