### ISSUE TITLE
Selecting your radio in curator remote control

### ISSUE THREAD

**Issue by BmanDesignsCanada** [michail-nikolaev/task-force-arma-3-radio#1265]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1.170504` (stable)
**Task Force Radio Version:** `1.-1.0.244`

**Mods:**
- `@cba_a3`
- `@ace`
- `@task_force_radio`

**Description:**
Using \<ctrl\> + P while remotely controlling a unit brings up a window to select between your actual radio or the remotely controlled unit's radio. Selecting your actual unit's radio and setting it as active results in the bottom right window saying `Channel: scalar NaN` and `Frequency: any`. The radio dialog is never shown and no radio is used when pushing \<Caps Lock\>. Switching back to the remotely controlled unit's radio works fine. `Inventory item with given name: [TFAR_anprc152_1] not found` is the relevant output in the RPT

**Steps to reproduce:**
- Remote control unit in Zeus / Curator interface
- \<ctrl\> + P
- Select topmost radio / your actual radio

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer

**Comment by BmanDesignsCanada** [comment]
`fnc_setActiveSwRadio.sqf` is assuming the radio being passed is owned by TFAR_currentUnit

**Comment by dedmen** [comment]
Good catch.
245 changes it so that you can't use the Curators SR Radio to transmit. You can still receive on it and you can also receive/transmit on the Curators LR Radio.

**Comment by BmanDesignsCanada** [comment]
Why not allow the user to use the Currator's SR?

https://github.com/Synixe/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_setActiveSwRadio.sqf

https://github.com/Synixe/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_activeSwRadio.sqf

This was testing in self-hosted multiplayer.
Allows the use of the curator's radio.

**Comment by dedmen** [comment]
Feel free to make a PR. But won't merge right now because I'm not sure if it could cause any unforseen consequences.

**Comment by BmanDesignsCanada** [comment]
Okay, I'll test with my unit sometime this week and make sure everything runs smoothly.
