### ISSUE TITLE
Anyone used TFR on lythium map and experienced SR radio quality bugs?

### ISSUE THREAD

**Issue by Snak3Doc** [michail-nikolaev/task-force-arma-3-radio#1267]
Has anyone else experienced strange tfr bugs on the lythium map, namely short range comes sounding like their being blocked or your 6km away when your actually standing right next to each other, I was expecting LR coms quantity and range to be effected by all the massive mountains, but that shouldn't effect SR coms of someone standing next to you.

From what I can tell it has to do with were you are on the map and possibly the time of day, I know tfr works of light and I think lythium has custom lighting and or skybox so maybe the custom lighting is overpowering the tfr light/signals. Anyone else experienced this?

**Comment by dedmen** [comment]
`I know tfr works of light` Where did you get that?

**Comment by Snak3Doc** [comment]
Not sure just something I've heard heaps of people say over the years, that it worked by using use light and reflections rather than create radio signals from scratch, I'll edit it out but my point still stands about lythium standing in one valley person next to me sounds 10km away and then the next valley over it's fine again

**Comment by dedmen** [comment]
Maybe related to Relay Antenna bug which will be fixed in 276?

**Comment by Snak3Doc** [comment]
Can confirm this stopped when we found and removed the relay antennas from the map, someone didn't realise they weren't vanilla and added a bunch.

**Comment by dedmen** [comment]
TFAR relay antennas have TFAR in the name :D But they are also fixed next release and on current alpha release.
