### ISSUE TITLE
Unfriendly setMyMetaData

### ISSUE THREAD

**Issue by BmanDesignsCanada** [michail-nikolaev/task-force-arma-3-radio#1268]
**Task Force Radio Version:** `245` (dev)

The function `Teamspeak::setMyMetaData` is not friendly to other developers wanting to use a similar system.

```
std::string to_set;
std::string sharedMsg = clientInfo;
if (sharedMsg.find(START_DATA) == std::string::npos || sharedMsg.find(END_DATA) == std::string::npos) {
  to_set = to_set + START_DATA + metaData + END_DATA;
}
```

Since to_set is an empty string, everything is removed and the metadata is only the `<TFAR>` tags instead of preserving other metadata.

```
std::string to_set = clientInfo;
std::string sharedMsg = to_set;
if (sharedMsg.find(START_DATA) == std::string::npos || sharedMsg.find(END_DATA) == std::string::npos) {
  to_set = to_set + START_DATA + metaData + END_DATA;
}
```

This change would not remove the data of other TeamSpeak plugins using the metadata.

**Comment by dedmen** [comment]
You should also quote the rest of the code.
It only set's metadata to empty when it doesn't already contain <TFAR> tags. If it does then it only set's the text inbetween. Meaning if other Plugins also cooperate in that they don't just delete the <TFAR> tags then everything will be fine.

**Comment by BmanDesignsCanada** [comment]
Can this issue be closed?

**Comment by dedmen** [comment]
Oops ^^ Yes.
