### ISSUE TITLE
Entering arsenal on a player via Zeus resets their long range channels

### ISSUE THREAD

**Issue by ShizCalev** [michail-nikolaev/task-force-arma-3-radio#1271]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1.170504` (stable)
**Task Force Radio Version:** `1.-1.0.245` 

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
Entering arsenal on a player via Zeus resets their long range channels.

**Steps to reproduce:**
Have a player set their long range
Open Zeus
Open that player's arsenal
Radio channels on the player's long range has reset.

**Where did the issue occur?**
Dedicated

**RPT log file:**

**Comment by dedmen** [comment]
What? That was fixed long time ago. And it worked back when I added it.

**Comment by ShizCalev** [comment]
I recall that entering arsenal resetting -your- long range channels was fixed, yes. 

However, the issue seems to now be occurring when you open up arsenal on a different player via Zeus, resetting the other player's radio.

**Comment by dedmen** [comment]
Ouhhhh.. Yeah. That's true. Since when is that even possible? I thought Zeus prevents editing other Players.
There isn't much we can do about that. That's not a TFAR bug that's a Arsenal bug. We were able to add a local workaround for that. But that won't work for remote Players.
