### ISSUE TITLE
Battleye is blocking TFR 64 bit

### ISSUE THREAD

**Issue by C0kkie** [michail-nikolaev/task-force-arma-3-radio#1274]
**Arma 3 Version:** `newest` (stable / rc / dev)
**Task Force Radio Version:** `newes (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- Since 3h battleeye is blocking the 64bit version of taskforceradio

**Comment by JamesTaki** [comment]
Having to same problem [![https://gyazo.com/ba16b8704a6117ccda404e5aa3fb4a5b](https://gyazo.com/ba16b8704a6117ccda404e5aa3fb4a5b/raw)](https://gyazo.com/ba16b8704a6117ccda404e5aa3fb4a5b)

**Comment by jamese98** [comment]
Same issue here
![1](https://user-images.githubusercontent.com/23371260/27004665-ef24306e-4dda-11e7-997c-86ce416db4ae.JPG)




![2](https://user-images.githubusercontent.com/23371260/27004667-f24c0a46-4dda-11e7-8575-2387891804ea.JPG)






![3](https://user-images.githubusercontent.com/23371260/27004669-f683b9ba-4dda-11e7-9592-ad1ea43a2394.JPG)

**Comment by dedmen** [comment]
I cannot do anything about this. It's a Battleye issue. Which happens quite frequently.
