### ISSUE TITLE
Show transmitting hint not working

### ISSUE THREAD

**Issue by NiallMcsliveCityLifeRPG** [michail-nikolaev/task-force-arma-3-radio#1276]
**Arma 3 Version:** `1.70.141838` (stable )
**CBA Version:** `3.3.1` (stable )
**Task Force Radio Version:** `1. -1.0.240` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio
-CL mods which shouldnt affect the issue

**Description:**
- So on this version of TFR you are supposed to be able to turn on/off the volume hint which you get whenever you change volume of your voice.However, even with the correct boxes checked ( https://gyazo.com/047896f9fe5d03a9945f69c10e2bc603 ) No hint appears at all at the bottom right of my screen.

**Steps to reproduce:**
Have all the boxes checked such as show old voice volume hint.
Change your voice volume
You will see you are unable to see what volume you are at

**Where did the issue occur?**
- Dedicated server
**RPT log file:**
-https://pastebin.com/9bnt7598

**Comment by dedmen** [comment]
You have the new Indicator and the old Hint enabled at the same time.
You may have to disable the new Indicator first.

**Comment by NiallMcsliveCityLifeRPG** [comment]
I've tried using two of them individually and it still wont appear.

**Comment by dedmen** [comment]
Wait.. Just noticed it. The title is Transmitting hint but in description you are talking about volume Hint. What do you actually mean here?

**Comment by NiallMcsliveCityLifeRPG** [comment]
at the bottom right whenever u change your voice to normal whisper or yelling it doesnt appear

Sent from my Sony Xperia™ smartphone

---- Dedmen Miller wrote ----

**Comment by dedmen** [comment]
That is because you set the transperency to 100%. Which makes it invisible.

**Comment by NiallMcsliveCityLifeRPG** [comment]
Ive changed the visibility to 0 (fully visible) and have use old volume hint on and nothing else in regards to the pop up and it still doesnt appear.

**Comment by NiallMcsliveCityLifeRPG** [comment]
https://gyazo.com/3e35391728ff719bc079b65e872807f8 This is a screenie of my settings.

**Comment by dedmen** [comment]
Might be that it's bugged in 240.
But again. Why don't you use the New indicator?

**Comment by NiallMcsliveCityLifeRPG** [comment]
Ive attempted to use it and it doesnt work,
Personally I dont like the new one.

**Comment by NiallMcsliveCityLifeRPG** [comment]
Its also bugged in 1.-1.0.245

**Comment by dedmen** [comment]
I just tested it. Opened a local MP server. Reset all my settings to default and enabled "Show old Voice Volume Hint" And it worked right away.

**Comment by dedmen** [comment]
My settings:
![](https://image.prntscr.com/image/2TO-VD4wQHCiLBnM4rlk9Q.png)

**Comment by ArMaTeC** [comment]
this should be marked as fixed as it was the gui not being setup correctly that caused it and its now fixed in the newer versions

**Comment by dedmen** [comment]
@NiallMcsliveCityLifeRPG Please confirm fix?

**Comment by NiallMcsliveCityLifeRPG** [comment]
yes, this issue is fixed.
