### ISSUE TITLE
Transmitting beep heared from other server

### ISSUE THREAD

**Issue by burnacid** [michail-nikolaev/task-force-arma-3-radio#1279]
**Arma 3 Version:** `1.70.0.141.838` stable
**CBA Version:** `v3.3.1` stable
**Task Force Radio Version:** 1.0-dev.245 (release file)

**Mods:**
- @CBA_A3
- @task_force_radio
- @3cb_baf
- @ace
- @acex
- @Alive
- @tfw_radios

**Description:**
- Within our unit we run on 2 servers. We recently updated to the dev build.
Today we noticed while on 2 different servers 2 people on the same frequency you hear the radio beep sound when someone starts transmitting on the other server.

**Steps to reproduce:**
connect 2 people to 2 different servers
set frequency to the same (we used 80.2)
hold Ctrl+Caps Lock

The other person on the other server will hear the start and ending transmitting beep. While in the same TS channel

**Where did the issue occur?**
- Dedicated

**Comment by burnacid** [comment]
Because we always used to do so. Plus TFAR keeps switching you anyway

**Comment by dedmen** [comment]
All players in the same game world should be in the same channel. 
Having different servers in the same channel can even create performance problems and also put's quite some load on your Teamspeak server. Because they all communicate with eachother even if they shouldn't.

**Comment by blindbat2006** [comment]
Would creating 2 channels in teamspeak say TaskForceRadio1 and TaskForceRadio2 and the arma servers then point to there own tfar channel. Would that be solution to this then?

**Comment by dedmen** [comment]
Yes.

**Comment by dedmen** [comment]
TFAR knows everyone that is in your channel. So even if I would check who is in the channel that wouldn't fix that. 
Just not possible with TFAR's architecture.
