### ISSUE TITLE
Remote controlled unit can't hear other players.

### ISSUE THREAD

**Issue by iReckonItzMike** [michail-nikolaev/task-force-arma-3-radio#1280]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable)
**Task Force Radio Version:** `0.9.12` (stable)

**Mods:**
- `@CBA_A3`
- `@task_force_radio
- `@CUP Terrains (Maps/Core/CWA)`
- `@CUP (Weapons/Vehicles/Units)
- Various others that wouldn't interfere.
**Description:**
- When a Zeus controls a unit, All other players in it's vicinity can hear the Zeus talking, But the Zeus (Remote controlling) Can't hear anything they say back.

**Steps to reproduce:**
- Zeus Slot > Remote Control Unit
- Talk to Players > Can't hear them responding.

**Where did the issue occur?**
- Dedicated / Rented

**Comment by dedmen** [comment]
Duplicate #1153. Already fixed in 1.0
