### ISSUE TITLE
CallExtension 'task_force_radio_pipe' could not be found

### ISSUE THREAD

**Issue by Fubister** [michail-nikolaev/task-force-arma-3-radio#1281]
**Arma 3 Version:** `1.72.142164` (stable)
**CBA Version:** `3.3.1.170504` (stable)
**Task Force Radio Version:** `0.9.12` (stable)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
I see a massive spam in my server .rpt saying CallExtension 'task_force_radio_pipe' could not be found. The addon works perfectly fine, but the reason why I'm worried is I found out CallExtension problem may cause performance and fps drops for players. I should add my server is hosted on a Linux machine.

**Steps to reproduce:**
-

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
Server doesn't need extension.

**Comment by Fubister** [comment]
I haven't done any changes to the addons, I placed them both on the server side, how can I get rid of that error?

**Comment by dedmen** [comment]
Can you post your RPT please?

**Comment by Fubister** [comment]
https://pastebin.com/NvZfCNrS

**Comment by dedmen** [comment]
You lied in what Mods you run.
I'd need the scripts of all your Mods to see what is calling TFAR and causing that.

**Comment by Fubister** [comment]
I'm running a car and clothing pack and I'm pretty sure they have nothing to do with tfar but here is an interesting fact, I ran exact copy of my mission and mod but on a Windows machine and this problem does not exist, in fact in windows .rpt i get only 1 message "18:18:10 CallExtension loaded: task_force_radio_pipe (D:\A3Serwer-win\@wonderlife\task_force_radio_pipe_x64.dll) [@¦îaß]" and that's it.

**Comment by dedmen** [comment]
That is because the extension can load on Windows. But that doesn't change the fact that it should never run Serverside.

**Comment by Fubister** [comment]
You were right this is the script in server init.sqf it making player screen black and displaying some info, how can i modify it to stop callextension spam?

`if (isNil "TFAR_fnc_isTeamSpeakPluginEnabled") exitwith {
	
	999999 cutText ["Task Force Radio is not running on your computer. Please re-sync and retry","BLACK FADED"];
	999999 cutFadeOut 99999999;
	if (player getvariable "taskfr") then {
		player setvariable ["taskfr",false,true];
	};
};



_TFenabled = [] call TFAR_fnc_isTeamSpeakPluginEnabled;

if (!(_TFenabled)) then {

	while {!([] call TFAR_fnc_isTeamSpeakPluginEnabled)} do {
		
		titleText ["Please enable Task Force Radio in your TS3 Plugins! || TS3 -> Settings -> Plugins", "BLACK"];
		sleep 2;
		if (player getvariable "taskfr") then {
		player setvariable ["taskfr",false,true];
		};
	};
};

Dvid_TFEnabled = true;
Dvid_onTsServer = "Your TS Server Name There" == (call TFAR_fnc_getTeamSpeakServerName); ///////////////////////Edit This line (the channel at the top of your TS (where you right click and "Edit Virtual Server"), yes, get the name of that goes here)
Dvid_onChannel = "TaskForceRadio" == (call TFAR_fnc_getTeamSpeakChannelName);
titleText ["Task Force Radio loaded succesfully","BLACK IN"];

[] spawn {

	while {true} do {
	
				_isadmin = false;
				if (!(isNil "life_adminlevel")) then {
					_adminlvl = life_adminlevel call BIS_fnc_parseNumber;
					
					if (_adminlvl > 0) then {
						_isadmin = true;
					};
				};
				
				
				
					_TFenabled = [] call TFAR_fnc_isTeamSpeakPluginEnabled;
					if ((!(_TFenabled)) && (Dvid_TFEnabled)) then {
					if (!(_isadmin)) then {
						titleText ["Please enable Task Force Radio in your TS3 Plugins! || TS3 -> Settings -> Plugins", "BLACK"];
						Dvid_TFEnabled = false;
					};
							if (player getvariable "taskfr") then {
								player setvariable ["taskfr",false,true];
							};
					};
					
					_onTsServer = "same as Dvid_onTsServer variable " == (call TFAR_fnc_getTeamSpeakServerName); //////////////////////Edit too pls, or dont but it wont work if you dont
					if (!(_onTsServer)) then {
					if (!(_isadmin)) then {
						titleText ["Please join the teamspeak server! Adress: here", "BLACK"];
						Dvid_onTsServer = false;
					};
						if (player getvariable "taskfr") then {
							player setvariable ["taskfr",false,true];
						};
					} else {
						if (!(Dvid_onTsServer)) then {
						if (!(_isadmin)) then {
							titleText ["TS server check completed. Welcome!","BLACK IN"];
							Dvid_onTsServer = true;
							};
						if (!(player getvariable "taskfr")) then {
							player setvariable ["taskfr",true,true];
						};
						};
					};
					
					_onChannel = "TaskForceRadio" == (call TFAR_fnc_getTeamSpeakChannelName);
					if (!(_onChannel)) then {
					if (!(_isadmin)) then {
						titleText ["Please reload the plugin to join the TFR channel || Settings -> Plugins -> Reload All", "BLACK"];
						Dvid_onChannel = false;
					};
						if (player getvariable "taskfr") then {
							player setvariable ["taskfr",false,true];
						};
					} else {
						if (!(Dvid_onChannel)) then {
							titleText ["TS channel check completed. Welcome!","BLACK IN"];
							Dvid_onChannel = true;
						if (!(player getvariable "taskfr")) then {
							player setvariable ["taskfr",true,true];
						};
						};
					};
					
					
					if ((_TFenabled) && (!(Dvid_TFEnabled))) then {
						titleText ["Plugin enabled, welcome back!","BLACK IN"];
						Dvid_TFEnabled = true;
						if (!(player getvariable "taskfr")) then {
							player setvariable ["taskfr",true,true];
						};
					};
				
				sleep 2;	
			};

};`
