### ISSUE TITLE
Disable radio-sounds

### ISSUE THREAD

**Issue by EduardSurovy** [michail-nikolaev/task-force-arma-3-radio#1282]
Is there any ways to globaly disable radio-sounds when using radio (on server dev side)? We are using TFAR for developing phone functionality on our own arma life platform. Is it possible to get compiled TS plugin without use of radio-sounds?

**Comment by dedmen** [comment]
You can either compile it yourself.
Or you just use the existing phone functionality. That doesn't have sounds.

**Comment by dedmen** [comment]
Use phone subtype for phones. It doesn't have sounds. Problem solved.
