### ISSUE TITLE
Simplex (TFAR 'Half Duplex') Generates RPT Errors

### ISSUE THREAD

**Issue by spartancain** [michail-nikolaev/task-force-arma-3-radio#1283]
**Arma 3 Version:** 1.72 stable
**CBA Version:** 3.4.0 stable
**Task Force Radio Version:** 1.-1.0.245 RC

**Mods:**
@CBA_A3
@15thACE (ACE 3.10.1)
@15thMEU
@15thAmmo
@15thOPFOR
@RHSAFRF (0.4.2.2)
@RHSUSAF (0.4.2.2)
@RHSGREF (0.4.2.2)
@RHSSAF (0.4.2.2)
@CUP_Terrains_Complete
@task_force_radio

**Description:**
When TFAR half-duplex mode (IRL simplex) is enabled and a user transmits while another user is already transmitting on the same frequency, the server dumps an error in the RPT:
```
2017/05/22,  4:27:21 NetServer: trying to send too large non-guaranteed message (1360 bytes long, max 1348 allowed)
2017/05/22,  4:27:21 Message not sent - error 0, message ID = ffffffff, to 89407432 ([REDACTED])
```
This error corresponds to a small drop in server performance. When >70 people are on a server engaged in pitched combat, the number of errors and the corresponding drop in performance increases dramatically, contributing to several server freezes we had before re-disabling TFAR half-duplex.

At the time this particular RPT was generated, we were either on 0.9.12 or 1.-1.0.235, but the error has been observed since. We are unsure if a fix is in the works for this, or if this is simply part of how TFAR half-duplex works. As it is, we would love to use half-duplex but are unable to due to the massive server issues encountered.

**Steps to reproduce:**
TX while other user on same frequency is also TXing.

**Where did the issue occur?**
- Dedicated MP during operations

**RPT log file:**
- https://drive.google.com/file/d/0B3ZXrdlp7k4ddGdmSXlOSjktMG8/view?usp=sharing

Respectfully submitted,

CPL H. TAYLOR | 15M1884
Infantryman | S-3 Range Instructor | S-4 Mission Team
3rd Battalion, 1st Marines
15th MEU Realism Unit

**Comment by dedmen** [comment]
That is a common error since 1.72 and not related to semi-duplex. Semi-duplex only acts inside of Teamspeak and between Teamspeak clients. It is in no way connected to Arma Networking.
I also have this spam alot on my Server. We just filter it out of our logs and didn't observe any side-effects like desyncs or lags.

**Comment by spartancain** [comment]
We've only had it with half-duplex enabled when users PTT while others are already keyed up. Heh. I mean I'll double check the logs to make sure, but that's what I've got so far.

Good to know though, that all half-duplex workings are TS-side. Guess I'll look for other potential causes... it's been bad enough that our only solution is to turn off half-duplex to prevent server performance from suffering mightily.

**Comment by spartancain** [comment]
Additional question:

With simplex (full duplex selected OFF), are there any known issues or more frequent instances of people saying "I can't hear X particular person at all"?

We've been using full duplex for a while and have had some of those issues reported (some possibly due to mod/TS mismatches, some definitely not). We just did a large scale test with a 57 person task force, and had a somewhat higher number of these "I can never hear Corporal Smith but he can hear me" errors. They are confirmed not to be the result of people trying to hear while transmitting. 

Any existing data on this?

**Comment by dedmen** [comment]
"I can't hear someone" is a bug that I'm still working on finding the cause. Not connected to using simplex.
Plugin reload fixes it.
If that happens I need diagnose logs so I can find out what the error might be.
`/tfar diag` and `/tfar pos` in Teamspeak
And the pluginCommands.log from AppData\Roaming\TS3Client

All taken at the time the issue is happening and before reloading the Teamspeak plugin.
