### ISSUE TITLE
When tilting head up/down 3D sounds rotates 180°

### ISSUE THREAD

**Issue by tenondra** [michail-nikolaev/task-force-arma-3-radio#1285]
**Arma 3 Version:** `1.71 stable`  
**CBA Version:** `3.4.0.170627 stable`
**Task Force Radio Version:** `1 - 1.0.245 dev `

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- When you pres alt, and move your head either up or down, after you tilted your head about few degrees you will hear thing from left on right and vice versa.

**Steps to reproduce:**
- Spawn
- Tilt your head either up or down

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
I thought I fixed that. Thanks will look into it. Are you sure you are running build 245?

**Comment by tenondra** [comment]
yes pretty sure.

**Comment by dedmen** [comment]
Could reproduce. Definetly caused by https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/547b3e108e330399d062e4aa8fc829f66023caf9#diff-24c2067afb9c97a308c5a6fbb4561731L59

**Comment by dedmen** [comment]
I think I fixed it. east-west and north-south are reversed to what our 3D sound engine expects.
Previously I just negated each value.
Now I switched over to leave these as original and instead swap the positons of receiver and emitter.
So now the sound get's emitted by the player and received by the other player that sends sound.
Seems confusing and wrong. But it works.

**Comment by dedmen** [comment]
Fix included in build 246. Please test and close this issue if fixed.

**Comment by tenondra** [comment]
thanks for fixing, just downloaded 246, will report back.

**Comment by tenondra** [comment]
yep can confirm that this issue has been fixed. Thanks for that again!
