### ISSUE TITLE
Teamspeak Crash when active TFR Plugin V1.-1.0.246

### ISSUE THREAD

**Issue by agorapolis** [michail-nikolaev/task-force-arma-3-radio#1287]
**Task Force Radio Version:** `1.-1.0.246` (/ dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio
- `Windows 7
- Teamspeak 3 version 3.1.5 (same problem on the 3.1.4.2)

**Description:**
- My teamspeak crash when i active TS3 plugin

**Steps to reproduce:**
- Install TS3 Plugin Task Force Radio
- Run Teamspeak (32 or 64 bits)
- Teamspeak 3 Client crash (TS3 stop working)

**Where did the issue occur?**
- Plugin teamspeak 3 client

**Comment by dedmen** [comment]
Where is the Teamspeak crash report?

**Comment by ShizCalev** [comment]
Do you also have an active ACRE plugin perhaps? Noticed updating re-enabled it, and having both on at the same time leads to crashing.

**Comment by dedmen** [comment]
Ah yeah. I remember something about that ACRE crashes Teamspeak when it see's TFAR. Even just clicking on a guy using TFAR used to crash ACRE a while back.
