### ISSUE TITLE
How to compile my own TFR teamspeak plugin

### ISSUE THREAD

**Issue by Whipgit** [michail-nikolaev/task-force-arma-3-radio#1288]
Hey guys,

I hope this question is not out of line. But I'm looking to fork off of your repo here and compile a TFR teamspeak plugin of my own which has some of the sounds replaced.

Would you guys be willing to point me in the right direction?
Are the files in the ts folder of the repo all I need?
Do the audio files need to be of a certain bitrate or other criteria I need to be aware of?
What do you use to compile it?

Thank you in advance!

**Comment by dedmen** [comment]
To replace the sounds you don't need to recompile the Plugin.
I just take the visual Studio project file from the src directory. Open it and press compile.
Bitrate wise 0.9.12 I don't know. But 1.0 see https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/ts/src/PlaybackHandler.cpp#L270
If you don't even know how to compile a C++ Project you shouldn't even try making a custom version of the Plugin.

**Comment by Whipgit** [comment]
> If you don't even know how to compile a C++ Project you shouldn't even try making a custom version of the Plugin.

Taking on more than you can handle is the only way to learn something new. 
I did it, thanks for the advice though! I appreciate all you do for TFR and I look forward to version 1.0 you're working on.
