### ISSUE TITLE
When having LR radios on speakers, all players in its radius can hear themselves

### ISSUE THREAD

**Issue by tenondra** [michail-nikolaev/task-force-arma-3-radio#1290]
**Arma 3 Version:** `1.71 stable` 
**CBA Version:** `3.4.0.170627`
**Task Force Radio Version:** `1 - 1.0.246`

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@ACE3`
- `@RHS mods`

**Description:**
- When there is a player with LR radio on his back and has set speakers, while being in radius of this LR radio you can hear your own voice while talking. Not like having an echo from another player's mic, but its like your own mic and headphones are connected together. + those additional mods should matter 

**Steps to reproduce:**
- Join dedicated server with TFAR on latest version
- Take LR radio on your back
- Set it on speakers
- Experience your very own voice while being mildly disturbed by your voice

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
I think I know the issue. Will fix in 247 shortly.

**Comment by tenondra** [comment]
looking forward to testing it! (:

**Comment by tenondra** [comment]
@dedmen have you found any fix yet? If not, maybe if you would point me where should I look maybe I could help you with that.

**Comment by dedmen** [comment]
It should be fixed in 247. Just didn't have time to press the "make new release" button yet.
Just done it. 247 should be out in a couple minutes and fix that.

**Comment by tenondra** [comment]
Cheers. btw didn't want to put you under pressure or anything like that.

**Comment by dedmen** [comment]
Nah. Pressure is good.

**Comment by tenondra** [comment]
Can confirm this has been fixed, but sadly, speakers don't work yet. But I prefer this over hearing myself.

**Comment by dedmen** [comment]
Yeah. LR speakers are known broken. I thought I fixed it but I must've overlooked something.
