### ISSUE TITLE
Where are the radio sounds located now?

### ISSUE THREAD

**Issue by kripto202** [michail-nikolaev/task-force-arma-3-radio#1297]
I'm wanting to create some new radio sounds for my group and I can't find where they are at now. Where does the plugin install the files?

**Comment by dedmen** [comment]
Same as before. Teamspeak Plugin directory radio-sounds folder.
This is a Issue tracker. For reporting Issues. Not asking questions.

**Comment by kripto202** [comment]
already looked there and they aren't there

**Comment by dedmen** [comment]
They are there. Give me full path of where you looked and which Teamspeak version are you running?

**Comment by kripto202** [comment]
ts 3.1.5 [stable]
C:\Program Files\TeamSpeak 3 Client\plugins
The folder is empty for me

**Comment by dedmen** [comment]
since TS 3.1 plugins are stored in Appdata.

**Comment by kripto202** [comment]
thanks, found them
