### ISSUE TITLE
Pipe was closed by TS

### ISSUE THREAD

**Issue by CharlesOnAir** [michail-nikolaev/task-force-arma-3-radio#1298]
**Arma 3 Version:** `1.72` (stable / rc / dev)
**CBA Version:** `Last Update 27/06/2017`
**Task Force Radio Version:** `0.9.12`

**Mods:**
- `@CBA_A3` // Don't activate in game
- `@task_force_radio

**Description:**
- When I play on an Arma 3 server, I have a message which displays below on the right of the screen: "  Pipe was closed by TS ". Then after I Arma 3, freeze during 30 seconds.

**Steps to reproduce:**
- Not much of a steps to reproduce

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
Probably your teamspeak freezed because of something.
What are you trying to say with `Don't activate in game` on CBA?

**Comment by CharlesOnAir** [comment]
The mode CBA is not activated in game.

**Comment by dedmen** [comment]
There is no "mode CBA" What do you mean by "not activated"

**Comment by CharlesOnAir** [comment]
Look -> http://image.noelshack.com/fichiers/2017/32/4/1502352210-capture.png

"CBA_A3" is not checked

**Comment by dedmen** [comment]
So you are telling me that you are loading TFAR and CBA but you are not loading CBA? Are you serious?

**Comment by CharlesOnAir** [comment]
I may activate CBA that not change nothing
