### ISSUE TITLE
Option to leave all intercom channels

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1299]
**Task Force Radio Version:** `1.-1.0.245` (stable / dev + commit hash)

Currently you can only switch between crew and cargo in the intercom.
An option to leave all intercom channels would be nice (for example if you have to use a radio while in a vehicle without wanting to hear all people babbling on and on).

**Comment by sbng-PAPA** [comment]
yeah. we need mic off and button too
addon option has low accessibility

**Comment by dedmen** [comment]
Intercom Slot `-1` is disabled. Just need to add ACE action for that.

**Comment by dedmen** [comment]
9ea6912d66b02941c58e7139571e187ae34ae76a Should've done this. Also added that you can't switch to the channel in which you already are anymore.

**Comment by dedmen** [comment]
248 was just pushed. Please test and close if fixed.

**Comment by Pergor** [comment]
Btw.: Tested and works fine. I'm not quite sure if players are on the right intercom channel from the get go though. I have the feeling as if a player who's entering a vehicle in a cargo seat is automatically on both the crew and the cargo intercom. You have to manually switch to one of the intercom channels to be on the right one - but then you can't switch back.
I'm not sure about that though - it might be that some players are just too *** to select the right channel... ;)

**Comment by dedmen** [comment]
Players are by default in cargo channel no matter which seat they are in. You can't be in two channels at the same time.

**Comment by dedmen** [comment]
There was a bug where you couldn't switch any channel in 248 ^^ But was fixed in next build.

**Comment by Pergor** [comment]
Ah, so everyone's on the same channel at first, but can switch afterwards. That explains that.
In that case: Everything works, can be closed.
