### ISSUE TITLE
ai hearing not working for respawned player

### ISSUE THREAD

**Issue by sbng-PAPA** [michail-nikolaev/task-force-arma-3-radio#1300]
**Arma 3 Version:** `1.74` (stable)
**CBA Version:** `3.4.0` (stable)
**Task Force Radio Version:** `1.-1.0.245`

**Mods:** cba, ace3, tfar

**Description:**
once died or respawned, ai_hearing stop working. just stop.
i'm not technician. sorry :(

**Comment by dedmen** [comment]
Thanks. I know what's wrong. Actually that bug breaks even more than just respawn

**Comment by dedmen** [comment]
Not fixed yet ;) I just know what the issue is.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1326
