### ISSUE TITLE
v.248 intercom option buttons not working

### ISSUE THREAD

**Issue by sbng-PAPA** [michail-nikolaev/task-force-arma-3-radio#1301]
**Arma 3 Version:** `1.74`
**CBA Version:** `3.4.0`
**Task Force Radio Version:** `1.0.248`

**Mods:**
ace3
CBA
TFAR

**Description:**
- interaction button is not working. disable, crew, cargo. all of this

**Comment by dedmen** [comment]
Crap :x

**Comment by dedmen** [comment]
Fixed in 249?

**Comment by sbng-PAPA** [comment]
it's working!!

i'm happy
