### ISSUE TITLE
Custom radio sounds not working anymore

### ISSUE THREAD

**Issue by Bydget** [michail-nikolaev/task-force-arma-3-radio#1302]
**Arma 3 Version:** `1.74` (stable)
**CBA Version:** `3.2.1` (stable)
**Task Force Radio Version:** `1.-1.0.245` (stable)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@RHS`

**Description:**
This isn't really such a massive issue, however, I liked having the ACRE sounds instead of the current ones. Typically, you would be able to just change them in the plugins folder in TeamSpeak, however, that doesn't work anymore for some reason. This might be a TeamSpeak 3 issue? I have no clue.

**Steps to reproduce:**
- Download ACRE sounds and replace current .wav files in plugins\radio-sounds. I downloaded the .wav files from here: http://www.armaholic.com/page.php?id=28342

**Where did the issue occur?**
- I tried in both SP and MP and it doesn't work.

**Comment by dedmen** [comment]
Which plugins folder? Appdata or Program files?

**Comment by Bydget** [comment]
Oh, they are two? I usually changed Program files. Do you need to change AppData as well or no?

**Comment by Bydget** [comment]
Ah right. I'm an idiot. I was changing the wrong thing the whole time. Sorry for any inconvenience. You may mark this as solved or delete it.

**Comment by dedmen** [comment]
Changed with Teamspeak 3.1
