### ISSUE TITLE
Possible to add a button to the TS toolbar to disable/enable plugin?

### ISSUE THREAD

**Issue by Snak3Doc** [michail-nikolaev/task-force-arma-3-radio#1305]
The title says it all, is it possible to add a button (like the overwolf one) to the ts toolbar for enabling/disabling the tfr plugin?

**Comment by ArMaTeC** [comment]
i think this is hard coded as OW is partnered with TS3

**Comment by Snak3Doc** [comment]
Thought this might be the case, just thought id ask as everyone always complaining about turning it on/off

**Comment by ArMaTeC** [comment]
maybe head over to the ts3 forums and request that addons be added to the tool bars as toggles you never know they might add it as it should be quite simple to add

**Comment by dedmen** [comment]
I can't enable/disable the plugin.
But what are you trying to archive?

**Comment by ArMaTeC** [comment]
what he means is he wants to add a shortcut to the tool bar to directly enable/disable TFAR directly

**Comment by dedmen** [comment]
I know what he means. That directly is not possible. So that's why I ask what the final goal is.

**Comment by ArMaTeC** [comment]
Ok  sorry to butt in was trying to help save you the need to do so but his end goal was to speed up the process of disabling/enabling the plugin

**Comment by dedmen** [comment]
If it is to diable the channel switching for example.. I already have a solution for that.

**Comment by Snak3Doc** [comment]
ArMaTec is correct it's purely to speed up the process of disabling/enabling the plugin when your playing with/without ( I'm aware of than channel switching thanks great feature for us Aussies with our derp net) When I get round to it, I'll ask on the ts forums for them to add it

**Comment by dedmen** [comment]
Yeah. Can't do that then.
