### ISSUE TITLE
Unable to install TS plugin

### ISSUE THREAD

**Issue by ndfmoab** [michail-nikolaev/task-force-arma-3-radio#1307]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** 1.-1.0.259
**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
Fresh install of windows. Fresh install of teamspeak. When I install the TFAR plugin it shows an error in the settings "Plugin could not be loaded: Failed to open plugin.: -518312306 (minimum 21, current 22)"

**RPT log file:**
**https://pastebin.com/e2wb3sYQ**

**Comment by theYoursTruly** [comment]
Do you have ACRE installed?

**Comment by ndfmoab** [comment]
No, ACRE is not installed

**Comment by dedmen** [comment]
"The specified module could not be found."
Some DLL TFAR depends on was not found.. Problem is.. TFAR doesn't depend on any dll. Antivirus?

**Comment by ndfmoab** [comment]
Might be. The problem went away after I repeatedly rebootet my system due to windows updates.
