### ISSUE TITLE
Phones/Cellphones for TFAR ?

### ISSUE THREAD

**Issue by Fameling** [michail-nikolaev/task-force-arma-3-radio#1312]
Is it Possible to add some Cellphones or something like this in the Mod?

If its Possible it would be Very nice if you can add this :)

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1063
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/961
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/702

What do you create a duplicate issue if you know very well that the other one exists?!
