### ISSUE TITLE
Race condition with group frequencies.

### ISSUE THREAD

**Issue by Coryf88** [michail-nikolaev/task-force-arma-3-radio#1314]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**Task Force Radio Version:** `1.-1.0.259` (beta)

**Mods:**
- `@CBA_A3`
- `@Task Force Arrowhead Radio (BETA!!!)`

**Description:**
- A race condition occurs with setting group frequencies.
- If the server takes longer to do `TFAR_fnc_processGroupFrequencySettings` then the client takes to use `TFAR_fnc_getSwSettings` or `TFAR_fnc_getLrSettings`, the client will generate their own frequencies.
- Increasing the chance of the race condition can be done by adding a "Game Master" (ModuleCurator_F) module, which delays the call of `TFAR_fnc_processGroupFrequencySettings`.

**Steps to reproduce:**
- Open the Editor.
- Enforce "Same LR frequencies for side".
- Place a 'Men', edit the unit's load-out, and add a TFAR LR backpack.
- Place a "Game Master" (ModuleCurator_F) module.
- Start mission in Multiplayer.
- Notice frequencies of `(call TFAR_fnc_activeLRRadio) call TFAR_fnc_getLrSettings;` and `group player getVariable "tf_lr_frequency";` are different.

**Where did the issue occur?**
- Dedicated and Self-Hosted Multiplayer

**Comment by dedmen** [comment]
That's not very easy to fix though. We can set a variable after the server first set the frequencies. But for JIP players the variable might arrive before the def frequencies.

**Comment by Coryf88** [comment]
Yes, having the client wait until the group's `tf_sw_frequency`/`tf_lr_frequency` have been set should work.

**Comment by dedmen** [comment]
SW shouldn't be a problem as the client requests these from the server... Or atleast that can be solved serverside by not giving out any Radios until the server is ready.

**Comment by dedmen** [comment]
@Dorbedo Rewrote most of that. If still an issue feel free to comment here and I'll reopen.
