### ISSUE TITLE
Frequencies Module

### ISSUE THREAD

**Issue by Snak3Doc** [michail-nikolaev/task-force-arma-3-radio#1316]
TFR - 1.-1.0.264
CBA - 3.4.1.170912
ACE - 3.10.2
Arma3 - stable, problem persists over multiple versions
Lots of other shite...

Im trying to set up the frequencies module, but it only works for the first person the first time they load into a slot, doesn't work for other players joining and doesn't work for the first player if he backs out to the lobby and rejoins, am i missing something?

Im using 3 of the modules set to "synchronized objects only"

ps. just realised i forgot to add my tfr version ect my bad

**Comment by dedmen** [comment]
The preset frequency variables are in the JIP queue...
If the variables arrive after your radio get's it's frequency then it will use default frequency..
Just got another Idea.. I could just make the frequencies module execute clientside.. that should work

**Comment by dedmen** [comment]
Also! The frequencies Module that you sync with groups... You sync it with Groups. So if someone rejoins and is not in the same group as before, He won't get his default frequency.
Also if you are the last member in a Group I can imagine Arma will just delete all variables of that group.
But that should also be fixable by my idea.

**Comment by Snak3Doc** [comment]
Yea I tried a few of variations of method for setting it "sync with groups of objects" ect ect and syncing the module to the object and vice-versa, had no luck. seeing as were in Aus I'm guessing its to do with our shite internet and the settings not getting to the players in time like you said in your first comment.

**Comment by dedmen** [comment]
Modules are gone.
