### ISSUE TITLE
Curator Hears Players Through Curator Camera Not Working?

### ISSUE THREAD

**Issue by Snak3Doc** [michail-nikolaev/task-force-arma-3-radio#1317]
TFR - 1.-1.0.264
CBA - 3.4.1.170912
ACE - 3.10.2
Arma3 - stable, problem persists over multiple versions
Lots of other shite...

Is there something else that's required to get the option for curators to hear players voices through their curator camera, other than just selecting the tick box on your curator units attributes menu? 

ive tried this option over multiple version of arma/tfr/cba and never had any luck with it.

**Comment by dedmen** [comment]
Does `player getVariable ["TFAR_curatorCamEars",false]` report false?
Alternative `this setVariable ["TFAR_curatorCamEars", true]` into the init box of that unit. Does that work? If it does then it's just the Eden attribute being broken for whatever reason.

**Comment by Snak3Doc** [comment]
Ok it's the Eden attribute that's broken not sure if it's caused by a mod conflict or not, but I just tested using the init setVar method on windows dedi and it worked, thanks man. FYI ace had a similar issue with their Eden attributes for setting medic/engi not saving properly.

**Comment by Dorbedo** [comment]
should be fixed after #1331
