### ISSUE TITLE
TFAR signature mismatch when trying to join my server. 

### ISSUE THREAD

**Issue by Adde2012** [michail-nikolaev/task-force-arma-3-radio#1318]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**Task Force Radio Version:** `1.-1.0.264` (dev)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
- When trying to join the server, it gives the following error in the launcher: "Load 'Task Force Arrowhead Radio 1.-1.0 (dev)' from library (signature mismatch)" 
I have the same key both on the server and on my computer. 

**Where did the issue occur?**
- Dedicated, hosted by myself

**Comment by Adde2012** [comment]
"tfar_1..bikey" It's straight from the mod folder.

**Comment by dedmen** [comment]
that filename might be incorrect... does it match the name of the bisigns?

**Comment by condolent** [comment]
I'm having the same exact issue.

**Comment by dedmen** [comment]
@condolent did you try doing what I just recommended?

**Comment by condolent** [comment]
@dedmen Yeah my keynames are correct, it's basically a fresh install of tfar

**Comment by dedmen** [comment]
But the keynames are wrong on a fresh install :o

**Comment by Adde2012** [comment]
Ok, the bisign file is called "tfar_core.pbo.tfar_1.-1.0-f6024bd2.bisign" Should i rename the bikey to "tfar_core.pbo.tfar_1.-1.0-f6024bd2.bikey"?

**Comment by dedmen** [comment]
No. Read my message again. only the `x` part

**Comment by Adde2012** [comment]
Isn't the x "tfar_1.-1.0" 
Or is it the entire "tfar_1.-1.0-f6024bd2"

**Comment by condolent** [comment]
@dedmen Not sure what you mean.

My keys names inside `@task_force_radio\keys` are as follows:
```
[TF]Nkey8.bikey
[TF]Nkey9.bikey
```

And the bisigns inside `@task_force_radio\addons` are as like this:
```
task_force_radio.pbo.[TF]Nkey8.bisign
task_force_radio.pbo.[TF]NKey9.bisign

task_force_radio_items.pbo.[TF]Nkey8.bisign
task_force_radio_items.pbo.[TF]NKey9.bisign
```

Since I only have 2 bikeys and 4 bisigns, how can I rename them to the bisings?

**Comment by Adde2012** [comment]
Alright, i renamed the bikey "tfar_1.-1.0-f6024bd2.bikey" It seems to be working now, thanks for the help!

**Comment by dedmen** [comment]
@condolent Read TFAR version in first post. You don't have the exact same issue.
