### ISSUE TITLE
TeamSpeak Failed to load plugin

### ISSUE THREAD

**Issue by BmanDesignsCanada** [michail-nikolaev/task-force-arma-3-radio#1320]
**Task Force Radio Version:** `dev 1.-1.0.264`
**TeamSpeak 3 Version:** `3.1.6 [Stable]`

**Description:**
- Failed to load TFAR plugin in TeamSpeak 3.1.6
- Minimum: 21, Current: 22

Fresh installed TeamSpeak today and have run into this issue. Our group had a copy of task_force_radio.ts3_plugin stored in our repo and it didn't work, downloaded the most recent and it gave the same error.

**Steps to reproduce:**
- Use the dev .ts3_plugin from 264 with TeamSpeak 3.1.6

**Comment by BmanDesignsCanada** [comment]
My computer was missing dependencies. Installing DirectX or redoing the Arma first time setup should solve this.

**Comment by dedmen** [comment]
No you didn't have problems with dependencies. You installed the 0.9.12 non 3.1 compat TS plugin.

**Comment by BmanDesignsCanada** [comment]
Nope, I am positive the correct version was installed. The version number of the plugin was 1.-1.0.264 in TeamSpeak 3 and we've not used 0.9.12 in over 8 months, I don't have a copy of 0.9.12 and would never download it.
