### ISSUE TITLE
TS3 crash after plugin installation

### ISSUE THREAD

**Issue by shukari** [michail-nikolaev/task-force-arma-3-radio#1324]
**Task Force Radio Version:** BETA 1.0.264

**Description:**
- After install TeamSpeak crash at startup

**Steps to reproduce:**
- install TFAR plugin
- restart
- crash

**Logs/Crashfiles/Dumps**
https://workupload.com/file/a5wuk4A

**Comment by dedmen** [comment]
Teamspeak loaded the plugin. and for some reason unloaded it immediatly but failed at that and decided to kill itself.

**Comment by theYoursTruly** [comment]
ACRE plugin installed and/or activated?

**Comment by shukari** [comment]
Fresh installation... no acre... see logs...

**Comment by dedmen** [comment]
The logs don't tell that much. There is one client log and that's veeery old.

**Comment by shukari** [comment]
dead end
