### ISSUE TITLE
ACE³ self interactions for interaction with radios not available if sitting in vehicle

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1328]
**Arma 3 Version:** `current` (stable)
**CBA Version:** `3.4.1.170912`
**Task Force Radio Version:** `1.0.264`
**ACE3 Version:** `3.11.0`

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@ace`

**Description:**
- The self interactions "Radios" and "Lower Headset"/"Raise Headset" aren't shown when sitting in vehicle.

**Steps to reproduce:**
- Get in vehicle
- Try to lower your headset with ace³ self interaction.

**Comment by Pergor** [comment]
Oh, by the way: Parachutes have an intercom. Just so you know. ;)

**Comment by dedmen** [comment]
Oh..... Uhm.. Oops? :D

**Comment by Pergor** [comment]
They **are** vehicles, so... But it gets a bit lonely after a bit of talking on the intercom. ;)

**Comment by dedmen** [comment]
#1323
