### ISSUE TITLE
Player keeps transmitting after dying

### ISSUE THREAD

**Issue by neilzar** [michail-nikolaev/task-force-arma-3-radio#1335]
**Arma 3 Version:** `1.76` (stable / rc / dev)
**CBA Version:** `3.4.1.170912` (stable / dev + commit hash)
**Task Force Radio Version:** `1.-1.0.262` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@ace`

**Description:**
- When a player is killed while transmitting on their SR, he will keep transmitting when dead if he keeps holding the transmit key. Only once he releases the key will he stop transmitting.
- Think it should be that when he dies, it should cut off his radio.

**Steps to reproduce:**
- Have 2 players in a game.
- Player one transmits on the short range.
- Player two then kills player one, player one keeps holding their transmit button.
- Player one will still be heard by alive players, eventhough he is spectating.

**Where did the issue occur?**
- Dedicated Multiplayer

**RPT log file:**
- [paste](https://paste.ee/p/0uvTq)

**Comment by dedmen** [comment]
Killed eventhandler should kill transmissions :/

**Comment by dedmen** [comment]
Make new TFAR_fnc_releaseAllTangents `"task_force_radio_pipe" callExtension (format ["RELEASE_ALL_TANGENTS	%1", name player]);`
and call in https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/plugin/fnc_sendPlayerKilled.sqf#L23

**Comment by dedmen** [comment]
Fixed in 271 release should be today. Waiting for confirmation on the fix

**Comment by neilzar** [comment]
This is fixed. Only issue that persists, when someone was transmitting on the radio when dying, they will be hotmicing afterwards. Which is then fixed by switching from voice activation to push to talk and back.

**Comment by dedmen** [comment]
But.... Wasn't that the issue this report was about? :D You keeping to transmit when dead?
They stop radio transmitting but their mic still transmits in 3D voice mode? I know where I have to look for that.

**Comment by neilzar** [comment]
This is different. Before they could constantly be heard on the radio when they died. Now after dying, they stop transmitting on the radio after about a second, but they will have their mic infinitely enabled. So they aren't transmitting on radio, but they are constantly talking in spectator.

**Comment by dedmen** [comment]
Jup know what is causing that. But The ending of radio transmissions should stop that too. Should be easy to fix.

**Comment by dedmen** [comment]
Cannot confirm. When I die I stop transmitting. And mic also stops sending in TS.
