### ISSUE TITLE
Short range radio doesn't work when playing a COOP mission on LAN

### ISSUE THREAD

**Issue by daelyn1** [michail-nikolaev/task-force-arma-3-radio#1343]
The host can open the CTRL+P interface and transmit on the short range radio but the other players can't hear it, transmit or even open the CTRL+P interface. Direct speech and the long range radio work fine.

**Comment by dedmen** [comment]
Radio ID's not being assigned. There is a issue template (https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/.github/ISSUE_TEMPLATE.md) for a reason. Please use it.

**Comment by daelyn1** [comment]
It's working now, I messed up something in the TFAR modules. Sorry for being this incompetent.
