### ISSUE TITLE
Unable to use radio

### ISSUE THREAD

**Issue by LiamSmith1** [michail-nikolaev/task-force-arma-3-radio#1344]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `Stable` (stable / dev + commit hash)
**Task Force Radio Version:** `Stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
When i join a server i will attempt to use the radio however it will cause me to hot mic on the radio and this will only stop if i change radio freq channel. After that i cant use the radio at all. Please help.

**Steps to reproduce:**
I really dont know i think its just a bug

**Where did the issue occur?**
- Dedicated

**RPT log file:**
https://pastebin.com/vP1BVCrJ
IDK if this is right ill try and fix if it isnt

**Comment by dedmen** [comment]
There is important data missing from your RPT file.

**Comment by LiamSmith1** [comment]
https://file.io/KpMik2
I`ve been messing about and got it to work 2 now but i dont know what im doing to fix it.

**Comment by dedmen** [comment]
That file you linked doesn't exist.

**Comment by LiamSmith1** [comment]
http://www.mediafire.com/file/ze4d1ph91pzx8pd/Arma3_x64_2017-11-23_15-27-18.rpt
Sorry about the inconvenience.

**Comment by Dorbedo** [comment]
You have uploaded a rpt without any mod:
`[...]\common\Arma 3\Arma3_x64.exe" -mod= -beservice`

**Comment by LiamSmith1** [comment]
i just copy and pasted it.

**Comment by dedmen** [comment]
The log is useless. We need a log from when you had the issue.
Are Radios working fine for others on the same server?

**Comment by LiamSmith1** [comment]
A month or 2 ago i was playing on a modded server and it was working perfectly. When i load into the server i delete TFR and reinstall it and then re log and it seems to work,

**Comment by LiamSmith1** [comment]
Update: When i unbind my push to talk in game (Caps lock), my radio works.

**Comment by dedmen** [comment]
That's something you should do anyway.
