### ISSUE TITLE
Option to prevent automatic channel move

### ISSUE THREAD

**Issue by chris579** [michail-nikolaev/task-force-arma-3-radio#1353]
In some cases you don't want to be automatically moved to the TFAR channel when joining the game. It would be nice to introduce a CBA setting where you can define whether you would like to be auto moved or not.
Plus, it could be quite useful to introduce another setting disabling the auto move back to the TFAR channel when leaving it. Sometimes some people have problems with their game so you would help them without leaving the game and without disabling TFAR. This was possible in 0.9 because it was not enforced to stay in the TFAR channel but now in 1.0 there is no possibility to do so.

**Comment by dedmen** [comment]
Is it enough if I disable automove while you are tabbed out of Arma?

**Comment by chris579** [comment]
It could but in some cases you might want to stay tabbed into Arma while not being in the TFAR channel. For example if you are Zeus and want to do things ingame while speaking to people that are performing JIP.

**Comment by dedmen** [comment]
I guess in that case you'd have to disable TFAR if you want to permanently stay out. I don't really want users to be able to just disable the automove. And you can't talk to other people while TFAR is enabled anyway. As serious mode mutes everyone that isn't ingame.

**Comment by chris579** [comment]
You could disable serious mode when this setting is enabled. Server admins are able to force automove so this options would give experienced users more freedom when using TFAR. If this is too much work then disabling automove when tabbed out is fine.

**Comment by dedmen** [comment]
If I make it a CBA setting you'd have to click through to the options menu.. Which is about the same effort as just disabling the plugin in TS

**Comment by chris579** [comment]
Well, you would just leave the settings you like on. Personally, I would permanently disable the automove back to channel when leaving it because there are often cases I would like to leave it.

**Comment by dedmen** [comment]
Is disabled now for when you are tabbed out since 274. Like said in https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1353#issuecomment-350017441
Is this done now then?

Having a setting would also require some way on the server to configure which user is allowed to disable it. As generally you don't want users to be able to do that

**Comment by chris579** [comment]
Dunno, 0.9 also allowed it and there were no real issues about it.

**Comment by dedmen** [comment]
Implemented now.
You by default don't get moved while tabbed out. But can be enabled via clientside setting.
