### ISSUE TITLE
Custom Radio Value/Set

### ISSUE THREAD

**Issue by Purry** [michail-nikolaev/task-force-arma-3-radio#1354]
I have searched but I am either not finding the right words or it doesnt exist, essentially I would like to know how to asign LR values to items or to make an item that isnt a backpack for a LR. 

Essentially the new ear piece from Laws of War to transmit long range so that I can keep my backpack.

**Comment by dedmen** [comment]
Can't.

**Comment by dedmen** [comment]
I guess you could mod the ear piece into a shortrange radio with long range if you really wanted..... No.. No doesn't work as the Radio doesn't go into the Radio slot.
