### ISSUE TITLE
Teamspeak Changes for Flexibility

### ISSUE THREAD

**Issue by HellBz** [michail-nikolaev/task-force-arma-3-radio#1358]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** `x.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
Can You Add a Function to get Server-IP and Channel ID.

i Think it will be mutch Better...

**Comment by dedmen** [comment]
Dude...
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Functions
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Functions#TFAR_fnc_getTeamSpeakChannelName
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Functions#TFAR_fnc_getTeamSpeakServerName

Would you please stop creating nonsense non issues?

**Comment by HellBz** [comment]
Pls das


TFAR_fnc_getTeamSpeakChannelID
Now you can check the channel I'D and the Server owner can change the Channel Name..

TFAR_fnc_getTeamSpeakChannelIP
Now you can change the Servername,
If you check, if a Player is on the Server..

**Comment by dedmen** [comment]
Feel free to use German if your english is too crusty to explain things correctly.

**Comment by HellBz** [comment]
Dass ich bei der Überprüfung eines Teamspeak der Name auch ändern kann wäre es eigentlich sinnvoller zu überprüfen ob man auf die richtige IP connected hat daher die Abfrage von der server IP.

Desweiteren die Abfrage der Channel ID daher da man so den Namen flexibel auch ändern kann ohne dass in gewissen abfragen the script fehlschlägt.

So gestern auf meinem Server ich habe einen black faded Script das heißt wo man erstmal überprüft wird ob man auf dem Server ist da wurde aber nur der Server Name verglichen und bei dem Servernamen war am Ende des Namens ein Leerzeichen und in meinem Skript war das Leerzeichen nicht und somit hat es mich auf meinem eigenen Server nicht spielen lassen.

Daher fände ich es für mehr Flexibilität besser wenn man die server IP und die Channel ID überprüft da man als Server Inhaber so den Namen des Servers oder den Namen des Channels auch ändern kann ohne dass das Script auf dem Server fehlschlägt.

Weil sobald ich nur den Servernamen oder den channelnamen ein klein wenig appendere muss ich das auf dem Server auch machen in dem Skript und bekomme so keine Genehmigung zum Spielen auf dem Server.

Hier ein Example Script, durch 5 sec. GOOGLE..

https://www.altisliferpg.com/topic/1054-tutorial-task-force-radio-black-screen-when-not-in-channel-etc/

Mein Anliegen ist ernst gemeint und es ist kein einfacher Spam Post da ich mir auch Script technisch Gedanken mache wenn ich sowas poste.

Des Weiteren der andere Post mit der userconfig ist daher entstanden da mein Server bzw Task Force Radio mit mir sagt dass Task Force Radio auf dem Server nicht enabled wäre und ich weiß nicht warum mir dieses Popup immer wieder kommt

**Comment by dedmen** [comment]
`bei dem Servernamen war am Ende des Namens ein Leerzeichen und in meinem Skript war das Leerzeichen nicht` Das du den Namen falsch schreibst ist aber nicht mein Problem.
`klein wenig appendere` Das ist weder deutsch noch englisch.
`mir sagt dass Task Force Radio auf dem Server nicht enabled` Das hat 0 mit der userconfig zutun.
Wow ist das ein beschissenes script das du da gelinked hast XD

Hier übrigens mal ein ausschnitt meiner Todo liste

**Comment by DeliciousJaffa** [comment]
Haven't tested this, but does the channel ID work within the CBA Settings framework?

**Comment by dedmen** [comment]
@DeliciousJaffa Nope
#TODO tho

**Comment by dedmen** [comment]
Getting the Server IP might be a security issue though. If someone is tabbed out and on another server you could spy on them and find out where they are.
How about a getter for the server UID instead?

Server UID and channelID are now implemented on Plugin side (SQF Side functions still on TODO).
Ability to use channel ID's for serious channel names was added. To use them write `ID:<channelID>` as channel name in the settings. The `ID:` is case sensitive. `id:1232` won't work.
See 2687898d352eadf165303832952701d17499b903

**Comment by DeliciousJaffa** [comment]
This maybe out of scope, but perhaps allow sending of IP/Domain to the plugin which could prompt the user "The Arma server you have connected to would like you to connect to <teamspeak server>, would you like to connect?" and any check for if the user is on that server can be done from serverID from then on

**Comment by dedmen** [comment]
@DeliciousJaffa Not possible. Cannot join servers afaik.

**Comment by DeliciousJaffa** [comment]
Fair enough, there's enough functionality for mission makers to implement systems in-game to tell a user how to connect

**Comment by dedmen** [comment]
ServerUID and ChannelID getters were implemented.
And you can now use channelID for serious channel setting.
Leaving this open in case anyone finds errors

**Comment by dedmen** [comment]
No errors.
To use the ChannelID instead of channelName for the CBA setting enter `ID:123` as the Teamspeak channel name. TFAR checks for the `ID:` at the start.
