### ISSUE TITLE
TFAR Automove not working since cba / tfar update.

### ISSUE THREAD

**Issue by Formannl** [michail-nikolaev/task-force-arma-3-radio#1364]
Arma 3 Version:  `1.80.143751` 
CBA Version: 3.5.0
Task Force Radio Version: 1.0.272

**Mods:**
- @CBA_A3
- @task_force_radio
- @ACE

**Description:**
- Automove to TFAR channel not occuring on teamspeak. Also the FORCE TFAR module is gone in the editor.

**Steps to reproduce:**
- Updated CBA - ACE and TFAR to versions above.

**Where did the issue occur?**
- Dedicated server

So basicly I update CBA, TFAR and ACE , for some reason the automove to TFAR channel is not occuring. Also when looking in the eden editor the module for tfar seems to be gone. I already tried reverting back to our old ACE version. But that doenst seem to fix the problem. So it should be somewhere with CBA and TFAR.

**Comment by dedmen** [comment]
Please ask on Discord or Slack before reporting a user error as bug.
Everything was moved to CBA settings.

**Comment by Formannl** [comment]
Well oke, im did read that but im not familliar with the CBA settings. Sorry if I frustrated you.
