### ISSUE TITLE
Problem with pressing t key

### ISSUE THREAD

**Issue by shukari** [michail-nikolaev/task-force-arma-3-radio#1376]
**Arma 3 Version:** stable
**CBA Version:** stable
**Task Force Radio Version:** dev

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- press t get error

**Steps to reproduce:**
- A-10D vabnilla jet
- press t key

https://steamuserimages-a.akamaihd.net/ugc/939431644136135148/7B2F26A7F05ED339C7C087885CA3727878142B83/

**Comment by Dorbedo** [comment]
I can't reproduce the error. Could you please provide the *.rpt file.

**Comment by Radeni** [comment]
@Dorbedo I can confirm that this error does appear but only in singleplayer/editor, it also happens when clicking Y for aditional on LR radio but since TFAR is by all means intended for multiplayer i dont think there's anything that needs fixing

**Comment by dedmen** [comment]
It shouldn't be pressable in singleplayer. Just like the normal radio key. Maybe I just forgot it for the additonal key.
