### ISSUE TITLE
Radio duplication when switching SW radio

### ISSUE THREAD

**Issue by neilzar** [michail-nikolaev/task-force-arma-3-radio#1377]
**Arma 3 Version:** `1.80`
**CBA Version:** `3.5.0`
**Task Force Radio Version:** `1.0.273` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `ACE`
- `Backpack on chest`

**Description:**
- This is a bug I had reported to me by a Community Member, but it is quite complex to have it happen. Basically, after messing around a bit with backpacks and putting one on your chest and back etc. It will start duplicating the Short Wave radio. [Video showing it happening](https://youtu.be/vHTsKnfgpAM)

This was done using ACE Arsenal but may also happen with BIS Arsenal.

**Steps to reproduce:**
- Get a normal AN/PRC-152 from the arsenal and put it in a backpack
- Get another AN/PRC-152 from the arsenal
- Use the ACE interaction "Put backpack on chest"
- Get another backpack from the arsenal and put whatever in it (No idea if it impacted it)
- Switch again so you have the backpack with the radio on your back and the other on your chest
- Use the bind from TFAR "Change Left SW Radios" (No idea if keeping the backpack on your chest impact anything)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**RPT log file:**
- [Google Drive](https://drive.google.com/file/d/1CyPV4Co0MAjYZwaET8dp3bXIH6Tg3eYs/view?usp=sharing)

**Comment by dedmen** [comment]
So what's wrong? The radio should be removed from backpack but isn't?

**Comment by neilzar** [comment]
The problem is that your backpack gets filled with endless copies of your radio. E.g. you end up with 5 AN/PRC-152 30 and 5 AN/PRC-152 32 radios for example. Not sure what could cause this, but the video shows it happening.

**Comment by Dorbedo** [comment]
This happens because the inventory of TFAR is cached.
Try `TFAR_lastLoadoutChange = 0;` after changing the backpack from back to front.

**Comment by dedmen** [comment]
CBA's Loadout changed EH should catch the backpack being changed. And it should also detect changes in backpack Inventory.

**Comment by dedmen** [comment]
Is this still happening?

**Comment by neilzar** [comment]
I have not tested it myself, also haven't heard of the issue from anyone else. Can't confirm if it is fixed.

**Comment by SekiAlpha** [comment]
@neilzar any updates?

**Comment by SekiAlpha** [comment]
I tried replicating it and I couldn't reproduce.

**Comment by dedmen** [comment]
¯\\_(ツ)_/¯
