### ISSUE TITLE
tf_sendingDistanceMultiplicator trend?

### ISSUE THREAD

**Issue by Lorenz94B** [michail-nikolaev/task-force-arma-3-radio#1379]
Hi,
me and my clan are using Task Force Radio for a long time, and what I would like to know is what's the exact mathematical process behind this variable (or its antagonist, tf_receivingDistanceMultiplicator).

What I'm trying to achieve is a jammer acting in a non-linear way,  so that the communications get worse the nearer a player gets to the object designated as jammer.

The problem is that this variable seems to (almost) completely prevent cooms only if set at 0.001. What I would like to achieve is near zero comms between players really near to the jammer (one distant from another a couple of meters), and increasing the value back to 1 near the "edge" of the radius of action of the jammer.

If you're so kind to explain to me the exact calculation that your mod does (so I can understand for what value I hear nothing), would be cool!

Thank you.

**Comment by dedmen** [comment]
Why don't you just look in the code?
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/ts/src/clientData.cpp#L71-L79
`TF_terrain_interception_coefficient` and `tf_receivingDistanceMultiplicator` and https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_calcTerrainInterception.sqf
