### ISSUE TITLE
WE GOT A PROBLEM WITH GRABING THE RADIO OF VIRTUAL ARSENAL

### ISSUE THREAD

**Issue by DivisionFAS** [michail-nikolaev/task-force-arma-3-radio#1383]
**Arma 3 Version:** `1.78` 
**CBA Version:** `3.5` 
**Task Force Radio Version:** `0.9.12` 

**Mods:**
- `@CBA_A3`
- `@task_force_radio
- `@A3CNFARDAS
- `@FFAA
- `@ACE3

**Description:**
Hi guys, we're a hispanic clan and a long time ago we used task force radio, but now we have issues with grabbing the radio from the arsenal, when we grab it, we are gettin issues with open the radio menu and when we're online, the host can grab radios from the arsenal and ''transform'' radios from another players. I tried to fix the problem by changing the teamspeak version, changing the host and download again the TFR addons, but it doesn´t work

**Where did the issue occur?**
- Dedicated Server

**Comment by dedmen** [comment]
WHAT? I CAN'T HEAR YOU!

**Comment by dedmen** [comment]
Ace Arsenal? 0.9.12 doesn't support ACE arsenal. Already fixed in 1.0.
