### ISSUE TITLE
Unable to hear people / Static on LR when stood next to each other

### ISSUE THREAD

**Issue by nobodyshome** [michail-nikolaev/task-force-arma-3-radio#1390]
**Arma 3 Version:** `1.80.143869`
**CBA Version:** `3.5`
**Task Force Radio Version:** `1.0.274`

**Mods:**
```
http://addons.jfchq.uk/ModList.txt
```
**Description:**
- About an hour into a mission, radio comms seems to break down, people next to each other on short range and long range become static. Some on LR just simply can't hear another person. Has happened the past 5-10 times we have played, its super inconsistent in showing itself.

**Steps to reproduce:**
- So far the only things we found that "may" have an effect on causing this, is getting into certain helicopters/vehicles. May also be linked to player count? The more plays the worse the issue seems to propogate however sometimes with the same numbers its fine. 

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Will add the RPT log on the 25/02/2018 if the issue persists on this next mission due to me not having a rpt log on hand for when the issue occured.

**Comment by dedmen** [comment]
Known issue and being worked on for about half a year now.

**Comment by nobodyshome** [comment]
Anything specific you need done testing wise to help narrow down a cause? Or has that already been identified?

**Comment by dedmen** [comment]
We are currently testing a experimental alpha build. Join TFAR discord to grab it if you wanna test. 
I think we are quite close to isolating the cause.

**Comment by nobodyshome** [comment]
Will do, is there a invite link anywhere? Had a look around before making the bug report but couldn't find a way to joing a slack/discord.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1116 discord link is in there
