### ISSUE TITLE
How to add radio in vehicle

### ISSUE THREAD

**Issue by EndiaFR** [michail-nikolaev/task-force-arma-3-radio#1391]
**Arma 3 Version:** `Latest/Stable` (stable / rc / dev)
**CBA Version:** `3.6.1 stable` (stable / dev + commit hash)
**Task Force Radio Version:** `0.9.12 stable` (stable / dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- I want to add the radio in my vehicle, how i do this ?

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Dorbedo** [comment]
Please at least try to read the wiki:

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-For-developers#vehicles

Or:
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Variables
```
_vehicle setVariable ["tf_hasRadio", true, true]
Forces the presence of a vehicle-mounted radio.
```

**Comment by EndiaFR** [comment]
Where i add this ? ^^ `class MyVehicleWithRadio: LandVehicle {
    tf_RadioType = "some_backpack_radio_class";
};`

**Comment by dedmen** [comment]
@EndiaFR in your vehicles config.
This is for issues not questions.

**Comment by EndiaFR** [comment]
Oops sorry its the first time i post on github issues ^^' And for the : `_vehicle setVariable ["tf_hasRadio", true, true];` its on my init.sqf?

**Comment by dedmen** [comment]
You can put that wherever you want. Just make sure you pass the vehicle you want.
