### ISSUE TITLE
Cant add TFAR to my Arsenal Whitelist.

### ISSUE THREAD

**Issue by KlausMalzbier** [michail-nikolaev/task-force-arma-3-radio#1394]
**Arma 3 Version:** `1.80` stable
**CBA Version:** `3.6.1` stable
**Task Force Radio Version:** `0.9.12 stable

**Mods:**
ace 
ACE Compat - RHS Armed Forces of the Russian Federation
ACE Compat - RHS United States Armed Forces 
ACE3 - BWMod Compatibility 
Advanced Urban Rappelling 
Blastcore Edited (standalone version)
BWMod 
CBA_A3
CUP Terrains - Core
CUP Terrains - Maps 
Enhanced Movement 
FA-18 Super Hornet
Immerse
JSRS SOUNDMOD 
JSRS SOUNDMOD - Additional Weapon Handling and Reloading Sounds
KP Ranks 
MCC Sandbox 4 -  Mission Making The Easy Way 
Mine Detector 
Remove stamina 
Remove stamina - ACE 3 
RHSAFRF
RHSUSAF
ShackTac User Interface
Suppress
Task Force Arrowhead Radio 0.9.12
X-Cam-Taunus (Version 1.1)

**Description:**
I can't add one or all of the TFAR Radios to my whitelist. Every other Item works, but TFAR Radios.
In which category do the TFAR Radios need to be in?
// Custom Arsenal Preset

// Mods needed:
// ACE
// BWMod
// RHS AFRF
// RHS USAF

GRLIB_arsenal_weapons = [
	"arifle_AK12_F",
	"arifle_AK12_GL_F",
	"arifle_AKM_F",
	"arifle_AKS_F",
	"srifle_DMR_04_Tan_F",
	"srifle_dmr_04_f",
	"hgun_PDW2000_F",
	"arifle_TRG20_F",
	"srifle_DMR_05_tan_f",
	"arifle_Mk20_plain_F",
	"arifle_Mk20_GL_plain_F",
	"arifle_Mk20C_plain_F",
	"BWA3_G27",
	"BWA3_G27_Tan",
	"BWA3_G27_AG",
	"BWA3_G27_Tan_AG",
	"BWA3_G28_Standard",
	"BWA3_G28_Assault",
	"BWA3_G36",
	"BWA3_G36_LMG",
	"BWA3_G36_AG",
	"BWA3_G36K",
	"BWA3_G36K_AG",
	"BWA3_G38",
	"BWA3_G38_Tan",
	"BWA3_G38_AG",
	"BWA3_G38_AG_Tan",
	"BWA3_G38C",
	"BWA3_G38C_Tan",
	"BWA3_G38K",
	"BWA3_G38K_Tan",
	"BWA3_G38K_AG",
	"BWA3_G38K_AG_Tan",
	"BWA3_G82",
	"srifle_GM6_F",
	"MMG_01_tan_F",
	"arifle_SPAR_01_khk_F",
	"arifle_SPAR_01_snd_F",
	"arifle_SPAR_01_blk_F",
	"arifle_SPAR_01_GL_khk_F",
	"arifle_SPAR_01_GL_snd_F",
	"arifle_SPAR_01_GL_blk_F",
	"arifle_SPAR_02_khk_F",
	"arifle_SPAR_02_snd_F",
	"arifle_SPAR_02_blk_F",
	"arifle_SPAR_03_khk_F",
	"arifle_SPAR_03_snd_F",
	"arifle_SPAR_03_blk_F",
	"arifle_Katiba_F",
	"arifle_Katiba_GL_F",
	"arifle_Katiba_C_F",
	"mmg_02_camo_f",
	"MMG_02_sand_F",
	"MMG_02_black_F",
	"srifle_dmr_06_camo_f",
	"srifle_DMR_06_olive_F",
	"srifle_LRR_F",
	"srifle_LRR_camo_F",
	"srifle_LRR_tna_F",
	"LMG_03_F",
	"BWA3_MG4",
	"BWA3_MG5",
	"BWA3_MG5_Tan",
	"srifle_EBR_F",
	"SMG_05_F",
	"arifle_MX_F",
	"arifle_MX_Black_F",
	"arifle_MX_GL_F",
	"arifle_MX_GL_Black_F",
	"arifle_MX_GL_khk_F",
	"arifle_MX_khk_F",
	"arifle_MX_SW_Black_F",
	"arifle_MX_SW_F",
	"arifle_MX_SW_khk_F",
	"arifle_MXC_F",
	"arifle_MXC_Black_F",
	"arifle_MXC_khk_F",
	"arifle_MXM_F",
	"arifle_MXM_Black_F",
	"arifle_MXM_khk_F",
	"LMG_Zafir_F",
	"srifle_DMR_02_camo_F",
	"srifle_DMR_02_sniper_F",
	"srifle_dmr_02_f",
	"srifle_DMR_07_blk_F",
	"arifle_CTAR_blk_F",
	"arifle_CTAR_GL_blk_F",
	"arifle_CTARS_blk_F",
	"arifle_SDAR_F",
	"SMG_02_F",
	"srifle_DMR_03_multicam_F",
	"srifle_DMR_03_khaki_F",
	"srifle_DMR_03_tan_F",
	"srifle_dmr_03_f",
	"LMG_Mk200_F",
	"arifle_TRG21_F",
	"arifle_TRG21_GL_F",
	"arifle_ARX_blk_F",
	"SMG_01_F",
	"hgun_Pistol_heavy_02_F",
	"hgun_ACPC2_F",
	"BWA3_Fliegerfaust",
	"hgun_Pistol_heavy_01_F",
	"BWA3_MP7",
	"launch_NLAW_F",
	"BWA3_P2A1",
	"BWA3_P8",
	"hgun_P07_F",
	"BWA3_Pzf3",
	"BWA3_RGW90",
	"hgun_Pistol_Signal_F",
	"launch_B_Titan_F",
	"launch_B_Titan_tna_F",
	"launch_B_Titan_short_F",
	"launch_B_Titan_short_tna_F",
	"ACE_VMH3",
	"ACE_VMM3",
	"MineDetector",
	"rhs_weap_m16a4",
	"rhs_weap_m24sws",
	"rhs_weap_m24sws_blk",
	"rhs_weap_m24sws_ghillie",
	"rhs_weap_m32",
	"rhs_weap_m4",
	"rhs_weap_m4_m203",
	"rhs_weap_m4_m203S",
	"rhs_weap_m4_m320",
	"rhs_weap_m4a1_carryhandle",
	"rhs_weap_m4a1_carryhandle_m203",
	"rhs_weap_m4a1_carryhandle_m203S",
	"rhs_weap_M590_8RD",
	"rhs_weap_M590_5RD",
	"rhs_weap_m240B",
	"rhs_weap_fgm148",
	"rhs_weap_fim92",
	"BWA3_CarlGustaf",
	"rhs_weap_M136",
	"rhs_weap_M136_hedp",
	"rhs_weap_M136_hp",
	"rhs_weap_m72a7",
	"rhsusf_weap_glock17g4",
	"rhsusf_weap_m1911a1",
	"rhs_weap_M320",
	"rhsusf_weap_m9",
	"hgun_P07_khk_F",
	"srifle_dmr_05_blk_f",
	"srifle_DMR_03_woodland_F",
	"rhs_weap_XM2010",
	"rhs_weap_XM2010_wd",
	"rhs_weap_XM2010_sa",
	"rhs_weap_XM2010_d",
	"rhs_weap_m27iar",
	"rhs_weap_m14ebrri",
	"rhs_weap_sr25",
	"rhs_weap_sr25_d",
	"rhs_weap_sr25_wd",
	"rhs_weap_mk18",
	"rhs_weap_mk18_d",
	"rhs_weap_mk18_m320",
	"rhs_weap_mk18_wd",
	"rhs_weap_hk416d10",
	"rhs_weap_hk416d10_m320",
	"rhs_weap_hk416d145",
	"rhs_weap_hk416d145_m320",
	"rhs_weap_m16a4_carryhandle",
	"rhs_weap_m16a4_carryhandle_M203",
	"rhs_weap_m4_carryhandle",
	"rhs_weap_m40a5",
	"rhs_weap_m40a5_d",
	"rhs_weap_m40a5_wd",
	"rhs_weap_m4a1_blockII",
	"rhs_weap_m4a1_blockII_M203_d",
	"rhs_weap_m4a1_blockII_M203",
	"rhs_weap_m4a1_blockII_M203_wd",
	"rhs_weap_sr25_ec",
	"rhsusf_weap_MP7A2",
	"rhsusf_weap_MP7A2_desert",
	"rhsusf_weap_MP7A2_winter",
	"rhs_weap_m240G",
	"rhs_weap_m249",
	"rhs_weap_smaw",
	"rhs_weap_smaw_green",
	"rhs_weap_M107",
	"rhs_weap_M107_d",
	"rhs_weap_M107_w"
];

GRLIB_arsenal_magazines = [

];

GRLIB_arsenal_items = [
	"optic_ACO_grn",
	"optic_Aco",
	"optic_ACO_grn_smg",
	"optic_Aco_smg",
	"BWA3_optic_Aimpoint",
	"optic_AMS_khk",
	"optic_AMS_snd",
	"optic_AMS",
	"optic_Arco",
	"optic_Arco_blk_F",
	"optic_DMS",
	"BWA3_optic_EOTech",
	"BWA3_optic_EOTech_tan",
	"BWA3_optic_EOTech_tan_Mag_Off",
	"BWA3_optic_EOTech_Mag_Off",
	"optic_ERCO_khk_F",
	"optic_ERCO_snd_F",
	"optic_ERCO_blk_F",
	"BWA3_optic_G36C_Ironsight_100",
	"optic_KHS_tan",
	"optic_KHS_blk",
	"ACE_acc_pointer_green",
	"acc_pointer_IR",
	"BWA3_acc_VarioRay_irlaser",
	"BWA3_acc_LLM01_irlaser",
	"BWA3_acc_LLM01_irlaser_underbarrel",
	"optic_LRPS",
	"optic_LRPS_tna_F",
	"ACE_muzzle_mzls_338",
	"ACE_muzzle_mzls_smg_01",
	"ACE_muzzle_mzls_L",
	"ACE_muzzle_mzls_H",
	"ACE_muzzle_mzls_B",
	"ACE_muzzle_mzls_smg_02",
	"ACE_muzzle_mzls_93mmg",
	"optic_Holosight",
	"optic_Holosight_smg",
	"optic_Holosight_khk_F",
	"optic_Holosight_blk_F",
	"optic_Holosight_smg_blk_F",
	"optic_SOS",
	"optic_SOS_khk_F",
	"optic_MRCO",
	"optic_MRD",
	"BWA3_optic_NSA80",
	"optic_Hamr",
	"optic_Hamr_khk_F",
	"BWA3_optic_RSAS",
	"muzzle_snds_338_green",
	"muzzle_snds_338_sand",
	"muzzle_snds_338_black",
	"muzzle_snds_acp",
	"muzzle_snds_M",
	"muzzle_snds_m_khk_F",
	"muzzle_snds_m_snd_F",
	"muzzle_snds_58_blk_F",
	"muzzle_snds_H",
	"muzzle_snds_H_khk_F",
	"muzzle_snds_H_snd_F",
	"muzzle_snds_B",
	"muzzle_snds_B_khk_F",
	"muzzle_snds_B_snd_F",
	"muzzle_snds_L",
	"muzzle_snds_93mmg",
	"BWA3_muzzle_snds_MP7",
	"BWA3_muzzle_snds_G36",
	"BWA3_muzzle_snds_G28",
	"BWA3_optic_20x50",
	"BWA3_optic_Shortdot",
	"muzzle_snds_65_TI_blk_F",
	"acc_flashlight",
	"optic_Yorris",
	"BWA3_optic_24x72",
	"BWA3_optic_ZO4x30_Single",
	"BWA3_optic_ZO4x30",
	"bipod_01_F_khk",
	"bipod_01_F_mtp",
	"bipod_01_F_snd",
	"bipod_01_F_blk",
	"U_B_CTRG_3",
	"U_B_CTRG_1",
	"U_B_CTRG_2",
	"U_B_CTRG_Soldier_urb_1_F",
	"U_B_CTRG_Soldier_urb_3_F",
	"U_B_CTRG_Soldier_urb_2_F",
	"U_B_CTRG_Soldier_F",
	"U_B_CTRG_Soldier_3_F",
	"U_B_CTRG_Soldier_2_F",
	"U_B_T_Sniper_F",
	"U_B_GhillieSuit",
	"U_B_HeliPilotCoveralls",
	"BWA3_Uniform_idz_Fleck",
	"BWA3_Uniform3_idz_Fleck",
	"BWA3_Uniform2_idz_Fleck",
	"BWA3_Uniform_idz_Tropen",
	"BWA3_Uniform3_idz_Tropen",
	"BWA3_Uniform2_idz_Tropen",
	"BWA3_Uniform_Ghillie_idz_Fleck",
	"BWA3_Uniform_Ghillie_idz_Tropen",
	"U_B_CombatUniform_mcam",
	"U_B_CombatUniform_mcam_tshirt",
	"U_B_T_Soldier_F",
	"U_B_T_Soldier_AR_F",
	"U_B_T_FullGhillie_tna_F",
	"BWA3_Uniform_Crew_Fleck",
	"BWA3_Uniform_Helipilot",
	"BWA3_Uniform_Crew_Tropen",
	"U_B_PilotCoveralls",
	"U_B_CombatUniform_mcam_vest",
	"U_B_T_Soldier_SL_F",
	"U_B_Wetsuit",
	"U_B_FullGhillie_lsh",
	"U_B_FullGhillie_sard",
	"U_B_FullGhillie_ard",
	"V_Chestrig_rgr",
	"V_Chestrig_khk",
	"V_Chestrig_oli",
	"V_Chestrig_blk",
	"V_PlateCarrierL_CTRG",
	"V_PlateCarrierH_CTRG",
	"V_PlateCarrierIAGL_oli",
	"V_PlateCarrierGL_rgr",
	"V_PlateCarrierGL_blk",
	"BWA3_Vest_Fleck",
	"BWA3_Vest_Grenadier_Fleck",
	"BWA3_Vest_Leader_Fleck",
	"BWA3_Vest_Marksman_Fleck",
	"BWA3_Vest_Autorifleman_Fleck",
	"BWA3_Vest_Medic_Fleck",
	"BWA3_Vest_Rifleman1_Fleck",
	"BWA3_Vest_Tropen",
	"BWA3_Vest_Grenadier_Tropen",
	"BWA3_Vest_Leader_Tropen",
	"BWA3_Vest_Marksman_Tropen",
	"BWA3_Vest_Autorifleman_Tropen",
	"BWA3_Vest_Medic_Tropen",
	"BWA3_Vest_Rifleman1_Tropen",
	"V_PlateCarrier1_rgr",
	"V_PlateCarrier1_blk",
	"V_BandollierB_cbr",
	"V_BandollierB_rgr",
	"V_BandollierB_khk",
	"V_BandollierB_oli",
	"V_BandollierB_blk",
	"V_TacVestIR_blk",
	"V_PlateCarrierSpec_rgr",
	"V_TacVest_brn",
	"V_TacVest_khk",
	"V_TacVest_oli",
	"V_TacVest_blk",
	"V_TacVest_camo",
	"V_TacChestrig_grn_F",
	"V_TacChestrig_cbr_F",
	"V_TacChestrig_oli_F",
	"V_RebreatherB",
	"V_PlateCarrierGL_mtp",
	"V_PlateCarrier1_rgr_noflag_F",
	"V_PlateCarrier1_tna_F",
	"V_PlateCarrierSpec_mtp",
	"V_PlateCarrierSpec_blk",
	"V_PlateCarrier2_rgr_noflag_F",
	"V_PlateCarrier2_tna_F",
	"V_PlateCarrierGL_tna_F",
	"V_PlateCarrierSpec_tna_F",
	"V_PlateCarrier2_rgr",
	"V_PlateCarrier2_blk",
	"G_Bandanna_beast",
	"G_Bandanna_tan",
	"G_Bandanna_khk",
	"G_Bandanna_oli",
	"H_Bandanna_sand",
	"G_Bandanna_blk",
	"H_Bandanna_gry",
	"H_Bandanna_camo",
	"BWA3_Beret_Falli",
	"BWA3_Beret_HFlieger",
	"BWA3_Beret_Jaeger",
	"BWA3_Beret_PzAufkl",
	"BWA3_Beret_PzGren",
	"BWA3_Beret_Pz",
	"BWA3_Beret_Wach_Blau",
	"BWA3_Beret_Wach_Gruen",
	"H_Beret_02",
	"H_Beret_Colonel",
	"H_Watchcap_cbr",
	"H_Watchcap_camo",
	"H_Watchcap_blk",
	"H_Watchcap_khk",
	"BWA3_Booniehat_Fleck",
	"H_Booniehat_khk",
	"H_Booniehat_mcamo",
	"H_Booniehat_oli",
	"H_Booniehat_tan",
	"BWA3_Booniehat_Tropen",
	"BWA3_G_Combat_Clear",
	"BWA3_G_Combat_Orange",
	"BWA3_G_Combat_Black",
	"H_HelmetCrew_B",
	"BWA3_CrewmanKSK_Fleck_Headset",
	"BWA3_CrewmanKSK_Fleck",
	"BWA3_CrewmanKSK_Schwarz_Headset",
	"BWA3_CrewmanKSK_Schwarz",
	"BWA3_CrewmanKSK_Tropen_Headset",
	"BWA3_CrewmanKSK_Tropen",
	"G_Aviator",
	"BWA3_M92_Fleck",
	"BWA3_M92_Tropen",
	"G_Spectacles",
	"G_Spectacles_Tinted",
	"H_CrewHelmetHeli_B",
	"H_PilotHelmetHeli_B",
	"G_Combat",
	"G_Combat_Goggles_tna_F",
	"H_HelmetB",
	"H_HelmetB_camo",
	"H_HelmetB_grass",
	"H_HelmetB_sand",
	"H_HelmetB_snakeskin",
	"H_HelmetB_black",
	"H_HelmetB_tna_F",
	"H_HelmetB_desert",
	"BWA3_Knighthelm",
	"H_Bandanna_cbr",
	"H_Bandanna_khk",
	"H_Bandanna_mcamo",
	"H_HelmetB_light",
	"H_HelmetB_light_grass",
	"H_HelmetB_light_sand",
	"H_HelmetB_light_snakeskin",
	"H_HelmetB_light_black",
	"H_HelmetB_Light_tna_F",
	"H_HelmetB_light_desert",
	"H_Cap_grn",
	"H_Cap_tan",
	"H_Cap_oli",
	"H_Cap_blk",
	"H_Cap_khaki_specops_UK",
	"H_Cap_tan_specops_US",
	"H_Cap_usblack",
	"H_MilCap_mcamo",
	"H_MilCap_tna_F",
	"BWA3_OpsCore_Fleck_Camera",
	"BWA3_OpsCore_Fleck",
	"BWA3_OpsCore_Schwarz_Camera",
	"BWA3_OpsCore_Schwarz",
	"BWA3_OpsCore_Tropen_Camera",
	"BWA3_OpsCore_Tropen",
	"H_PilotHelmetFighter_B",
	"G_Squares",
	"G_Squares_Tinted",
	"H_ShemagOpen_khk",
	"H_ShemagOpen_tan",
	"H_Shemag_olive",
	"G_Shades_Blue",
	"G_Shades_Green",
	"G_Shades_Red",
	"G_Shades_Black",
	"G_Balaclava_combat",
	"G_Balaclava_lowprofile",
	"G_Balaclava_oli",
	"G_Balaclava_blk",
	"G_Tactical_Clear",
	"G_Tactical_Black",
	"H_HelmetB_TI_tna_F",
	"G_Balaclava_TI_tna_F",
	"G_Balaclava_TI_G_tna_F",
	"G_Balaclava_TI_blk_F",
	"G_Balaclava_TI_G_blk_F",
	"H_Booniehat_tna_F",
	"G_B_Diving",
	"H_HelmetSpecB",
	"H_HelmetSpecB_paint1",
	"H_HelmetSpecB_sand",
	"H_HelmetSpecB_snakeskin",
	"H_HelmetSpecB_blk",
	"H_HelmetB_Enh_tna_F",
	"H_HelmetSpecB_paint2",
	"G_Sport_Red",
	"G_Sport_Blackyellow",
	"G_Sport_BlackWhite",
	"G_Sport_Checkered",
	"G_Sport_Blackred",
	"G_Sport_Greenblack",
	"ACE_RangeTable_82mm",
	"ACE_adenosine",
	"ACRE_PRC117F",
	"ACRE_PRC148",
	"ACRE_PRC152",
	"ACRE_PRC343",
	"ACRE_PRC77",
	"ACRE_SEM52SL",
	"ACE_ATragMX",
	"ACE_atropine",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_SpraypaintBlue",
	"ACE_bloodIV",
	"ACE_bloodIV_250",
	"ACE_bloodIV_500",
	"ACE_DAGR",
	"ACE_wirecutter",
	"Rangefinder",
	"ACE_RangeCard",
	"ACE_DefusalKit",
	"ACE_epinephrine",
	"Binocular",
	"ACE_Flashlight_MX991",
	"ItemGPS",
	"ACE_SpraypaintGreen",
	"ACE_Altimeter",
	"ACE_HuntIR_monitor",
	"ACE_IR_Strobe_Item",
	"BWA3_optic_IRV600",
	"ACE_CableTie",
	"ItemMap",
	"ACE_MapTools",
	"ACE_Kestrel4500",
	"ACE_salineIV",
	"ACE_salineIV_250",
	"ACE_salineIV_500",
	"ItemCompass",
	"ACE_Flashlight_KSF1",
	"Laserdesignator_01_khk_F",
	"Laserdesignator",
	"ACE_bodyBag",
	"ACE_M26_Clacker",
	"ACE_Clacker",
	"ACE_Flashlight_XL50",
	"ACE_microDAGR",
	"ACE_Cellphone",
	"ACE_morphine",
	"ACE_packingBandage",
	"ACE_MX2A",
	"NVGoggles_tna_F",
	"BWA3_ItemNaviPad",
	"NVGoggles",
	"NVGoggles_INDEP",
	"NVGoggles_OPFOR",
	"BWA3_optic_NSV600",
	"BWA3_optic_NSV80",
	"ACE_EarPlugs",
	"ACE_surgicalKit",
	"ACE_personalAidKit",
	"ACE_plasmaIV",
	"ACE_plasmaIV_250",
	"ACE_plasmaIV_500",
	"ACE_SpraypaintRed",
	"ACE_Sandbag_empty",
	"ACE_EntrenchingTool",
	"ACE_Tripod",
	"ACE_SpraypaintBlack",
	"ACE_SpottingScope",
	"ACE_DeadManSwitch",
	"ACE_tourniquet",
	"ACE_UAVBattery",
	"B_UavTerminal",
	"ItemWatch",
	"ACE_VectorDay",
	"ACE_Vector",
	"BWA3_Vector",
	"ACE_quikclot",
	"ToolKit",
	"ACE_Yardage450",
	"rhsusf_acc_ACOG",
	"rhsusf_acc_ACOG2",
	"rhsusf_acc_ACOG2_USMC",
	"rhsusf_acc_ACOG3",
	"rhsusf_acc_ACOG3_USMC",
	"rhsusf_acc_ACOG_MDO",
	"rhsusf_acc_ACOG_RMR",
	"rhsusf_acc_ACOG_USMC",
	"rhsusf_acc_ACOG_anpvs27",
	"rhsusf_acc_ACOG_d",
	"rhsusf_acc_ACOG_wd",
	"rhsusf_acc_ARDEC_M240",
	"rhsusf_acc_ELCAN",
	"rhsusf_acc_ELCAN_ard",
	"rhsusf_acc_EOTECH",
	"rhsusf_acc_LEUPOLDMK4",
	"rhsusf_acc_LEUPOLDMK4_2",
	"rhsusf_acc_LEUPOLDMK4_2_d",
	"rhsusf_acc_M2010S",
	"rhsusf_acc_M2A1",
	"rhsusf_acc_M8541",
	"rhsusf_acc_M8541_low",
	"rhsusf_acc_M8541_low_d",
	"rhsusf_acc_M8541_low_wd",
	"rhsusf_acc_M952V",
	"rhsusf_acc_SF3P556",
	"rhsusf_acc_SFMB556",
	"rhsusf_acc_SR25S",
	"rhsusf_acc_SpecterDR",
	"rhsusf_acc_SpecterDR_A",
	"rhsusf_acc_SpecterDR_D",
	"rhsusf_acc_SpecterDR_OD",
	"rhsusf_acc_anpas13gv1",
	"rhsusf_acc_anpeq15",
	"rhsusf_acc_anpeq15A",
	"rhsusf_acc_anpeq15_bk",
	"rhsusf_acc_anpeq15_bk_light",
	"rhsusf_acc_anpeq15_bk_top",
	"rhsusf_acc_anpeq15_light",
	"rhsusf_acc_anpeq15_top",
	"rhsusf_acc_anpeq15_wmx",
	"rhsusf_acc_anpeq15_wmx_light",
	"rhsusf_acc_anpeq15side",
	"rhsusf_acc_anpeq15side_bk",
	"rhsusf_acc_anpvs27",
	"rhsusf_acc_compm4",
	"rhsusf_acc_eotech_552",
	"rhsusf_acc_eotech_552_d",
	"rhsusf_acc_eotech_xps3",
	"rhsusf_acc_grip1",
	"rhsusf_acc_grip2",
	"rhsusf_acc_grip2_tan",
	"rhsusf_acc_grip3",
	"rhsusf_acc_grip3_tan",
	"rhsusf_acc_grip4",
	"rhsusf_acc_harris_bipod",
	"rhsusf_acc_harris_swivel",
	"rhsusf_acc_muzzleFlash_SF3P556",
	"rhsusf_acc_muzzleFlash_SFMB556",
	"rhsusf_acc_muzzleFlash_ardec_m240",
	"rhsusf_acc_nt4_black",
	"rhsusf_acc_nt4_tan",
	"rhsusf_acc_omega9k",
	"rhsusf_acc_premier",
	"rhsusf_acc_premier_anpvs27",
	"rhsusf_acc_premier_low",
	"rhsusf_acc_rotex5_grey",
	"rhsusf_acc_rotex5_tan",
	"rhsusf_acc_rotex_mp7",
	"rhsusf_acc_rotex_mp7_aor1",
	"rhsusf_acc_rotex_mp7_desert",
	"rhsusf_acc_rotex_mp7_winter",
	"rhsusf_acc_wmx",
	"rhs_uniform_cu_ocp",
	"rhs_uniform_cu_ucp",
	"rhs_uniform_FROG01_d",
	"rhs_uniform_FROG01_wd",
	"rhsusf_iotv_ocp_Grenadier",
	"rhsusf_iotv_ucp_Grenadier",
	"rhsusf_iotv_ocp_Medic",
	"rhsusf_iotv_ucp_Medic",
	"rhsusf_iotv_ocp",
	"rhsusf_iotv_ocp_Repair",
	"rhsusf_iotv_ucp_Repair",
	"rhsusf_iotv_ocp_Rifleman",
	"rhsusf_iotv_ucp_Rifleman",
	"rhsusf_iotv_ocp_SAW",
	"rhsusf_iotv_ucp_SAW",
	"rhsusf_iotv_ocp_Squadleader",
	"rhsusf_iotv_ucp_Squadleader",
	"rhsusf_iotv_ocp_Teamleader",
	"rhsusf_iotv_ucp_Teamleader",
	"rhsusf_iotv_ucp",
	"rhsusf_spc",
	"rhsusf_spc_corpsman",
	"rhsusf_spc_crewman",
	"rhsusf_spc_iar",
	"rhsusf_spc_light",
	"rhsusf_spc_mg",
	"rhsusf_spc_marksman",
	"rhsusf_spc_rifleman",
	"rhsusf_spc_squadleader",
	"rhsusf_spc_teamleader",
	"rhsusf_ach_helmet_ocp",
	"rhsusf_ach_helmet_ucp",
	"rhs_booniehat2_marpatd",
	"rhs_booniehat2_marpatwd",
	"rhs_Booniehat_ocp",
	"rhs_Booniehat_ucp",
	"rhsusf_mich_helmet_marpatd",
	"rhsusf_mich_helmet_marpatwd",
	"rhsusf_patrolcap_ocp",
	"rhsusf_patrolcap_ucp",
	"rhs_8point_marpatd",
	"rhs_8point_marpatwd",
	"rhsusf_mich_bare",
	"rhsusf_mich_bare_tan",
	"Leupold_Mk4",
	"ACE_NVG_Wide",
	"ACE_optic_Hamr_PIP",
	"muzzle_snds_93mmg_tan",
	"bipod_02_F_tan",
	"bipod_03_F_oli",
	"muzzle_snds_H_MG",
	"muzzle_snds_H_MG_blk_F",
	"muzzle_snds_H_MG_khk_F",
	"rhs_weap_optic_smaw",
	"rhs_uniform_g3_m81",
	"rhsusf_ach_helmet_M81",
	"rhs_Booniehat_m81",
	"rhs_uniform_g3_mc",
	"rhsusf_opscore_mc_cover",
	"rhs_uniform_g3_rgr",
	"rhsusf_opscore_rg_cover",
	"rhsusf_opscore_mar_fg_pelt",
	"rhsusf_opscore_mar_ut_pelt",
	"rhsusf_spc_patchless",
	"rhsusf_spc_patchless_radio",
	"V_DeckCrew_blue_F",
	"V_DeckCrew_brown_F",
	"V_DeckCrew_yellow_F",
	"V_DeckCrew_green_F",
	"V_DeckCrew_red_F",
	"V_DeckCrew_violet_F",
	"V_DeckCrew_white_F",
	"BWA3_Vest_JPC_Radioman_Fleck",
	"BWA3_Vest_JPC_Leader_Fleck",
	"BWA3_Vest_JPC_Rifleman_Fleck",
	"BWA3_Vest_JPC_Radioman_Tropen",
	"BWA3_Vest_JPC_Leader_Tropen",
	"BWA3_Vest_JPC_Rifleman_Tropen"
];

GRLIB_arsenal_backpacks = [
	"B_AssaultPack_cbr",
	"BWA3_AssaultPack_Fleck",
	"B_AssaultPack_rgr",
	"B_AssaultPack_khk",
	"B_AssaultPack_mcamo",
	"B_AssaultPack_blk",
	"BWA3_AssaultPack_Tropen",
	"B_AssaultPack_tna_F",
	"B_Bergen_mcamo_F",
	"B_Bergen_tna_F",
	"B_FieldPack_cbr",
	"BWA3_FieldPack_Fleck",
	"B_FieldPack_khk",
	"B_FieldPack_oli",
	"B_FieldPack_blk",
	"BWA3_FieldPack_Tropen",
	"B_Static_Designator_01_weapon_F",
	"B_Carryall_cbr",
	"BWA3_Carryall_Fleck",
	"B_Carryall_khk",
	"B_Carryall_mcamo",
	"B_Carryall_oli",
	"BWA3_Carryall_Tropen",
	"BWA3_PatrolPack_Fleck",
	"BWA3_PatrolPack_Tropen",
	"B_Kitbag_cbr",
	"BWA3_Kitbag_Fleck",
	"BWA3_Kitbag_Fleck_Medic",
	"B_Kitbag_rgr",
	"B_Kitbag_mcamo",
	"BWA3_Kitbag_Tropen",
	"BWA3_Kitbag_Tropen_Medic",
	"B_Parachute",
	"BWA3_TacticalPack_Fleck",
	"BWA3_TacticalPack_Fleck_Medic",
	"B_TacticalPack_rgr",
	"B_TacticalPack_mcamo",
	"B_TacticalPack_oli",
	"B_TacticalPack_blk",
	"BWA3_TacticalPack_Tropen",
	"BWA3_TacticalPack_Tropen_Medic",
	"ACE_TacticalLadder_Pack",
	"B_UAV_01_backpack_F",
	"ACE_NonSteerableParachute",
	"ace_gunbag",
	"ace_gunbag_Tan",
	"rhsusf_assault_eagleaiii_coy",
	"rhsusf_assault_eagleaiii_ocp",
	"rhsusf_assault_eagleaiii_ucp",
	"rhsusf_falconii_coy",
	"rhsusf_falconii_mc",
	"rhsusf_falconii",
	"B_rhsusf_B_BACKPACK"
];

RPT File:
https://drive.google.com/drive/folders/1-4ze2PfCt_eiDY5O3w2hPa-24gpVVe3P

**Comment by Dorbedo** [comment]
For obvious reasons, you have to add the backpack radios as backpacks and the handhelds as items.
Your list (btw. it's annoying to scroll to infinity) doesn't contain any TFAR items.

Just remember to add the default radio classes (without the unique ID):
For version 0.9.12 this is for example: `"tf_anprc152"` or `"tf_rt1523g_sage"`
