### ISSUE TITLE
TFR radio in-game stays on when I press CapsLk

### ISSUE THREAD

**Issue by RykerDemonic** [michail-nikolaev/task-force-arma-3-radio#1396]
Arma 3 - v1.80

TFAR - v0.9.12

CBA - v3.6.1

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- When I use the Radio to talk to people with Caps Lock is keeps my radio on even after I release the button this happens to me on any server I join. I have tried to remove the Base Arma 3 Push to talk button to nothing and the problem still persists. the only way i found to fix this is to change the SW radio key but even when I remove the key and add a new key Caps Lock still activates the radio and keeps it on but the button I set it to works perfectly fine but when im in Zeus mode i cant use the custom key I set up.

**Steps to reproduce:**
  - not sure if this will happen to others but it happens to me everytime.
   1. Join a server with TFR
   2. Use Caps Lock to talk
   3. Radio stays on

**Where did the issue occur?**
- Dedicated MilSim server, Arma 3 RP servers, any server that uses TFR

**RPT log file:**
- Game does not crash or get an error at all just radio stays on.

**Comment by dedmen** [comment]
`Most recent stable version of Arma 3, TFR, CBA` That's invalid. 
For one the mod is called TFAR. Second please list version numbers.

**Comment by coachwn** [comment]
I believe that was a CBA issue with the 0.9.12 version and after we as a community moved to the Beta version last year it went away.

**Comment by dedmen** [comment]
Oh didn't see the post was edited. I closed it because it was invalid ^^
Yeah. Fixed in 1.0.
