### ISSUE TITLE
TFAR Zeus issues

### ISSUE THREAD

**Issue by ComradeWolf2023** [michail-nikolaev/task-force-arma-3-radio#1401]
**Arma 3 Version:** `1.82` 
**CBA Version:** `3.6.1`
**Task Force Radio Version:** `Most current steam version. Last updated in March

**Mods:**
```
- @CBA_A3
- @task_force_radio
- @ACE
@ACEX
@RHSISAF RHSARFR RHSGREF RHSSAF
```
**Description:**
Unable to hear players when remote controlling AI's

**Where did the issue occur?**
- Dedicated multiplayer and self hosted

**RPT log file:**
- https://pastebin.com/052dA3YA

**Comment by ComradeWolf2023** [comment]
Ah that makes sense. Is the 1.0 version going to be uploaded to steam? Or is there a work around until it gets uploaded to steam? I've never had very good luck getting people to manually update mods in my unit.

**Comment by Dorbedo** [comment]
A beta version can already be found on the steam workshop.
