### ISSUE TITLE
Unable to pack TFAR pbo's

### ISSUE THREAD

**Issue by BlackFisch** [michail-nikolaev/task-force-arma-3-radio#1407]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1.180131` (stable)
**Task Force Radio Version:** `1.0` (dev commit 1347)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- I'm currently unable to pack both backpacks and handhelds addons for the newest TFAR version, always getting the same error 'missing files'. I already checked the mentioned files twice for errors and/or missing textures. All that was changed on the addon should be the ranges of the handheld radios.

**Steps to reproduce:**
- Open PBOProject and try to pack it

**Where did the issue occur?**
- On a local machine, trying to pack the pbos with edited ranges

**Mikeros Dos Tools log file:**
- https://gist.github.com/BlackFisch/8a789e00a959196dd179820156e96753

**Comment by dedmen** [comment]
Disable Mikeros missing files check.

**Comment by BlackFisch** [comment]
where can I disable that? Sorry, I just can't find it... https://i.imgur.com/cPFwYCQ.png

Or do I have to run the MakeFile.exe directly with `-N wyswig` parameter or sth?

**Comment by BlackFisch** [comment]
okay :) That was my bad then ^^ 
Thank You!
