### ISSUE TITLE
Successful packing of PBO's not possible

### ISSUE THREAD

**Issue by BlackFisch** [michail-nikolaev/task-force-arma-3-radio#1408]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1.180131` (stable / dev + commit hash)
**Task Force Radio Version:** `1.0` (dev 48011a554d744ca74fe432f80f7baa857b5c8626)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- After packing the files as provided in the repository with the included python script, the server and client crashes with the same error (see below). Half an hour I still wasnt able to find an error.

**Where did the issue occur?**
- Dedicated + Client

**RPT log file:**
`23:45:08 ErrorMessage: File z\tfar\addons\backpacks\anarc164\ui\anarc164.ext, line 74: Config: End of line encountered after 
23:45:08 Application terminated intentionally
ErrorMessage: File z\tfar\addons\backpacks\anarc164\ui\anarc164.ext, line 74: Config: End of line encountered after `

**Comment by dedmen** [comment]
You didn't enable binarization.

**Comment by BlackFisch** [comment]
I used build.py when getting the error

**Comment by BlackFisch** [comment]
okay, i got it working for now. my problems were a missing registry key, wrong pboproject settings and some other stupid mistakes of myself (like an outdated python version)... sorry for that and thanks again :D
