### ISSUE TITLE
custom keybinds

### ISSUE THREAD

**Issue by Diesel-160th** [michail-nikolaev/task-force-arma-3-radio#1410]
Arma 3 Version: 1.82 (stable ) CBA Version: 3.7.0 (stable ) Task Force Radio Version: 0.9.12 (stable )

Mods:

- @CBA_A3
- @task_force_radio
- RHS
- ACE
- Ares
- SMA
Description:
when using custom keybinds for transmitting, tfar is constantly transmitting on the wrong net.

EG. I have f1 through f4 keys set for sw,sw alt, LR, LR alt. if I try to transmit on LR being F3 it will almost always transmit over SW which is bound to F1.

this seems to have been a common issue within my community though others are using different keybinds for transmitting

Steps to reproduce:
rebind transmit keys, in combat environment with people talking to you on both short and long range, attempt to talk to each one after another ( a slight pause between each net)
using an-prc152 and rt-1523g

Add the steps needed to reproduce the issue.
on foot or in vehicle as above

Dedicated 

RPT log file: https://pastebin.com/U0G7aDKF

**Comment by dedmen** [comment]
Please use and fill out the issue template. https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Diesel-160th** [comment]
updated

**Comment by dedmen** [comment]
Known bug in 0.9.12. Already fixed in 1.0.
