### ISSUE TITLE
Not Compatible With TS Update 3.1.9 (Latest)

### ISSUE THREAD

**Issue by Vegas** [michail-nikolaev/task-force-arma-3-radio#1412]
Teamspeak rolled out their 3.1.9 version update today. This breaks TFAR plugins for version 0.9.12.

Anybody got a patch?

**Comment by dedmen** [comment]
That's incorrect. The new version doesn't require a new API version.
Use the 3.1 compatible plugin which btw was also required for the previous couple versions.
