### ISSUE TITLE
TS pipeline closed

### ISSUE THREAD

**Issue by topdog13590** [michail-nikolaev/task-force-arma-3-radio#1421]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)
**Task Force Radio Version:** `0.9.12` (stable / dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
-Me and my friend are in the same teamspeak server and both of are on my server and we both have the plugin installed but for him it says Ts pipline closed 

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by dedmen** [comment]
Try running TS/Arma/Both as Administrator. If that doesn't work then I don't know. But is fixed in 1.0
