### ISSUE TITLE
Hello juste question

### ISSUE THREAD

**Issue by BadySmith** [michail-nikolaev/task-force-arma-3-radio#1428]
TaskForceRadio is compatible for new version TeamSpeak ? (TeamSpeak 5)

**Comment by dedmen** [comment]
This is a issue tracker. Not a question asking place.
How is TFAR supposed to be compatible with something that doesn't exist? Tell me that.

**Comment by Fusselwurm** [comment]
context:

https://www.nexteamspeak.de/blogbeitrag,95,teamspeak-5-0-alles-neu-und-irgendwie-doch-nicht.html

It seems there'll be a "TeamSpeak 5" by end of year.

@BadySmith there's virtually no information on this yet. As it is a new major version though (and devs are promising us it will be the best thing ever), you have to assume current TFAR wont be compatible with it.

**Comment by LaocheXe** [comment]
https://www.teamspeak.com/en/your-download#ts5
