### ISSUE TITLE
blocks targeting and gun stabilization

### ISSUE THREAD

**Issue by duden** [michail-nikolaev/task-force-arma-3-radio#1431]
**Arma 3 Version:** `1.82.144710` (stable)
**CBA Version:** `3.7.1.180604` 
**Task Force Radio Version:** `Steam Beta Build (Pre-release 278, i guess)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
Blocks standard targeting Key and gun stabilization even if no additional channel is set. 

**Steps to reproduce:**
-take control over a drone
-try to stabilize the vision (preferable on a moving target)

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer

**Comment by Dorbedo** [comment]
Does this still occur, if you change your keys?

**Comment by duden** [comment]
> Does this still occur, if you change your keys?
@Dorbedo if change the keys the error doesnt persist.

> What is "gun stabilization" ?
gun stabilization is the Arma Feature to look your Turret onto moving targets. For example with the standard drone onto a moving ifrit like in this  [example](https://youtu.be/9p8rvur4BWI?t=12m36sl).

> Meaning it should work if additional channel is set and transmitting via it works.
yes it works if an additional channel is set and transmitting works, thats what confused me in the first place.
