### ISSUE TITLE
TFAR - Force Usage won't work if the password is empty

### ISSUE THREAD

**Issue by Guy-Markman** [michail-nikolaev/task-force-arma-3-radio#1432]
**Arma 3 Version:** Stable
**CBA Version:** Stable
**Task Force Radio Version:** Stable

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
When setting up the model TFAR - Force Usage, if you keep the password part empty, the model won't work at all. It won't move you to the indicated channel in Channel Name empty and won't mute dead players. 

**Steps to reproduce:**
- Put the model in the editor.
- Keep the Channel name with the name of the room you want the players to move to.
- Clean the password part empty (because the channel don't have any password).
- Start the mission.
- Open Issue on Github

**Where did the issue occur?**
-  Self-Hosted Multiplayer

**Comment by Dorbedo** [comment]
It's by design.

**Comment by dedmen** [comment]
>Arma 3 Version: Stable

Invalid.
>CBA Version: Stable

Invalid.

>Task Force Radio Version: Stable

Invalid.

>When setting up the model TFAR - Force Usage

Never heard of a model with that name. We generally only have Radio and backpack models.

>Clean the password part empty (because the channel don't have any password).

Doesn't matter. You can also write a password in there as a dummy.

>Open Issue on Github

NO! DON'T DO THAT TO REPRODUCE!

Don't spam full RPT's into the comments. You are supposed to attach a file.
