### ISSUE TITLE
Task force radio, No task force radio deployed onto server

### ISSUE THREAD

**Issue by STAYoFROSTY** [michail-nikolaev/task-force-arma-3-radio#1433]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** `x.x.x` (stable / dev + commit hash)

**Mods:**
```
@CBA_A3;@task_force_radio;@Achilles;@Advanced Rappelling;@Advanced Urban Rappelling;@Enhanced Movement;@FFAA MOD;@NATO_Rus_Vehicle;@RHSAFRF;@RHSGREF;@RHSSAF;@RHSUSAF;@ace;@ACE 3 Extension (Animations and Actions);@ACE 3 Extension (Placeables);@ACE Compat - RHS Armed Forces of the Russian Federation;@ACE Compat - RHS- GREF;@ACE Compat - RHS United States Armed Forces;@CUP Terrains - Core;@CUP Terrains - Maps;@CUP Units;@CUP Vehicles;@CUP Weapons;
```
**Description:**
- Im trying to setup TFAR for Antistasi Altis. When you join the sever you get moved into the dedicated TS channel, but then it says "No task force radio deployed onto server". After that proximty Voip works perfect, but radio's dont at all. When a radio is in you inventory, and you press ALT-P literally nothing happens, aswell as pressing caps lock. I've tried changing the binds around but still nothing. 

**Steps to reproduce:**
- Literally just joining the server

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- https://pastebin.com/F1EQ4PPg

**Comment by 654wak654** [comment]
The quotes around your `-mod=` line are wrong, so the server isn't loading any of those mods. You should wrap the whole thing inside one quote, but you immidiately escape it. You should get rid of the second quote after `=`, and obviously delete one of the quotes at the end of the mod line too.

**Comment by STAYoFROSTY** [comment]
Dude thank you so much! This is my first dedicated server and have now ironed out all the issues i've had with it, the remaining one now the radio's are working is when you press the radio transmission (capslock) it works, but makes no noise

**Comment by dedmen** [comment]
`Arma 3 Version: x.xx (stable / rc / dev)` invalid
`CBA Version: 3.x.x (stable / dev + commit hash)` invalid
`Task Force Radio Version: x.x.x (stable / dev + commit hash)` invalid.

You know... We don't ask for these things just for fun...
