### ISSUE TITLE
TS3 3.2.x Freeze when TFAR plugin is enabled

### ISSUE THREAD

**Issue by pablodma** [michail-nikolaev/task-force-arma-3-radio#1437]
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `3.x.x` (stable)
**Task Force Radio Version:** `1.-1.0.298` (stable / dev + commit hash)
**TS3 Version:** `3.2.1`

**Mods:**
```
- @CBA_A3
- @task_force_radio
- @ACE3
```
**Description:**
- TS3 crashes after couple minutes of being playing arma 3

**Steps to reproduce:**
- Enable TFAR and Wait

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- [Pastebin](https://pastebin.com/jMXXEdCm)).

**Comment by pablodma** [comment]
https://pastebin.com/jMXXEdCm
TS3 logs

**Comment by Dorbedo** [comment]
ACRE seems to have some issues with 3.2 too.
I would advice not to upgrade to 3.2 for now until the issues are examined.

Ref:
https://github.com/IDI-Systems/acre2/issues/567
https://github.com/IDI-Systems/acre2/issues/568

**Comment by ImplicitDeny** [comment]
I would like to point out the fact that the issue is happening very randomly. Yesterday evening, we had a very radio intensive game, where a friend of mine was crashing every 5mn approximately, whereas myself crashed only two times in the whole game. This might be as well unrelated to TFAR or ACRE.

**Comment by dedmen** [comment]
>This might be as well unrelated to TFAR or ACRE

Yeah think so too. Even the fact that TFAR and ACRE have the same issue. Chances are low that we are both making the same mistake by accident.

**Comment by pietronas95** [comment]
I'm having the same problem even without running Arma3, is this going to get fixed?
TS3: 3.2.1
I temporarily resolved unistalling TFAR plugin from ts3...

**Comment by hamiltong34** [comment]
this has solved my problem, thanks very much

**Comment by dedmen** [comment]
@pietronas95 not my bug. I cannot fix Teamspeak being broken.
You can downgrade your TS client to 3.1.10.

**Comment by pietronas95** [comment]
I know @dedmen but the problem is that at the moment TFAR plugin is in some way in conflict with the new version of ts.

**Comment by jokoho48** [comment]
@pietronas95 as far as it currently looks like it is not TFAR or ACRE because both have the same issue. it looks more like a general issue with Teamspeak. I also heard that other plugins also have problems.

**Comment by ColdEvul** [comment]
Some members in my community is experiencing a CTD issue after updating to the latest version of TS.

Here is a older version of TS in case you upgraded and don\t know how to downgrade.
http://dl.4players.de/ts/releases/3.1.10/

**Comment by JABirchall** [comment]
+1, TFR is causing teamspeak 3.2.* to crash

**Comment by tonyrodrigues** [comment]
Downgrade to 3.1.10, maybe solve.
http://dl.4players.de/ts/releases/3.1.10/

**Comment by dedmen** [comment]
@JABirchall no it's not.
@tonyrodrigues YES it does solve it. We already know

**Comment by thorwe** [comment]
Beta client 3.2.2 should fix this.

**Comment by JABirchall** [comment]
TS 3.2.2 is released and this bug is no longer happening for me.
