### ISSUE TITLE
I am a player from China. Can I edit the language file and translate Chinese?

### ISSUE THREAD

**Issue by diguo520** [michail-nikolaev/task-force-arma-3-radio#1438]
I am a player from China. Can I edit the language file and translate Chinese?

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/stringtable.xml

This is a issue tracker... For issues, not questions.

**Comment by diguo520** [comment]
I do not have permission to edit this page.
