### ISSUE TITLE
Player can still use LR radio even if he dropt it.

### ISSUE THREAD

**Issue by tuntematonjr** [michail-nikolaev/task-force-arma-3-radio#1449]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**Task Force Radio Version:** `1.0-dev.305` 

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- When player drop LR backback. He can still use it and change settings etc.

**Steps to reproduce:**
- Drop LR and try to use it.

**Where did the issue occur?**
- Editor (Multiplayer) 
EDIT. Tested this also in dedicated and same thing (but this time there was more mods)

**RPT log file:**
- nothing in RPT logs

**Comment by dedmen** [comment]
Already fixed for 306
https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/fd99b62f825e482a0b497461cb542548203c872a
