### ISSUE TITLE
Using "call TFAR_fnc_haveLRRadio" in IF statement. It give following error.

### ISSUE THREAD

**Issue by tuntematonjr** [michail-nikolaev/task-force-arma-3-radio#1450]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**Task Force Radio Version:** `1.0-dev.305` 

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- Using "call TFAR_fnc_haveLRRadio" in IF statement. It give following error.
If player dont have LR
```
23:22:07 Error in expression <pace getVariable ["TF_lr_active_radio", _backpackLR];
private _overrideLR = miss>
23:22:07   Error position: <_backpackLR];
private _overrideLR = miss>
23:22:07   Error Undefined variable in expression: _backpacklr
23:22:07 File z\tfar\addons\core\functions\fnc_lrRadiosList.sqf, line 23
```
If player have LR radio
```
23:22:37 Error in expression <ue _backpackLR; 
_result pushBackUnique _vehicleLR; 

if ((player call TFAR_fnc_>
23:22:37   Error position: <_vehicleLR; 

if ((player call TFAR_fnc_>
23:22:37   Error Undefined variable in expression: _vehiclelr
23:22:37 File z\tfar\addons\core\functions\fnc_lrRadiosList.sqf, line 33
```
**Steps to reproduce:**
Run this
```
[] spawn { 
	if !(call TFAR_fnc_haveLRRadio) exitWith { 
		hint "Well Hello There" 
	}; 
};
```

**Where did the issue occur?**
- Editor (Multiplayer)

**RPT log file:**

**Comment by dedmen** [comment]
most of TFAR's functions are made to be ran in unscheduled. In this case the usage of nil is intended.

**Comment by tuntematonjr** [comment]
Ok. Then there is something wrong with my actual script. It should also run in unscheduled (not reproduce one). 
I supose this is not real problem and can be closed. Thanks for answering and keep up the good work.

**Comment by Pergor** [comment]
I had the same problem with version .312 (used .302 before where it didn't occur).

I solved it by using this instead:
`private _activeLRRadio = _unit call TFAR_fnc_backpackLR;
if ( isNil "_activeLRRadio" ) exitWith { };`

That way it worked in scheduled environment as well as in unscheduled.

**Comment by commy2** [comment]
The scheduler is the most annoying thing about SQF and responsible for 99% of all scripting bugs.
Just force unscheduled environment when using the function (or doing scripting in general). If you don't want to rewrite your whole script then you can abuse `isNil CODE`. For example:
```sqf
[] spawn {
    isNil {
        if !(call TFAR_fnc_haveLRRadio) exitWith {
            hint "Well Hello There";
        };
    };
};
```
