### ISSUE TITLE
Stop transmitting when userInputDisabled ?

### ISSUE THREAD

**Issue by Reekoj** [michail-nikolaev/task-force-arma-3-radio#1455]
Hello, i don't really know if it's a feature request or a bug.
1st problem : 
If you call `disableUserInput true;` on a player while he's transmitting on the radio, he can still talk and hear everyone until you `disableUserInput false;`
2nd problem : 
After that, If you call `disableUserInput false;` and you remove the unit's radio, he can't hear other players anymore, BUT they can hear him (even if he doesn't have any radio)

**Comment by dedmen** [comment]
`call TFAR_fnc_releaseAllTangents`
