### ISSUE TITLE
Option for delaying being muted when going unconscious

### ISSUE THREAD

**Issue by Bummeri** [michail-nikolaev/task-force-arma-3-radio#1456]
It would be great to have a CBA setting that could be adjusted to give a little delay before player gets muted when he goes unconscious. Mainly because it would be a way to communicate to other players very briefly that you got wounded. This would make team-play easier when such things get noticed more often and earlier.

**Comment by dedmen** [comment]
When you get shot and fall over unconscious, you don't just say "hey I got wounded! help".. You fall over unconscious..

**Comment by Bummeri** [comment]
Yet also you do not always lose your consciousness the second the injury that will eventually put you unconscious is received...

**Comment by dedmen** [comment]
ACE is about realism. Not gameplay. 
If you don't go immediately unconscious then you don't. If you do, then you just got immediately unconscious, can't yell out anymore.

**Comment by Bummeri** [comment]
The whole medical system in ace is already customizable and filled with elements that support different gameplay such as: revive, treating hitpoints etc. etc.

This discussion is moot at this point anyway so have a good day!
