### ISSUE TITLE
REQUEST - Emergency Forces Vehicles get vehicle radio

### ISSUE THREAD

**Issue by Syr3L** [michail-nikolaev/task-force-arma-3-radio#1457]
HI!

I like to request that emergeny vehicles like the police offroad and the ambulance van get a blufor lr vehcle radio

i may send in a pull request for it to ease it in

maybe get the civilian IDAP faction their own radio code like idap_radio_code or something and they use the indipendent equipment

i have to read in in how to create radio cycles on this one then i try to help you out a bit if help is wanted?

**Comment by severgun** [comment]
???
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-For-developers#vehicles

**Comment by SekiAlpha** [comment]
@Syr3L you should close this, @severgun has the answer for you.
