### ISSUE TITLE
Problem  with CTRL + P | ALT + P | CTRL + TAB

### ISSUE THREAD

**Issue by ImPacT937** [michail-nikolaev/task-force-arma-3-radio#1464]
Launcher version: 1.5.145631
Game version: 1.92.145639
Branch: main / beta branch not specified

CBA_A3 - v3.11.1.190503
TFR - v0.9.12 (10-10-2016)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
Hi first. I have a problem and although, I can not open the radio with CTRL + P / ALT + P. The change of the "Change Speaking Volume" [CTRL + TAB] also not. What works is with "Capslock" nornal speeches. I'm just desperate.
I have repeated the following activities:
- Reinstallation Arma / TFR / CBA (No solution)
- 2 test servers set up (no solution)
- Mods newly downloaded (No solution)
- Searched several forums (No solution)
- Keys allocated in (L / CTRL + L / Shift + L (No solution))
- Mission SQM emptied and only the modules set (No solution)
- CBA / TFR in a mod and loaded separately (no solution)

Is it because of me?! Am I doing something wrong ?! There was already a thread of something like that but no solution. The server is a Windows Root Dedi. from OVH.
Ah and one more thing, I see all the items being loaded. CBA is also activated.
Sorry my English is very very bad LUL

Server-side and client-side RPT logs says nothing

**Comment by dedmen** [comment]
>Ah and one more thing, I see all the items being loaded.

Does your radio have a ID? You should see that on it's name in your inventory or in the classname.
Is TFAR loaded propery on the server?

**Comment by ImPacT937** [comment]
Yes TFR is loaded. I also see in the inventory the ID when I hover over the item.

**Comment by kripto202** [comment]
are you running default hotkey setup for tfar or did you modify your keys or did you hotkeys change somehow?

**Comment by SekiAlpha** [comment]
I mean the author hasn't gotten back in two months on this issue. I think this can be closed due to inactivity @dedmen
