### ISSUE TITLE
Cannot us SR only LR and direct talk

### ISSUE THREAD

**Issue by dprince2** [michail-nikolaev/task-force-arma-3-radio#1466]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `3.11.2` (stable / dev + commit hash)
**Task Force Radio Version:** `1.-1.0.312` (stable / dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- Unable to use Short Range Radio's. 
I am able to use LR and Speech though

**Steps to reproduce:**
Load up server

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- https://gist.github.com/dprince2/45c13ba8fad9afc30234bb69c6f4dc6f

**Comment by dedmen** [comment]
Can't reproduce.
Your TFAR serverside eventhandler is not set. Should be set in TFAR preInit on server.
Either something is breaking preInit, or removing the eventhandler.

Can you reproduce with just CBA+ACE+TFAR?

>Mods:
>- @CBA_A3
>- @task_force_radio


Don't lie to me.

`Warning Message: No entry 'bin\config.bin/CfgMovesMaleSdr/Actions.'.`
Some mod you are loading is terribly breaking the game config. Find out what it is and remove it.

**Comment by dprince2** [comment]
> Don't lie to me.

> 

Sorry didnt mean to, was just alot of mods and at the time it was 2am for me so i didnt feel like listing them all. and all of them were listed in the RPT file.

that being said i went back through enabling mod by mod to find the conflict. I do not know which one caused the conflict as i have everything working normally again.

That being said i dont know where that warning message is coming from because i had it as soon as i loaded up CBA + ACE + TFAR, so its one of those.

Thank you for your support
