### ISSUE TITLE
Настройка тимспика для администрации.

### ISSUE THREAD

**Issue by lisfab** [michail-nikolaev/task-force-arma-3-radio#1474]
Есть ли возможность изменять имя канала и пароль в тимспике не изменяя pbo? Где эти настройки нужно указывать?

**Comment by Fusselwurm** [comment]
your question may be answered here: https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5
