### ISSUE TITLE
Cant hear people talk in radio

### ISSUE THREAD

**Issue by Rayson88** [michail-nikolaev/task-force-arma-3-radio#1476]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**Task Force Radio Version:** `x.x.x` (stable / dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- When i join Arma3 server after i switch channel and frequency, i cant hear people talking in radio but they can hear me ...and i checked log..this showed up
task_force_radioCan't get current channel : invalid clientID
i tried reinstall ts and TFAR many times...its not working...

**Comment by dedmen** [comment]
Fill our the issue template or I won't even look at this.

**Comment by SekiAlpha** [comment]
You could probably also close this @dedmen. Do I even have to @ you?

**Comment by dedmen** [comment]
no you don't have to.
@Rayson88 if you want to report an issue, then fill out the issue template. If you don't care to report correctly, then I don't care to help you either.
