### ISSUE TITLE
[Update 1.94]Saving loadouts with TFAR Radio equipped in BI Arsenal cause fail to load the loadouts

### ISSUE THREAD

**Issue by GoldJohnKing** [michail-nikolaev/task-force-arma-3-radio#1477]
**Please notice it may not be a TFAR bug, BI possibly caused this problem.**

**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)
**Task Force Radio Version:** ~~9.0.12~~`0.9.12` (stable, workshop version)

**Mods:**
```
- @CBA_A3
- @ace3
- @task_force_radio
```

**Description:**
- Since v1.94 update, in BI Arsenal, when player have TFAR Radio chosen in radio category and saved their loadout then try to load it, the saved loadout's name appears gray and the load button is deactivated.
Screenshots here:
https://i.endpot.com/image/ZIIVR/QQ%E5%9B%BE%E7%89%8720190726172229.png
https://i.endpot.com/image/HEL6P/QQ%E5%9B%BE%E7%89%8720190726172217.png
(In China we cannot directly upload file to github, so sorry for the screenshots provided by externel link.)
- This seems only happen with v0.9.12 version of TFAR. v1.0.318 tested, currently not encounter this error.
- Currently not reproduced this error with with ACE Arsenal.
- Some players have similar error with RHS but not related to TFAR, so it could be BI's fault. Screenshot: https://i.endpot.com/image/WZDEL/20190726171025_1.jpg

**Possibly Causes:**
- I think this error may be related to the TFAR items' classname.
- Players' tfar radios have different classnames. For example, player 1 join the server and take tfar_anprc152_1, then player 2 take tfar_anprc152_2... 
- So if TFAR mod only have tfar_anprc152 as a registed classname, then tfar_anprc152_1 and tfar_anprc152_2 becomes an invalid item, so the loadout becomes unloadable.
- v1.94 SOPTREP (https://dev.arma3.com/post/spotrep-00089) have related contents:
Fixed: Saved custom loadouts are now correctly compared against available Arsenal gear, and incompatible loadouts are disabled
- The related mplementation might be already refactored in v1.0.* TFAR (I'm not sure), and it might be the reason that the same error does not happens with v1.0.318.

**Steps to reproduce:**
- Go into BI Arsenal (either SP & MP)
- Choose TFAR Radio in radio category on the left panel.
- Save the loadout.
- Try to load the saved loadout, you'll find its name turns gray and becomes unable to load.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**RPT log file:**
- No RPT log related.

**Comment by dedmen** [comment]
Yes BI's fault. I already told them about it and it might get fixed in the hotfix.
>Task Force Radio Version: 9.0.12

That version doesn't exist
>Players' tfar radios have different classnames. For example, player 1 join the server and take tfar_anprc152_1, then player 2 take tfar_anprc152_2...

No that's wrong. tfar_ classnames are TFAR 1.0, which has a automatic filter which filters ID's out from saved arsenal loadouts.

The issue are indeed the unique IDs, but only TFAR 0.9 doesn't automatically filter them out.

**Comment by GoldJohnKing** [comment]
> That version doesn't exist

Wrong version corrected... 😭 

> Yes BI's fault. I already told them about it and it might get fixed in the hotfix.
Thanks. If there's any issue tracker for me to fllow and keep me update to the issue, please let me know.

> No that's wrong. tfar_ classnames are TFAR 1.0, which has a automatic filter which filters ID's out from saved arsenal loadouts.
>
>The issue are indeed the unique IDs, but only TFAR 0.9 doesn't automatically filter them out.

Yep, I get your points.

**Comment by SekiAlpha** [comment]
@GoldJohnKing you can also use the ace arsenal that should solve your problem.

**Comment by Dahlgren** [comment]
Should hopefully be fixed since the Arma 3 1.94 hotfix release earlier this week.
