### ISSUE TITLE
How to force TFAR to not replace the radio automatically?

### ISSUE THREAD

**Issue by Bluscream** [michail-nikolaev/task-force-arma-3-radio#1483]
I am stuck in a SP mission because TFAR always overwrites the default Radio with it's own version and i cannot start the mission without the default radio in inv. I tried setting the addon settings to never give a radio:

![](https://i.imgur.com/nMdZAaQ.png)

**Comment by Fusselwurm** [comment]
Uhm, replacing the radio is the whole point of TFAR. If you don't want that, don't use the mod (also, why are you loading TFAR in SP anyway).

Am I missing something?

**Comment by dedmen** [comment]
Hi Bluescream! :D
Afaik you can't disable that in old TFAR.
New TFAR doesn't do anything in SP anymore, thus won't replace it either.
Upgrade to 1.0, bug already solved there.

**Comment by Bluscream** [comment]
Thanks ^^
