### ISSUE TITLE
Feature Request: Microfon status

### ISSUE THREAD

**Issue by BluetypeOrigen** [michail-nikolaev/task-force-arma-3-radio#1486]
Build a command that User can see if there Microfon on TeamSpeak is muted. Some User forgot to unmute there Microfon and talk with him self.

**Comment by Fusselwurm** [comment]
ooooh I like that. Alternatively, a "you're sending direct speech right now" icon (like when you're radioing) would do the trick too.

**Comment by dedmen** [comment]
This feature request was only about API so far, not a user indicator.
User indicator won't make it to 1.0, API probably will
