### ISSUE TITLE
TS3 server tab change crash

### ISSUE THREAD

**Issue by oldLucke** [michail-nikolaev/task-force-arma-3-radio#1488]
**Arma 3 Version:** `1.96` (stable )
**CBA Version:** `3.12.2.190909` (stable)
**Task Force Radio Version:** `1.-1.0.325` (dev)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- New TFAR plugin crashes TS3 when you are ingame and change the active TS3 server tab.

**Steps to reproduce:**

1. Join at least 2 TS3 servers.
2. Go Ingame with TFAR
3. Change the active server tab.
4. Profit?!?

**Where did the issue occur?**
- Dedicated

**Comment by SekiAlpha** [comment]
@oldLucke I'm not sure what changed but this bug has stopped happening to me, it could have been this new update but I tried reverting back to 325, to try and reproduce the issue but I wasn't able to produce a crash.

**Comment by oldLucke** [comment]
this seems to be fixed with later versions of TFAR or TS3
