### ISSUE TITLE
[Feature Request] Additional keybinds: Next/Previous channel, radio volume control. 

### ISSUE THREAD

**Issue by Niksuto** [michail-nikolaev/task-force-arma-3-radio#1491]
It'd be neat to see independent keybinds for the following settings on future versions.
```
Active/ALT SW radio: "Next and previous channel" keys. "Set additional channel" key. 
Active/ALT LR radio: "Next and previous channel" keys. "Set additional channel" key. 
```
As well as independent volume controls for the radios through hotkeys/keybinds.

Ideally the entire user interface should be manageable through keybinds without using the mouse. Which would be especially cool for those of us using button boxes, or other controllers.

**Comment by dedmen** [comment]
Ref TFAR discord https://discordapp.com/channels/233658633957802016/235996654455488513/641457098873634886

**Comment by Grezvany13** [comment]
see #1492

**Comment by dedmen** [comment]
Fixed by https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1492
