### ISSUE TITLE
Hear people while zeus.

### ISSUE THREAD

**Issue by TimRuskof** [michail-nikolaev/task-force-arma-3-radio#1503]
I'm on a server, a multiplayer server, but i can't hear other people because I can't add a virtual zeus, any idea ? I'm borred to TP me to other players, far enough to don't let them listen to me.

**Comment by dedmen** [comment]
> because I can't add a virtual zeus,

Why not? I can't see any reason why you can't?

Just set the Curator Cam Ears option, it will put your ears into your Zeus camera even if you are not a zeus logic.
