### ISSUE TITLE
Change Default Range

### ISSUE THREAD

**Issue by matt2210** [michail-nikolaev/task-force-arma-3-radio#1506]
Hello 

I'm runing on dedicated server 

I Want to change the default range of radio i try to edit tf-range in config of mods but nothings 

Can you give me more information to edit this please 
Thanks

**Comment by nomisum** [comment]
no mod needed.

`player setVariable ["tf_sendingDistanceMultiplicator", 0.5]`
`player setVariable ["tf_receivingDistanceMultiplicator", 2]`

**Comment by matt2210** [comment]
Thanks

**Comment by matt2210** [comment]
Where can i insert this Variable i try in INIT.sqf but nothing is working
