### ISSUE TITLE
Add Shoutcaster mode

### ISSUE THREAD

**Issue by AdmiralGhoster** [michail-nikolaev/task-force-arma-3-radio#1509]
**Arma 3 Version:** `2.0 stable
**CBA Version:** 3.15.1 stable
**Task Force Radio Version:** 1.0.327+

I'm part of a large arma pvp event and was wondering on the possibility of adding a "shoutcaster" mode to the tfar mod.
This would allow players in the game logic(or other non sided slot( not west,east,ind,civ)) to hear in mission players normally and not dead players, but also making the dead players be unable to hear the "shoutcasters". it should also be stated that the shoutcasting spot should be able to hear other shoutcasting spots as if they were in the spectator normally.

Ideally, if you could "lock" said position behind a in-game password or ts role would be optimal, as not everyone should be allowed to get into the shoutcasting spot. another idea would be to allow players to create shoutcasting lobbies that have passwords within the mission that get removed at mission end.

The ideas of this role are as follows:
    //allow this role to hear in-game players as if specator
   // mute all other spectators from this role, and mute this role from spectators
   // have a "lock" to prevent random players from joining [allowing JIP] (parameter, password, role, playerid, ect...)
  //  bypass a need to create a tunnel of one ts channel to another (which probably will not work)
    (Optionally): allow client level unmuting of this role while in spectator [via client addon settings]

**Comment by AdmiralGhoster** [comment]
ill try and look at where i can add this on my own, but im still newish to arma coding

**Comment by AdmiralGhoster** [comment]
wrong place moving to pull requests

**Comment by dedmen** [comment]
That sounds exactly like how spectator mode is supposed to work
