### ISSUE TITLE
CBA3 update new error.

### ISSUE THREAD

**Issue by ARMAARMA2020** [michail-nikolaev/task-force-arma-3-radio#1519]
**Arma 3 Version:** `2.00` (stable)
**CBA Version:** `v3.15.2` (stable)
**Task Force Radio Version:** `1.0.318` (dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- After updating to the new version of CBA3 today it appears TFAR has formed a compatibility error, perhaps a renaming of a core component has caused an issue. Still investigating. However, I was banned from the discord when reporting the issue, so mainly doing this for the users and nkey.

**Steps to reproduce:**
- update CBA and boot on the server

**Where did the issue occur?**
- Dedicated 
![tfar error](https://user-images.githubusercontent.com/74127193/99724420-812e4700-2aab-11eb-9e75-83921055f3b7.PNG)
91cd-fd17ec6e2244.png)
[arma3server_x64SERVERERROR_2020-11-19_15-07-49.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/5569748/arma3server_x64SERVERERROR_2020-11-19_15-07-49.txt)

**Comment by dedmen** [comment]
> Task Force Radio Version: 1.0.318

That version is 1 year and 5 months old....? We are at version 327.

> CBA Version: v3.15.2

That's wrong, your logs say you're running v3.15.1 from 7 months ago.

Your screenshot also doesn't show a CBA change that would break TFAR, it seems to show that you didn't update or load CBA correctly.


Feel free to come back when you have a actual bug to report o7

**Comment by BaerMitUmlaut** [comment]
Why are you trying to hide Black Star Initiative?

**Comment by ARMAARMA2020** [comment]
I give up, really toxic

**Comment by dedmen** [comment]
The text was edited out, but here for reference the original issue report.

![Screenshot_2020-11-19 CBA3 update new error · Issue #1519 · michail-nikolaev task-force-arma-3-radio](https://user-images.githubusercontent.com/3768165/99730283-77610f80-2abc-11eb-9980-aaa98feff4e8.png)

**Comment by ARMAARMA2020** [comment]
just take it down now, I'm really done now

**Comment by commy2** [comment]
FYI to anyone reading this issue.
The recent CBA update did not "form any compatibility error" in TFAR and no "core components" have been renamed.
If you are the maintainer of a server, it is your responsibility to update and maintain it correctly. Don't expect anyone else to do your job for free.
