### ISSUE TITLE
TFAR broken after upgrade to Windows 11 from Windows 10

### ISSUE THREAD

**Issue by Swearinbag** [michail-nikolaev/task-force-arma-3-radio#1533]
**Arma 3 Version:** `2.06.148221` (stable)
**CBA Version:** `3.15.6` (stable)
**Task Force Radio Version:** `0.9.12` (stable)

**Mods:**
```
- @CBA_A3
- @task_force_radio
- RHS:USAF
- RHS:AFRF
- ACE 3.13.6
- RHS: GREF
- RHS: SAF
- Ace compats for AFRF, USAF, GREF
- CUP terrains - core 1.17.0
- CUP terrains - maps 1.16.0
- Achilles 1.3.1
- Rosche, Germany
- Anizay
- Kujari
- Ruha
- Pulau
- Gruppe Adler Trenches
- DUI - Squad Radar
- Hellanmaa
- 29th ID
```
**Description:**
- Worked well when working with Windows 10. Stopped properly working on Windows 11. Voice location in game is broken. Radios don't sound well and lost left/right sound when switching stereo settings.

**Steps to reproduce:**
- So far I've found that if you upgrade to windows 11 this is what you get.

**Where did the issue occur?**
- Dedicated multiplayer server. Worked for everyone (all windows 10 users).

**RPT log file:**
- [pastebin](https://pastebin.com/hN9KADt8)

**Comment by severgun** [comment]
> Task Force Radio Version: 0.9.12 (stable)

I play with it on Windows 11 since june. Everything is normal for me.

**Comment by Swearinbag** [comment]
Fixed the issue. Apparently TS needs to be on my arctis 7's game channel, not chat.

**Comment by Swearinbag** [comment]
Fixed the issue. Apparently TS needs to be on my arctis 7's game channel, not chat.
