### ISSUE TITLE
Side Default Radio for Independent uses the wrong str() value

### ISSUE THREAD

**Issue by indig0fox** [michail-nikolaev/task-force-arma-3-radio#1539]
`str(independent)` in TFAR_fnc_getSideRadio returns "GUER", however the init variables from TFAR create "TFAR_DefaultRadio_Personal_Independent", causing retrieval of these variables based on string interpolation to fail. This requires compensation code to work around.

```sqf
missionNamespace setVariable [
  "TFAR_DefaultRadio_Personal_Guer",
  TFAR_DefaultRadio_Personal_Independent,
  true
];
missionNamespace setVariable [
  "TFAR_DefaultRadio_Backpack_Guer",
  TFAR_DefaultRadio_Backpack_Independent,
  true
];
```

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/c408ce13e9300069207213fb75df49f0b5dfe7c5/addons/core/functions/fnc_getSideRadio.sqf#L26-L37

**Comment by dedmen** [comment]
oh wow, that might be a pretty old/big bug there if that also happens in the encryption code place

**Comment by SekiAlpha** [comment]
> oh wow, that might be a pretty old/big bug there if that also happens in the encryption code place

Wait would this be the cause of encryption codes randomly breaking for random people?

**Comment by dedmen** [comment]
If that get variable fails, you may get no/broken encryption codes

**Comment by SekiAlpha** [comment]
Well if that's the case I will start turning on encryption on my servers after this bug is fixed.

**Comment by SekiAlpha** [comment]
@indig0fox So I talked to Dedmen on discord and he said that he doesn't have time to implement this. If you can would you be able to make a pull request so Dedmen can merge your changes? IF not I'd be more than happy to help, but my skills are compatible to a novice.
