### ISSUE TITLE
TFAR 1.-1.0.329 breaks Addon Settings in Eden

### ISSUE THREAD

**Issue by klausman** [michail-nikolaev/task-force-arma-3-radio#1542]
**Arma 3 Version:** `2.06.148470` (stable)
**CBA Version:** `3.15.6.211004` (stable)
**Task Force Radio Version:** `1.-1.0.329` (stable / dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**

"Addon Settings" in Eden is broken.

**Steps to reproduce:**

- Open game with mods loaded
- Go to Multiplayer > Server Browser -> Host Server, start localhost server
- Select Altis, New, hit "Play" (i.e. start editor)
- Go to Settings , click "Addon options"

-> Nothing happens.

**Where did the issue occur?**
- Editor (MP)

**RPT log file:**

Likely relevant part:

```
14:01:27 [CBA] (xeh) INFO: [0,13.052,0] PreStart finished.
14:01:27 Error in expression < == 1) then { ('%1 is getting out of %2',_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error position: <,_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error Missing )
14:01:27 Error in expression < == 1) then { ('%1 is getting out of %2',_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error position: <,_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error Missing )
14:01:27 Error in expression < == 1) then { ('%1 is getting out of %2',_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error position: <,_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error Missing )
14:01:27 File z\tfar\addons\static_radios\XEH_postInit.sqf..., line 15
14:01:27 Error in expression < == 1) then { ('%1 is getting out of %2',_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error position: <,_player,_vehicle); [_vehicle,_player,[t>
14:01:27   Error Missing )
14:01:27 File z\tfar\addons\static_radios\XEH_postInit.sqf..., line 15
14:01:29 SimulWeather - Cloud Renderer - noise texture file is not specified!
```

Full logfile: https://skade.schwarzvogel.de/~klausman/tfar_329_fail.rpt.txt

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/d0e513d3d6940e932306190df37aff0d20c3b797/addons/external_intercom/CfgVehicles.hpp#L53

The TRACE_2 macro is apparently not being found.
If the file were not found then mikero should've refused to pack that pbo, but they didn't...

**Comment by severgun** [comment]
So can it be fixed for now just by dodging debug info? Instead of waiting for mikero fix
