### ISSUE TITLE
  TFAR_fnc_calcTerrainInterception optimisation

### ISSUE THREAD

**Issue by GalNa** [michail-nikolaev/task-force-arma-3-radio#1550]
**Arma 3 Version:** `2.10` (stable)
**CBA Version:** `steam version` (stable)
**Task Force Radio Version:** `1.1.330` ( dev + commit hash)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
In function TFAR_fnc_calcTerrainInterception
you may to use  vectorAdd and vectorMultiply 0.5 to define the variable _middle

**Comment by smitt14ua** [comment]
#1553

**Comment by dedmen** [comment]
Fixed by https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1553
