### ISSUE TITLE
[Feature request] SIGINT 

### ISSUE THREAD

**Issue by fragilepantsu** [michail-nikolaev/task-force-arma-3-radio#1558]
First I would like to thank the developers for the unique addon. I would like to wish further good development and implementation of new ideas and features.

Since arma is a good military simulator and TFAR is an excellent implementation of radio communications, I propose that based on this addon the possibility of radio electronic reconnaissance be introduced into the game. Considering that Arma 3 has an addon related to this (Contant). Fortunately, they've added 3D models of radio equipment to the game that can be used by the mod.

I propose to consider introducing the following features:

1. Add a spectrum analyzer for different wavelengths to the mod. It can be used to see on which frequencies the signal is transmitted. We know that the interception of conversations can not be the same as in real life, but will be aware of the fact that nearby talking to the enemy. This adds more realism and tactical solutions to the game, such as radio silence. A voice scrambling effect could be added.

2. Modern portable radios support retransmission mode, so I propose to introduce the possibility of using radios as repeaters to increase the transmission range. 

3. Add the possibility of directional signal reception and transmission. For example, using yagi antenna.

4. Add a radio jammer to the mod. If the jammer signal is stronger than the useful signal, then simulate a strong improvement in communication. 

All of this can be realised within a separate dedicated military vehicle.

I am ready to help with additional explanations of how it should work, if you have any clarifying questions. Thank you!

**Comment by b-mayr-1984** [comment]
@fragilepantsu have a look at https://github.com/Crowdedlight/Crows-Electronic-Warfare .
Most of what you are asking for is part of that mod.
