### ISSUE TITLE
New Teamspeak client beta 3.6.0 had emerged.

### ISSUE THREAD

**Issue by unhappytroll** [michail-nikolaev/task-force-arma-3-radio#1559]
And it will break this mod, because new API version 26. ACRE already got updated.

ps. what had became of Mumble integration idea?

**Comment by Xavia1991** [comment]
A update to the TFAR Beta on steam workshop fixes the problem after removing and installing the plugin again.

**Comment by ThalusA** [comment]
It has been release, when will this work ? @dedmen

**Comment by dedmen** [comment]
This was fixed here https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/77525d51bc5d1fcf355db56ded63126f896784a1
