### ISSUE TITLE
Installer for plugin (TS format)

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#32]

**Comment by dedmen** [comment]
Putting the plugins into a zip file with a ini describing it. and naming it .ts3_plugin will then be opened by the teamspeak client and install itself. Its very good practice as i always see communitys struggling with trying to tell people how to install the teamspeak plugins.

**Comment by jmlane** [comment]
The hassle of TS3 plugin installation manually after the Arma addon installation is still something that comes up regularly 2.5+ years later.

Is this something that you would consider revisiting? [ACRE has an extension with a working example](https://github.com/IDI-Systems/acre2/blob/f8bd42f9c504e9028154e5505ffb2d57d0e89cff/extensions/src/ACRE2Steam/CallExt_DllMain.cpp#L255) of how this could be done.
