### ISSUE TITLE
Check for lr_dialog_radio and sw_dialog_radio in case of dialog updates

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#330]
Error in expression < ["_channelText"];
ctrlSetText [  1410, lr_dialog_radio call getLrFrequency];
_c>
  Error position: <lr_dialog_radio call getLrFrequency];
_c>
  Error Undefined variable in expression: lr_dialog_radio
File task_force_radio\client.sqf, line 480

**Comment by kavinsky** [comment]
closing most probably fixed
