### ISSUE TITLE
CBA Flexi menu logs error

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#365]
"x\cba\addons\ui\flexiMenu\fnc_menu.sqf: Invalid params c1: [B Alpha 1-1:1 (L-H),["_this call TFAR_fnc_swRadioMenu"]]"
"x\cba\addons\ui\flexiMenu\fnc_menu.sqf: Invalid params c1: [B Alpha 1-1:1 (L-H),["_this call TFAR_fnc_lrRadioMenu"]]"

**Comment by dedmen** [comment]
still valid?

**Comment by kavinsky** [comment]
i dont think so, so closing
