### ISSUE TITLE
TS PPT button sometimes disabled in case of game crash

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#450]

**Comment by dedmen** [comment]
This is from 0.9.0 so quite old. Never encountered that. Also don't see how that would be possible if the Teamspeak Plugin doesn't crash.

**Comment by dedmen** [comment]
Could have been possible back then. But now its only possible if Teamspeak crashes.. And in that case one doesn't care about a non working PTT button ^^
