### ISSUE TITLE
day/night textures for radio dialogs

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#469]
this is just a cosmetic feature but adding day/night textures to radios will be more inmersive simulation for the addon.
- day/night/(dusk/dawn) textures to radios
- simulate LCD retroillumination
- button retroillumination

this is easy achievable by on the event onLoad of the dialog adjust the texture of the background, on the design side, could be little harder but not impossible.
##

**Comment by dedmen** [comment]
day/night has been Implemented.. Animated buttons is not.. But IMO thats overkill anyway
