### ISSUE TITLE
Add support to Mumble

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#528]
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2669249&viewfull=1#post2669249

Check that thread and the next.

Project Reality has a good implementation.

**Comment by Krzmbrzl** [comment]
This seems like a duplicate of #312 to me

**Comment by dedmen** [comment]
Correct. We'll continue in #312
