### ISSUE TITLE
tf_radio_channel_name in mission param

### ISSUE THREAD

**Issue by made82** [michail-nikolaev/task-force-arma-3-radio#597]
i´m searching for a solution to choose 1 of 3 different values of "tf_radio_channel_name" in the mission param´s (description.ext).
is this possible simmilar like this:
...
class GVAR(tf_radio_channel_name) {
		title = "$STR_TFR_CHANNEL_NAME";
		values[] = {0,1,2};
		default = 0;
		texts[] = {"$STR_TFR_CHANNEL_1","$STR_TFR_CHANNEL_2","$STR_TFR_CHANNEL_3"};
};
...

**Comment by dedmen** [comment]
You can set the channel name variable in your init.sqf which can also read Mission parameters.
