### ISSUE TITLE
Radio rebroadcasting

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#603]
Add the feature to enable vehicles (or fixed antennas) to rebroadcast all radio transmissions of the side.

**Comment by rogerxxxx** [comment]
Should also toss the key word "Repeater" in here.  Radio repeaters (or just more commonly referred to as a "Repeater") are their more common names.

I've also heard relay stations and relay radios used as well.

If I'm not mistaken, repeaters are commonly attached to large antenna masts.  However I would also presume a repeater could be affixed to any vehicle, or to a person.  But I think the later is quite rare.

**Comment by spartancain** [comment]
I know that this is listed as backlogged, but I thought I'd throw my two cents in:

I think a good place to start for this would be a shipping-container-based 'Site on Wheels' as they are called, that can be either placed through the editor or moved and manually set up by field units during gameplay. This would allow a modular preset-able or deploy-able repeater site to be used without too much fuss.

For a model, all you would need is a shipping container, a light antenna mast (can be the short game model, ~20 feet tall), and perhaps a generator (all exist already in game).

For interaction, you'd just really need a setup/disassemble option for the box, and a TFAR interaction menu for the radios inside the box. I suppose it could be scripted in another way (for permanent repeaters), but all you'd need for a field repeaters is two AN/ARCs labeled INPUT and OUTPUT for you to select and configure from next to the box. Subscriber radios then set up to transmit on the input frequency and receive on the output, and the box rebroadcasts the input signal on the output frequency at a simulated 20-100 watts RF (low vs high power, if configurable).

Sure, that's a quick and dirty way to do it, but I thought I would add it for your consideration. Setups exactly like this exist in the real world quite frequently, and they work perfectly well for short term tactical site-on-wheels usage. It can of course be improved upon over time, but I think having a tactical repeater that can be deployed in game like that would be very helpful.


Thanks, hope to see this in game soon - thank you for all you do, you make a wonderful mod.

**Comment by rogerxxxx** [comment]
And just to first simply everything, the portable repeater set-up (ie. generator, short game model ~20 ft antenna, shipping container or trailer) could initially be all statically placed on the map.  And once the internal code is verified working, implement the middle mouse button setup actions.

What is unfortunate, there's already quite a lot of features with deployable static emplacements implemented but currently goes unused due to the requirement of teamwork.  Many are one-man Rambo's like me.  So maybe should consider further dual roles of the trailer or cargo unit (ie. such as providing additional storage space or Virtual Arsenal) to further encourage players to want to take the time to deploy such tools.  Similar to awarding pilots flying hours, which this game does not do to encourage pilots to fly and fly safely.  (ie. I'd have quite a few flying hours accumulated by now, but instead currently within the game, all I get is minus /negative -2,000 for friendly kills.)

Great post spartancain.

**Comment by spartancain** [comment]
Thank you.

I do sort of expect that teamwork will be required for such a thing - after all, TFAR as a whole is designed as a teamwork-enhancing modification. Technically speaking though, all you should need is a sole driver to load the box, drive it out there, dump it, and deploy/configure it. Repeaters shouldn't really be needed unless you're working a team effort across a large area with other units on the same net, so the teamwork bit is sort of included in the package.

I agree though, a permanent, drop-it-in-and-it's-done version is probably the best thing to start with, though it might be easiest, configuration wise, to leave it field-configurable once the map is started rather than worry about creating config setups for it in the map backend.

**Comment by tbeswick96** [comment]
I implemented it in a crude way for use with my unit. Simply running a script on each player that waits for the OnSpeak event. If it is a long range broadcast, then it ups the multiplier if it's in range of a rebro, which I made as a land rover. We can sling load it and drop it somewhere, and then we can speak across huge maps.

**Comment by kavinsky** [comment]
This will be implemented on the next iteration of TFAR.

**Comment by spartancain** [comment]
Fantastic, kavinsky, that's great to hear!

Also, to clarify and reference:

"all you'd need for a field repeaters is two AN/ARCs labeled INPUT and OUTPUT for you to select and configure from next to the box. Subscriber radios then set up to transmit on the input frequency and receive on the output, and the box rebroadcasts the input signal on the output frequency at a simulated 20-100 watts RF (low vs high power, if configurable).

Reference #519 for further in regards that capability.

**Comment by rogerxxxx** [comment]
And are the Input and Output on separate frequencies, are can they be on the same frequency?

In my head, I would imagine they would have to be separate frequencies to prevent  echoes and delays, and other anomalies.

**Comment by spartancain** [comment]
IRL, they would absolutely be required to be on different frequencies (the repeater output would swamp its own input antenna when transmitting and possibly destroy the receiver). I think the TFAR guys are most likely to follow the spirit of reality.

**Comment by rogerxxxx** [comment]
Exactly what I thought, and likely can be referenced within the Amateur Radio documentation.

Thanks for taking the time to explain what would occur.

**Comment by zebra1993** [comment]
i recently used on of [these](http://www.adbgst-c2-prod.vbs.admin.ch/img/photos/g4-000-000-60.jpg), it's used in the swiss army. in the Back are two VHF radio stations who can be linked via a cable to mobile relais. a similar version includes a HF and a VHF radio who are keepable of working along with on anothe ror functioning as a relais. and if you need bigger distances coverd, just deploy the antenna in the field a few meters away.
examples:
- All in one Vehicle
- 3m Container, generator and a antenna (as mentioned before) (the radios coudl be connected with ropes as cables?)
- Built-in in the FOB HQ's 

Would realy love to see something like this in Arma.
Greets zeb

**Comment by WSIContractor** [comment]
I am very interested in this feature. I would be happy to produce some type of retrans antenna. Something like http://blueskymast.com/mast-systems/al1-standard-series/ to be included in a bag and that could be carried manpack or vehicle?

**Comment by dedmen** [comment]
Sure feel free to make a Model and texture. I planned to also make one myself. 
But I planned more like static Antennas placed by the Missionbuilder but a carriable type as a backpack would also be possible.

**Comment by spartancain** [comment]
Just as a $.02 from a real-life radio systems technician..

A man-portable tower would be somewhat ridiculous.. I'd point towards vehicle-deployable more than anything else if there was to be a mobile setup. Just looking at it from a realism standpoint, man-portable is a little silly given the weight of the tower, the weight of the radio repeaters for the tower, the weight of the antennas on the tower, and the need for a generator to provide enough energy for, say, between 25-110 watts output power from the repeater. We're talking at least 300LB of equipment.

My initial interest in this was as an editor-deployable item, so I love that side of it. But just realism-design wise, any such setup would be deployed on or from a vehicle in a stationary position.

Hope I've provided constructive advice.

**Comment by dedmen** [comment]
Wasn't my plan anyway to have mobile antennas. Not even vehicle (yet).
But we already have the antenna from the ILBE Assault pack mod. I thought about maybe interconnecting the relay stations via Satellite. And Players could basically connect to that Sat network with a small backpack carryable antenna.

**Comment by spartancain** [comment]
That makes sense.

I guess my real direction there was to say that the most useful method of doing this was exactly what you had intended - the stationary repeater site placeable by a mission builder. That sounds absolutely outstanding.

**Comment by dedmen** [comment]
Concerning mobile.. We are doing ACE integration stuff anyways. It would be easy to make a static antenna that one can load into cargo of a vehicle and position using ACE dragging.

**Comment by WSIContractor** [comment]
My comment was not for it to be portable. it was for purely being able to carry and load the equipment. All of this gear is essentially stationary. I remember when a retrans site use to be set down on two shipping pallets. Nothing portable. Like @dedmen said we have the ILBE mod which is more than enough,

**Comment by WSIContractor** [comment]
@dedmen Any movement on this? It would be good to get some similar functionality like this http://forums.unitedoperations.net/index.php/topic/11186-acre-retransmit-function/ Then worry about static models, etc.

**Comment by dedmen** [comment]
Static antennas Placed in Eden or Zeus are on the todo list for 1.0
Mobile antennas that you can carry or load into a vehicle maybe 1.1

**Comment by WSIContractor** [comment]
Do you have any prototypes, or spec on what that static placed code it going to look like for 1.0?

**Comment by dedmen** [comment]
not yet.

**Comment by WSIContractor** [comment]
okay, will the static object contain any function scripting capability, similar to what I referenced above?

**Comment by dedmen** [comment]
I don't know yet what scripting will be available. I may add changing the sending range but i didn't plan out anything yet.

**Comment by dedmen** [comment]
First build of the Antenna system was just published. 1.0 build 211 has the Antenna system. Works quite fine as far as I tested. Only one antenna currently the vanilla `Communication Tower`. Or any object can be made an antenna via script
`[_object,_rangeInMeters] call TFAR_antennas_fnc_initRadioTower`
