### ISSUE TITLE
error "nickname is already in use"

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#610]

**Comment by DeliciousJaffa** [comment]
The thing that causes this is having a space at the end or the beginning) of your profile name in arma. Teamspeak auto prunes spaces at the beginning and end of your name on the server, this causes TFAR to go in a loop of trying to set your nickname to one with spaces which are pruned by teamspeak, thus giving the "nickname is already in use" error spam.

**Comment by dedmen** [comment]
#1003
