### ISSUE TITLE
UDP questions

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#626]
Some of us can chose the protocol to be used when establishing an internet connection to be UDP or TCP. UDP is much faster and gives you a way better ping, so this is your usual choice and it never resulted in any problems when playing ArmA or using TFAR. But since we got 0.9.1, the following happens, no matter if you connect to a dedicated server or a private hosted game with TFAR running while using UDP:

-the game starts just fine and TFAR works without any problems (it initializes, you get a channel and can talk over the radio without any problems)

-BUT after after some time (maybe 30-40 seconds) you suddenly get the message that TFAR (it still says 0.8.1 btw  ) seems not to be running (even though it keeps working!) and whenever you do something ingame,...

-you are _completely_ out of synchronization, meaning when you fire your weapons, other players won't see or hear it and the impact of your bullets will not change anything in the game (you can fire whole magazines at other players or several AT-missiles on an Ifrit and it won't explode)
(Note: The desynch happens from the very first second on, even though it is the 3. point in my list.)

This never happened with one of the older TFAR-versions, and it is the only addon running (besides CBA of course, but it does not occur with CBA only).
As soon as you switch to TCP, everything works without any problems, but with a really bad connection.. (high ping, yellow or red chains..)

I really hope that you can find a way to fix this, since we really want to keep playing with your amazing addon! Or is there even something we could do right now?
If you have any questions or need further testing, just let me know!

**Comment by dedmen** [comment]
"Some of us can chose the protocol to be used when establishing an internet connection to be UDP or TCP. "
Shouldnt UDP packets go UDP and TCP packets just go TCP? I know you can set the protocol when going through a tunnel like OpenVPN. Can you explain what you mean? Or just close this is not relevant anymore.
