### ISSUE TITLE
Teamspeak crashes when Plugin Soundboard and TFAR used 

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#639]
Hey,
Often times (more than half of the time), when I have both the Soundboard and TFAR plugin enabled, Teamspeak crashes. The crash occurs when I am starting to transmit via Radio. I am not using the Soundboard plugin actively, it´s just enabled.

**Comment by C0kkie** [comment]
I have this problem atm with the newest version

**Comment by dedmen** [comment]
#1083
