### ISSUE TITLE
Local Saved Radio Codeplugs

### ISSUE THREAD

**Issue by spartancain** [michail-nikolaev/task-force-arma-3-radio#663]
Had a suggestion for you, with an attached question.

Us in the 15th MEU typically use the same frequencies every day and have our own radio codeplug layouts, and it's a pain to individually set up each every time we start into an operation or training. What I suggest to make lives easier would be to add a local userconfig for TFAR in which we could save our radio codeplug, either manually or through saving from in-game, though that would be more difficult to set up. Thus, when TFAR loads in-game, it would check for the presence of a userconfig and would load the frequencies included there if found.

Additionally with this, it would be great for easy differentiation to have an alpha tag (text tag) for each channel in the codeplug that someone could also put in their userconfig. This would necessitate having a freq/alpha swap key on the radio, which would be a pain if you could even find a spare key.
# Might be easier to explain with a config excerpt:

class task_force_radio_codeplug {

```
class sw_channel_1 {
    frequency = 130.0;
            alpha = 3RD PLT;
};

class sw_channel_2 {
    frequency = 70.0;
            alpha = AIR-GND;
};
```

... and so on, then

```
class lr_channel_1 {
    frequency = 31.0;
            alpha = F COY;
};

class lr_channel_2 {
    frequency = 30.0;
            alpha = HQ NET;
};
```
# ... and so on.

I'm digging through the scripts to see how best to do this, but I'm slow and not very good at coding, so I thought I'd pass it to you as well. Also, it's worth asking if you had anything like this in progress already so I don't double your work.

Thanks for the great mod so far, let me know what you think.

**Comment by spartancain** [comment]
Dragging this out of the dirt after two years of my own inactivity...

I just saw that addon by JonBons... it'll take a while for me, but I might see if I can dig through it and decipher how it's done and how to implement it as an integrated element.

I've never actually attempted to code a working thing (other than editing premade configs LIGHTLY) for arma, so I may not be able to do this myself and it certainly will be slow. But I'll try and look and maybe work on something if I'm able... I'd really, really love to see this happen - even if there's no way to SAVE a codeplug from game, it would be great to have so we could just create codeplug files raw and distribute them.

**Comment by dedmen** [comment]
TFAR now has a ingame setting (CBA Settings) that you can use to set global frequency presets. So your request can be accomplished with that.
Using 3DEN you can also configure preset frequencies on group/unit level in the editor when building the mission.
If you were lazy you could just select all player groups, and set the attribute for all of them at once.
