### ISSUE TITLE
[Enhancement] use more accurate data for 3D data (systemset3DListenerAttributes)

### ISSUE THREAD

**Issue by zsawyer** [michail-nikolaev/task-force-arma-3-radio#671]
You are currently building the look-vector from the radians of an angle (https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/ts/src/plugin.cpp#L1197). I believe this is an imprecise approach. 

I suggest that you retrieve the look-vector directly using following SQF:
`vectorDir player`

I have done so myself here: http://dev.withsix.com/projects/mumblelink/repository/revisions/master/entry/sqf/MumbleLink/scripts/fnc_updateMumble.sqf#L23

There you can also find how to get the up vector `_fAvatarTop = (vectorUp player);`. 

I kindly suggest that you update the following file to use the new functions and thus get more precise data while probably also improving performance (due to usage of more native code): 
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_preparePositionCoordinates.sqf

Using these more accurate values will resolve the weird left/right-on/off-switching when the sound source transitions "behind your back". 

Note that my mod is open-source under LGPLv3 if you need a different license let me know and I will re-license the mumblelink project to the license that you need. 
Also beware that the vector transformation for TS and Mumble might differ (left- vs right-handed-coordinate system problem or the like).

**Comment by dedmen** [comment]
1.0 Changed to use full positions for every Player and also Full viewDirection vectors instead of a viewangle. Which gets the Teamspeak Plugin all data needed to be as precise as it could be.
