### ISSUE TITLE
Issue wit h TS profiles

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#744]
создаешь новый профиль в ТС, во время игры, когда находишься в РТ меняешь профиль, потом возвращаешься на старый и у тебя постоянный робовойс, который лечится только перезапуском ТС 

_Google translation:_
Create a new profile in the vehicle, during the game, when you are in the RT you change the profile, then come back to the old, and you have a permanent robovoys which is treated only restarting the CU

**Comment by dedmen** [comment]
You mean Sound output profile?

**Comment by dedmen** [comment]
If anything then Teamspeak issue
