### ISSUE TITLE
CTRL not working?

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#771]
On a related note, but I am not entirely sure this is because of TFAR or the 1.32 patch or Hotfix, it seems that the CTRL key only works erratically. For example, I am sometimes not able to use the stance adjust function, while e.g. CTRL-TAB to switch voice volume works. This might also be an issue with CBA's functionality. I just thought I'd bring this up. It might be related to another addon that I am using, but I haven't changed anything in our clan setup except for the new patch and TFAR, and in vanilla, the Ctrl key works.

**Comment by dedmen** [comment]
CBA keybinding system was rewritten. And TFAR keybinds were also rewritten. 
And if it's external application we can't do anything about it.
