### ISSUE TITLE
- Keybinds under Configure>Controls>Configure Addons reload each time a keybind is added/replaced

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#775]
Keybinds under Configure>Controls>Configure Addons reload each time a keybind is added/replaced and reload even when the addon to configure is switched.

**Comment by CorruptedHeart** [comment]
These are all CBA issues, I believe that CBA's key binding is going to get an overhaul at some point due to various issues discovered within it.

**Comment by ArMaTeC** [comment]
this is fixed in the next CBA update i have it and its super fast now

**Comment by michail-nikolaev** [comment]
@ArMaTeC cool, thanks for info

**Comment by sinbad269** [comment]
Just got into Arma around Christmas and a bunch of people recommend TFAR. I'd like to use my mouse buttons for PTT, but it's not catching any of them. I've only 2 mouse buttons and I only ever use them for PTT; 1 for Teamspeak, 1 for in-game.
I know the game catches my mouse buttons, as I've Mouse 5 as my regular PTT in-game, I despise using Capslock for anything other than it's intended use, so if you could get that sorted, that'd be great thanks.
Other than this issue, it's pretty awesome

**Comment by dedmen** [comment]
@sinbad269 CBA issue. Also in no way related to this issue.
