### ISSUE TITLE
Issue with tangent and speak delay

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#798]

**Comment by dedmen** [comment]
Meaning Radio transmissions ignore Teamspeaks PTT delay? Thats fixed now but maybe forgot to close this issue.

**Comment by dedmen** [comment]
Probably also http://forum.teamspeak.com/threads/127880-SDK-PTT-Delay-stops-audio-transmission-though-it-shouldn-t
