### ISSUE TITLE
Speakers sometimes sound crappy

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#811]

**Comment by kavinsky** [comment]
@dedmen can u check this?

**Comment by dedmen** [comment]
If the guy that transmits is close to the speaker then it sounds crappy i think. I hear people very often screaming then a guy in their fireteam has speaker enabled.

**Comment by kavinsky** [comment]
Tryed it and seems fixed.
