### ISSUE TITLE
Parameter to set additional channel to LR channel of side

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#814]
First of all - Thank you very much for TFAR! It literally changed the way we play for the better.
I was wondering if you thought about the feature we proposed to you. It will help so much to all groups that plays games with split teams (and a lot of missions have split teams, as can be seen on the workshop). It won't be something that helps only to us or to very specific groups. I am sure it will help a lot of players! Even such that are currently not aware that such a feature will be helpful for them. It's also a comms scheme that is used by Special Forces.

Currently, leaders have to tell their guys to be quiet in order to hear LR transmissions and that's bad. Also, teams are not aware to what is going on unless their team leader repeats what command ordered him to do and that's also bad. Having this system has ONLY advantages. And of course, if it's controlled by a configuration parameter (that can be "off" by default) I don't see any downsides for groups that don't want to use it.

Of course the LR frequency can be set manually at the beginning of all missions, but that's time consuming and people will a lot of times will mess up and even change their primary channel. All that makes it a bad choice and an automatic process is really needed...

I hope that you will consider it. Please write back if you have any questions.

Thanks a lot!

Variable [Comrades in Arms]

**Comment by dedmen** [comment]
I don't understand what this should mean. You can already set stereo settings, frequencies and additional channel in script.

**Comment by dedmen** [comment]
>Currently, leaders have to tell their guys to be quiet in order to hear LR transmissions and that's bad. 
Enable speakers
>Also, teams are not aware to what is going on unless their team leader repeats what command ordered him to do and that's also bad.
Enable speakers
