### ISSUE TITLE
CAPS stuck for some players

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#817]

**Comment by dedmen** [comment]
Also occurs to some people on 0.9.8 Not very often though.

**Comment by dedmen** [comment]
Can't reproduce. Letting CTRL go while still holding CAPS stops LR Transmission. Which was what I thought was not working in my last comment. Besides we didn't get any reports about this since 0.9.7 so... Closing this
