### ISSUE TITLE
Quark sound ignores stereo settings

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#821]

**Comment by dedmen** [comment]
https://www.twitch.tv/dedmenmiller/v/90671809 
Its a veryyyyy ugly hack right now... But works fine so far... Need to change a lot more stuff to make it work in a non hacky way... code is on stereoQuarkTest branch

**Comment by dedmen** [comment]
Merged into 1.0 in 2155bc749bbab0377904c887a4a3bb129091049a Its still a bit ugly but it matches the still of the other plugin code :D
