### ISSUE TITLE
Task Force Radio resetting textures of spawned vehicles

### ISSUE THREAD

**Issue by karmaklave** [michail-nikolaev/task-force-arma-3-radio#827]
Reproduce by: 
get server to spawn a vehicle. (we used the hatchback for our test)
sleep 0.1
set custom texture of vehicle
observe for 10 seconds

You should see that TFR resets the vehicle skin to a random BIS default after a short duration.

**Comment by CorruptedHeart** [comment]
Is this still an issue? I will check the inheritance that we are doing in case it is changing things.

**Comment by ace16huey** [comment]
I can confirm the same thing is happening to my server, I didn't know if it was the new randomization thing for vehicles and its only happening to a couple of them, not all. So now that I have seen this, I think the issue may be still there

**Comment by kavinsky** [comment]
Cannot reproduce, seems fixed.
