### ISSUE TITLE
 (CCIP script for aircraft) confict

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#829]
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2803703&viewfull=1#post2803703

**Comment by michail-nikolaev** [comment]
probably too old...

**Comment by jonpas** [comment]
We play with both mods and see 0 issues.

**Comment by michail-nikolaev** [comment]
@jonpas thanks for info
