### ISSUE TITLE
Шифрование звуковых данных в серьезном режиме

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#84]
Enconding of sound data in Serious mode.

**Comment by dedmen** [comment]
"Encrypting the audio data in serious mode" google translate.
Do you mean real encryption over network? So non tfar users can't understand anything from tfar users?
It's possible and shouldn't have a too high performance hit.

**Comment by michail-nikolaev** [comment]
@dedmen probably not... not remember. lets just close :)
