### ISSUE TITLE
Tangent gets stuck when killed while transmitting

### ISSUE THREAD

**Issue by CorruptedHeart** [michail-nikolaev/task-force-arma-3-radio#843]

**Comment by aeroson** [comment]
Might be related?
1) Player is talking (with positional voice).
2) Player dies,
2) Everyone can hear player during the respawn time, behaves like his TFAR is off.

We can hear killed players for a few moments even if the respawn time is set to 0 seconds.

**Comment by dedmen** [comment]
The Teamspeak Plugin currently mutes the player when he is dead. So this should already be fixed.

**Comment by aeroson** [comment]
Dead players are now muted, even in Lightweight mode ?

**Comment by sthorshaug** [comment]
A suggestion is to have a configuration parameter for the muting of dead players. Some groups like to have the option of talking while waiting for respawn.

**Comment by kavinsky** [comment]
Cannot reproduce.
