### ISSUE TITLE
LR activates SR

### ISSUE THREAD

**Issue by jonpas** [michail-nikolaev/task-force-arma-3-radio#845]
When speaking on (or trying to) on a LR radio, SR also gets activated. When you start speaking and during speaking you can see the hint saying LR, but when you terminate you see SR hint displaying for a brief second, which indicates it was activated (and not because of releasing CTRL before CAPS). You can also clearly hear yourself.

Version: 0.9.7.1
Keybinds: Default

This was not reproducible though, it only happened once and without server restart after all of us disconnected and 2-3 of us went back on (again without mission restart) and we didn't get any issues anymore.

**Comment by ACyprus** [comment]
Similar issue experienced last night on coop mission, dedicated server.

Affected only me, 4 others using LR backpacks had no problem.

All of us on current TFAR and CBA versions. Also running other mods.

I had C1 (CAPS) and A2 (TAB) on SR, C1 (F9) and A2 (F12) on LR.

Transmitting LR C1 sometimes worked OK but very often instead:

* LR hint and image would display ok
* LR beeps would play ok
* transmission was sent to SR C1

Incoming transmissions unaffected.

**Comment by Th3Cr0w** [comment]
Got the same prob.
0.9.7.3
Cba 1.20.
Ace3
Hitting left windows for tansmitting lw gives the right hint but broadcasts on sw.

**Comment by michail-nikolaev** [comment]
@ACyprus @Th3Cr0w is it works fine if two keys fort LR used (CTRL + something)

**Comment by ACyprus** [comment]
@michail-nikolaev I will test as soon as I have some friends available to help on a dedicated server. Unless you have one we can try right now together.

**Comment by ACyprus** [comment]
@michail-nikolaev 

> is it works fine if two keys fort LR used (CTRL + something)

**CTRL+CAPS**
* works fine as expected.

**SHIFT+CAPS**
* shows LR hint
* transmits LR and SR at same time
* some team members say they only receive my SR
* VON [text] also displayed, if CAPS bound to vanilla VON




..
I've tested tonight on Dedicated server, we happened to be running Zeus.

First thing I noticed was this in my client RPT:
```
19:27:46 [63677,1844.95,0,"CBA_VERSIONING_SERVER: cba=1.1.20.150416, "]
19:28:27 "Installing EH in display 12"
19:28:27 Unable to get file version size: D:\Games\Steam\steamapps\common\Arma 3\@task_force_radio\task_force_radio_pipe.dll
```




..
Other consistent reproducible results follow.

**BINDINGS:**

- **SR C1** - CAPS 
- **SR A2** - TAB
- **LR C1** - F9
- **LR A2** - F12

**STEPS IN SEQUENCE**

1. Transmit SR C1
  * works OK
2. Transmit LR C1
  * displays LR C1 hint
  * message received by others on SR C1
3. Transmit LR C1
  * works OK
4. Transmit SR C1
  * no hint displayed
  * no message received by others
  * on keyup I see SR C1 'transmitted' hint
5. Transmit SR C1
  * works OK


The above results also observed when keybinds changed to:

- **SR C1** - CAPS 
- **SR A2** - TAB
- **LR C1** - Y
- **LR A2** - T



**Note that:**
- LR A2 was also coming through SR if used in step 2 above instead.
- other team members had no problems and completed steps properly and as expected 



..
Apologies for the confusing mess, hopefully this helps somewhat.

**Comment by michail-nikolaev** [comment]
@ACyprus thanks for report!

**Comment by Th3Cr0w** [comment]
Can confirm, using a combination of ctrl + leftWin works just fine.

**Comment by GRUBES** [comment]
I'm seeing exactly the same behaviour as @ACyprus. It's interesting that when the `LRTransmit` keybind has a modifier like CTRL, everything works correctly. This is my first venture into the TFAR codebase, so hopefully I'm not way off base here.

Sort of stating the obvious, but it would seem that right now the LR keybind is calling both the `onLrTangentPressed` *and* `onSwTangentPressed` functions somehow. In *ClientInit.sqf* it looks like `onSwTangentPressedHack` gets called on `Key Down` as well as `Key Up` events. This makes me wonder if maybe the `_is_lr` guard or the subsequent guard in `onSwTangentPressedHack` that wrap the call to `onSwTangentPressed` are not quite correct and maybe succeeding when they shouldn't.

Looking at `onSwTangentPressedHack` right now, it seems like the code assumes that the `LRTransmit` keybind will always have a modifier. `_is_lr` will always be `false` when the `LRTransmit` keybind has no modifier because the `_mods_lr select #` checks will be false no matter what # is. Thus, in the subsequent check, when `LRTransmit` is pressed, you have:

* `_scancode == _scancode_lr` will be `true` because we are pressing the `LRTransmit` key
* `!(_is_lr)` will be `true` because of aforementioned reason
* `!(_mods select #)` will all be `true` because we are not currently pressing any modifier key.

All three groups of conditions are `true`, so our `if` succeeds and we call `onSwTangentPressed` even though we're pressing the `LRTransmit` key. I'm wondering if you could simplify `_is_lr` a little bit to something like

    // If the currently pressed modifier keys and the LRTransmit modifiers are the same
    // AND we're pressing the LRTransmit key...
    _is_lr = (([_this select 2, _this select 3, _this select 4] == _mods_lr) && (_scancode == _scancode_lr));

I'm curious why we approach this by trying to rule out the `LRTransmit` rather than just checking if we're pressing `SWTransmit`. It could be that I'm missing some vital context there, but just looking at this piece of the code, another option might be to forget entirely about `LRTransmit` and all related variables and go with something like:

    // Get SW DIK code
    _scancode_sw = ((_sw_keybind) select 5) select 0;

    // Determine whether SW key and associated modifiers are pressed
    _is_sw = (([_this select 2, _this select 3, _this select 4] == _mods) && (_scancode == _scancode_sw));

    // If this is in fact SW, then call onSwTangentPressed
    if (_is_sr) then { call TFAR_fnc_onSwTangentPressed; };

I'd have preferred to write this up myself and just submit a pull request for you on this one, but I'm brand new to the modding arena so while I've written scripts before, I'm really not sure on the best ways to set up my environment or how to debug and test the mod appropriately. Any resources or pointers would help.

**Comment by GRUBES** [comment]
I realize now that you cannot directly compare two Arrays like that, but a brief test in the debug console showed this to work:

    [[1,2,3], [1,2,4]] call BIS_fnc_areEqual; // false
    [[1,2,3], [1,2,3]] call BIS_fnc_areEqual; // true

**Comment by michail-nikolaev** [comment]
@GRUBES thanks a lot for your investigation!

**Comment by GRUBES** [comment]
@michail-nikolaev Don't thank me until it's the right fix :) Sorry I haven't been able to write and test it myself, but I'm still a complete n00b to the mod tools.

**Comment by GRUBES** [comment]
I've rewritten the onSwTangentPressedHack function in the vein of my suggestion above. While I'm still futzing around with the addon builder, I thought I would post here to get some more eyes on it. I added a bunch of documentation for my own benefit while I was attempting to understand what was happening.

    /*
        Description:
            An event handler callback function for keypress events that get
            associated to a Display in ClientInit.sqf. Verifies that the
            SWTransmit key is currently being pressed before allowing
            onSwTangentPressed to be called.
        
        Parameters: 
            _this [ARRAY]
            [
                0 : ? unused
                1 : [STRING] DIK code of current key pressed
                2 : [BOOLEAN] Current state of SHIFT key - true if pressed, false otherwise
                3 : [BOOLEAN] Current state of CTRL key - true if pressed, false otherwise
                4 : [BOOLEAN] Current state of ALT key - true if pressed, false otherwise 
            ]
        
        Returns:
            Boolean - whether to override default engine handling for keyboard
                events (always returns false)
            
        See Also:
            https://community.bistudio.com/wiki/displayAddEventHandler
            https://dev.withsix.com/projects/cca/wiki/Keybinding
    */

    private [
        // [STRING] The DIK code of the currently pressed key
        "_scancode_pressed",
        /*
         * [BOOLEAN[]] State of modifier keys [SHIFT, CTRL, ALT]
         * for the current key press event, where the values will
         * be false when not pressed or true when pressed
         *
         * For example, [false, true, true] would mean that the user is
         * currently pressing CTRL and ALT, but not SHIFT
         */
        "_mods_pressed",
        //[OBJECT] CBA Keybind data for the current key press event
        "_keybind_sw",
        // [STRING] The DIK code for the SWTransmit key bind
        "_scancode_sw",
        /*
         * [NUMBER[]] The modifier keys for the SWTransmit keybind,
         * same structure as _mods_pressed
         */
        "_mods_sw",
        /*
         * [BOOLEAN] Used to determine if the user is currently pressing
         * the exact SWTransmit key combination
         */
        "_is_sw_pressed",
    ];

    // Ensure that the player has a radio
    if !(call TFAR_fnc_isAbleToUseRadio) then {
        // Get the DIK code of the key that is currently being pressed
        _scancode_pressed = _this select 1;
        
        // Get the state of each modifier key currently pressed
        _mods_pressed = [_this select 2, _this select 3, _this select 4]
        
        // Get the current keybind for SWTransmit
        _sw_keybind = ["TFAR", "SWTransmit"] call cba_fnc_getKeybind;
        
        if (!(isNil "_sw_keybind")) then {
        
            // Get the DIK code for the SWTransmit key bind
            _scancode_sw = ((_sw_keybind) select 5) select 0;
            
            // Get the modifier keys for the SWTransmit key bind
            _mods_sw = ((_sw_keybind) select 5) select 1;
            
            // If the DIK code AND the modifier keys of the keybind
            // match those of the current key event, then the user
            // is transmitting on SW
            _is_sw_pressed = ((_mods_pressed isEqualTo _mods_sw) &&
                    (_scancode_pressed == _scancode_sw));

            // Proceed with SWTransmit event handler
            if (_is_sw_pressed) then {
                call TFAR_fnc_onSwTangentPressed;
            };
        };
    };
    false

Once I am actually able to build, test, and verify, I'll submit a pull request if you don't get around to investigating first.

**Comment by michail-nikolaev** [comment]
@GRUBES you can use debug mission to test.
Load just task_force_radio_items.pbo and debug mission into editor.

**Comment by GRUBES** [comment]
@michail-nikolaev Thanks for the pointer. Initial testing looked promising. Replacing my code (fixing a few minor syntax errors) definitely fixes the issue that @ACyprus pointed out where the "Transmitting" hint is not displayed when transmitting on SW after LR. I tested repeatedly switching back and forth between LR and SW and in every case saw all prompts as you would expect.

It's late here so I did not have any other people to confirm with me that I was actually not transmitting, but at least the progress on the hints seems promising.

I am still struggling with actually building the full mod. Not sure if I'm just using the tools wrong, but I've used both the Addon Builder from Arma 3 Tools as well as Mikero's pboProject. With Addon Builder, the build fails as soon as it tries to run CfgConvert, and with Mikero's it fails immediately with:

> CfgFunctions.h : ignored or merged
> config.cpp In File z\task_force_radio\@task_force_radio\addons\task_force_radio\config.cpp: Line 17 Cannot include file

**Comment by ACyprus** [comment]
Good work chaps. Happy to test for you if needed. My larger ops are run on Saturdays.

Incidentally, last Saturday I was told I was having the same issue again (transmitting over the wrong radio when I could see the right one in the hint) - the catch is I was using CTRL combos which previously seemed unaffected by the bug.

**Comment by GRUBES** [comment]
I just tested this fix with another player using the debug mission. I believe everything is working correctly. Which branch do you want pull requests on? I will submit one from my fork.

**Comment by michail-nikolaev** [comment]
@GRUBES cool, to the master

**Comment by dedmen** [comment]
Since 0b23f594f21dab050fcce9a2a234ace84b3e669e it is impossible to transmit on SR while transmitting on LR or the other way around.
