### ISSUE TITLE
Move radio from rebreather to mask

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#851]

**Comment by CorruptedHeart** [comment]
The rebreather has the mask, doesn't it? I'm sure there is a connected face piece to the rebreather when underwater.

**Comment by michail-nikolaev** [comment]
As far as I remember rebreather is only thing required to became a diver in arma...

**Comment by CorruptedHeart** [comment]
It is. Closing this as invalid.
