### ISSUE TITLE
When you are being made unconscious by AGM while transmitting, you will see the in-game transmit notification as

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#858]
See [this post on BIF](http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2815699&viewfull=1#post2815699).

**Comment by dedmen** [comment]
Not valid anymore with ACE I'd assume? also BIF link down.

**Comment by kavinsky** [comment]
never happens with ACE
