### ISSUE TITLE
fnc_addEventHandler and incoming radio transmission

### ISSUE THREAD

**Issue by ACyprus** [michail-nikolaev/task-force-arma-3-radio#865]
Hello chaps. Superb job on your addon :)

Question for you, on `TFAR_fnc_addEventHandler`, please.

Is there an event handler I can use whereby I can detect and hook into when a player is receiving a transmission on any available radio, be it SW, LR or vehicle, etc?

I've looked at the list of events, the only one that sounds remotely applicable is "OnRadiosReceived" but I assume this actually means when a unit "physically" receives a radio item to their inventory rather than a radio transmission.

If this is not available, is there another mechanism that would help me achieve the same? Would you consider adding one?

Many thanks for the time.
A.Cyprus

**Comment by dedmen** [comment]
This is actually easy to do. On every position transaction with the plugin we get back if that player is currently speaking. A little extra code to check if we are currently transmitting our position and a check if we were currently talking and done.

**Comment by dedmen** [comment]
Implemented in 83d602989ee706e1d187732197ce0e89ee0ed6c6
Only works on local player... So.. you can only see if the local player is currently receiving a transmission. And you don't know who is sending that transmission.
Could add a script command that receives all players that are currently transmitting and what frequencies they are on. If anyone needs that create a new issue for that please.
Eventhandler is untested but should theoretically work.. I'll close this issue when testing is done.
