### ISSUE TITLE
Check floor level

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#866]
See [this post on BIF](http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2819662&viewfull=1#post2819662) .

**Comment by dedmen** [comment]
Link down. But i guess this is about hearing players in a floor below way too good?

**Comment by dedmen** [comment]
https://forums.bistudio.com/topic/159393-task-force-arrowhead-radio/page-126
