### ISSUE TITLE
Event for radio dialog opening

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#868]

**Comment by CorruptedHeart** [comment]
This is to simply fire an event when a radio dialog has opened correct?

What sort of parameters would be necessary?

I'm thinking

- Radio (string/array)
- LR (bool if it is a LR radio)
- The dialog (a reference to the dialog, if the user wants to do something with it)
- Opened (bool if the dialog has opened or closed)

**Comment by michail-nikolaev** [comment]
@CorruptedHeart agreed

**Comment by CorruptedHeart** [comment]
Event: OnRadioOpen
Parameters Passed:
0: OBJECT - unit (player)
1: STRING/ARRAY - radio
2: BOOL - LR radio
3: STRING - dialog name
4: BOOL - dialog open
