### ISSUE TITLE
Update and review README_SK

### ISSUE THREAD

**Issue by Tourorist** [michail-nikolaev/task-force-arma-3-radio#874]
Would be great if someone with a decent or even native handle of Slovak language, could go over the contents of [README_SK.md](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/README_SK.md) and bring it in line with the recent update to its counterpart translations in English/Russian (see [EN](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/README_EN.md)/[RU](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/README.md)). More specifically:
- The fourth column in "Vysielačky" table has to be filled with the missing instructions (in place of  [inštrukcie]). Alternatively, akin to how the original is formatted, it could be omitted entirely or the information contained therein moved and spread contextually outside of the table (if doable/sensible).
- Check to verify that "palubné rádio" is a proper localization term for "airborne/авиационная" (EN/RU) and "pre autorádiá" for "for vehicle-mounted/для встроенной".
- The list of contributors mentioned in "Veľká vďaka patrí" section is incomplete, between Andy230 and Tourorist (23 missing names).

PS (@michail-nikolaev): Протолкни мои изменения чтобы знающий человек работал с уже более актуальной информацией.

**Comment by Tourorist** [comment]
@evromalarkey, maybe you could look into this, assuming CZ is not that dissimilar from SK. :smile:

**Comment by evromalarkey** [comment]
I suppose I could :) Anyway 

// Check to verify that "palubné rádio" is a proper localization term for "airborne/авиационная" (EN/RU) and "pre autorádiá" for "for vehicle-mounted/для встроенной".

This is correct. I will take a look at reset later :)

**Comment by dedmen** [comment]
Or just remove it. As everyone speaks english anyway right?

**Comment by dedmen** [comment]
No seperated Readme's anymore in 1.0
