### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#875]
> Hello,
> I've checked the recent version of TFAR and made some corrections of the stringtable in task_force_radio .pbo and made the translation of the stringtable in task_force_radio_items.
> 
> There is a link with the two stringtable in my Onedrive.
> 
> task_force_radio : 
> https://onedrive.live.com/redir?resi...int=file%2cxml
> 
> task_force_radio_items :
> https://onedrive.live.com/redir?resi...int=file%2cxml
> 
> I don't know when you update your mod and could include the new translation or if you need my translation XD.
> 
> But keep the good work and don't hesitate to contact me for future translation.
> 
> Cheers form France.

**Comment by michail-nikolaev** [comment]
need to contact author somehow...

**Comment by dedmen** [comment]
Well... contacting the author probably wont happen right?
Also the links are not clickable.

**Comment by kavinsky** [comment]
let him contribute it on GH
