### ISSUE TITLE
Use Mousbuttons for Transmitt

### ISSUE THREAD

**Issue by FallenHorseman** [michail-nikolaev/task-force-arma-3-radio#877]
Is there a Possibility to use aditional Mousbuttons for Transmission?
prob. Mouse4, Mouse5.....

Seems that In-Game config didn't Support Mousebuttons.

**Comment by FallenHorseman** [comment]
@jonpas how did i get the userconfig. Got this one time, unfortunatly i deleted it. now i got only the radio_settings.hpp in Arma 3\userconfig\task_force_radio. 
Thank you FallenHorseman

**Comment by jonpas** [comment]
You can't in the latest version.

**Comment by FallenHorseman** [comment]
ok, thank you.
I used a workaround:
Set LR to (,)
and
      SW to(.)
and use http://www.highrez.co.uk/downloads/XMouseButtonControl.htm for Key-emulation. Works very well for the first test,

**Comment by michail-nikolaev** [comment]
@FallenHorseman good to hear

**Comment by sonst-was** [comment]
@FallenHorseman How/Where did you changed the keys?

@michail-nikolaev Will the support for additional mouse button be included again?

**Comment by FallenHorseman** [comment]
Is a longer time since i played ARMA:

Arma setttings-> controls-> configure addons 
Change SW/LR Transmit as desired. 
I use "." and "," 
Von meinem iPhone gesendet

**Comment by sonst-was** [comment]
Thanks, works perfect.

**Comment by dedmen** [comment]
Does new CBA keybinds system support mouse buttons?

**Comment by dedmen** [comment]
yes it does.
