### ISSUE TITLE
Players not getting radio on mission start

### ISSUE THREAD

**Issue by Enkindler** [michail-nikolaev/task-force-arma-3-radio#881]
Hey guys, i'm having an issue with some custom made coop settings. Every time i start a mission, some players wont get a radio, while others do. We all have the sames version of teamspeak. To get a radio, we need someone that already has one to "convert" normal arma 3 radios to TFAR radios and give them to the ones who dont have one one. Do you guys have any insight of why this is happening?. 

Teamspeak Verison 3.0.16

**Comment by michail-nikolaev** [comment]
@Enkindler is still actual?

**Comment by Enkindler** [comment]
Negative, it hasn't happened anymore.

**Comment by michail-nikolaev** [comment]
@Enkindler cool!
