### ISSUE TITLE
WARNING: Function 'name' - RPT spam when player is dead.

### ISSUE THREAD

**Issue by Cyrokrypto** [michail-nikolaev/task-force-arma-3-radio#885]
The following error message is spammed (usually twice every 1 second) when the player is dead in multiplayer.
```cmd
 1:07:03 WARNING: Function 'name' - Cyrokrypto is dead
 1:07:03 WARNING: Function 'name' - Cyrokrypto is dead
 1:07:04 WARNING: Function 'name' - Cyrokrypto is dead
 1:07:04 WARNING: Function 'name' - Cyrokrypto is dead
 1:07:05 WARNING: Function 'name' - Cyrokrypto is dead
 1:07:05 WARNING: Function 'name' - Cyrokrypto is dead
```
To reproduce, set a respawn delay on a mission:
respawnDelay = 60;

Commit suicide. While the player is dead this message is spammed.

**Comment by jonpas** [comment]
Isn't this vanilla Arma 3 warnings? Try without TFAR.

**Comment by Cyrokrypto** [comment]
I've tested vanilla and with TFAR. The error only occurs when TFAR is used. 

As far as I know, this error occurs when the 'name' command is used on a unit that is dead, in this case the player. I believe that one of TFAR's loops are not checking 'alive player' before 'name player', since this error seems to appear at a constant rate.

If someone could confirm this error, that would be great. :)

**Comment by jonpas** [comment]
I see it as well, but I rarely load Arma without TFAR. :)

**Comment by michail-nikolaev** [comment]
WIll fix in next version (TFAR asks for name of dead player)
