### ISSUE TITLE
Add keybinds for different speech volumes

### ISSUE THREAD

**Issue by cja100** [michail-nikolaev/task-force-arma-3-radio#887]
It would be nice if we could map direct speech to keys with a certain volume, e.g. a yelling button such as right ctrl and still use my normal push to talk as normal.

**Comment by CorruptedHeart** [comment]
I vote no. TFAR already has way too many key bindings.
There is, however, nothing stopping you from creating your own mod that sets the voice volume for TFAR on key presses.

**Comment by jonpas** [comment]
Agreed with CorruptedHeart, a button to change between them is just perfect.

**Comment by proffrink** [comment]
I think this is an excellent idea. Keep it optional, sure, but having to switch between shouting and talking is a little annoying when you're being shot at - to have a simple key that transmits 'shouting' (then stops on release) would be perfect.

**Comment by pukka-pies** [comment]
+1 something like this would be much more useful. Maybe have the option to toggle or shout on press decided by the user?

**Comment by jonpas** [comment]
Okay, add keys but don't set them to any key by default (like some already are), that would work I bet, and keep those who don't want it without the hassle of removing it, while providing those who want it the ability to set it.

**Comment by Jinexo** [comment]
+1 i support cja100, it would be very useful!

**Comment by CommanderJ** [comment]
I would love this feature, it would be incredibly useful in close contact situations.

**Comment by ACyprus** [comment]
Guys, what was the decision on @jonpas suggestion? I was planning a similar addon myself but can have a go at putting it into TFAR instead if acceptable.

**Comment by michail-nikolaev** [comment]
@ACyprus you are welcom to contribute

**Comment by ACyprus** [comment]
Cool, I'll give it a go. @nkey - I'm assuming there is no way to initiate direct speech transmission in TeamSpeak from within the addon, correct? If so, this will essentially be a modifier key held down whilst the users PTT key is pressed. Which could get awkward.

**Comment by ACyprus** [comment]
Hello all, I've submitted a pull request for this tonight.

NOTE: the key binds in configuration are currently called "Yelling Modifier" and "Whispering Modifier" - only because I couldn't think of a better phrase. I am open to suggestions - perhaps something that would place them next to "Change Speaking Volume" in the list.

Any ideas welcome!

**Comment by michail-nikolaev** [comment]
"I'm assuming there is no way to initiate direct speech transmission in TeamSpeak from within the addon, correct? " - it is possible, but with plugin support.

Will check PR soon.

**Comment by dedmen** [comment]
Its possible to initiate direct speech with a hack explained in #992.
we will probably merge #992. And only close this issue when we added the ability to initiate direct speech with the yelling/whispering keys. Also planning to create a config option to either keep as modifier keys or use directly as speak keys.

**Comment by dedmen** [comment]
Added option to auto trigger direct speech when pressing modifier key in 5940117dee5614d931560eac2ebe1d56cade0702
