### ISSUE TITLE
Change the main loop from spawn to a per frame event handler

### ISSUE THREAD

**Issue by CorruptedHeart** [michail-nikolaev/task-force-arma-3-radio#888]
Currently the main loop for TFAR uses a while loop with sleeps. Which are unreliable in how long the sleep will actually take.

What we could do, is use a per frame event handler that checks the `diag_tickTime` and a `nextTime` to determine if the code should update. This would remove the TFAR from Arma's scheduled code.

``` sqf
TFAR_UpdateTime = 0;
["TFAR_MainLoop", "onEachFrame", {
  if (diag_tickTime >= TFAR_UpdateTime) then {
    // main loop here
    TFAR_UpdateTime = diag_tickTime + 1; // 1 second later
  };
}] call BIS_fnc_addStackedEventHandler;
```

**Comment by CorruptedHeart** [comment]
Could also use [CBA's Per Frame Handler](https://dev.withsix.com/docs/cba/files/common/fnc_addPerFrameHandler-sqf.html#CBA_fnc_addPerFrameHandler) which allows defining the delay in seconds. So we don't have to handle that.

**Comment by michail-nikolaev** [comment]
Hm... Currently main loop is already in per-frame handler.
But yes, it is good idea to use CBA (to avoid confict with "everyFrame")

**Comment by CorruptedHeart** [comment]
Server loop could be split into using CBA events for handling radio requests. And a delayed per frame handler for checking if a player has TFAR activated.

[https://dev.withsix.com/docs/cba/files/events/fnc_addEventHandler-sqf.html](Only add an event handler on the server for Radio Requests).
Request the radio on the client via a [remote event](https://dev.withsix.com/docs/cba/files/events/fnc_remoteEvent-sqf.html)

The check for the player's active mod can be done with [a delayed per frame handler](https://dev.withsix.com/docs/cba/files/common/fnc_addPerFrameHandler-sqf.html), perhaps even split the units up over separate calls to the handler.

**Comment by kavinsky** [comment]
@CorruptedHeart still you want to do this issue?

**Comment by CorruptedHeart** [comment]
I'd have to get back into modding again to do it, which might happen. There's been quite a lot of cool features added to CBA from the ACE side that could probably improve a lot of code in TFAR.

If someone wants to tackle this instead, then by all means. I'd prefer holding off on doing a lot of things until the major restructure of the folder structure and so on happens.

**Comment by kavinsky** [comment]
ok no problem, anyways if you want to help us in the structure refactoring, you are welcome.

**Comment by dedmen** [comment]
switch to onEachFrame was made a long time ago. processPlayerPositions was switched to CBA PFH in #1149 and in 1.0 all other (besides serverside for version check) spawned `while {true}` loops were optimized out or replaced with PFH's
Radio requests were rewritten to use CBA Events in bfbca2d41f304f1f265dfaffc28d1fb9abf5e819
