### ISSUE TITLE
SQF error after settings update

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#889]
> If you go to the controls settings while in-game — this error will pop-up every time you press a button. It can only be fixed by restarting the game. [[**source**](http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2862991&viewfull=1#post2862991)]

![](http://i.imgur.com/rUDsOBE.jpg)

**Comment by dixon13** [comment]
Had a similar problem but different function.

**Comment by dixon13** [comment]
Reference #894 for similar issue.

**Comment by CorruptedHeart** [comment]
These might be solved by updating the CBA keybinding method. Which I will do later.

**Comment by dedmen** [comment]
Solved already?
