### ISSUE TITLE
Radio frequencies reset during mission

### ISSUE THREAD

**Issue by Rod6er** [michail-nikolaev/task-force-arma-3-radio#890]
We play on a dedicated server with no headless client. When we start a mission, and the teamspeak reassigns us to the TFAR channel, our in game radios freak out and keep resetting/taking other people's channels. Sometimes you will see the radio channel change right before your eyes. This only happens with a good number of players such as 8+. 
We have tried to set the channels with the editor modules, it usually makes things a bit worse. Usually after a few minutes the radios calm down and stay perfect for the rest of the round/mission. I am not sure what extra information you need to investigate. Thanks!
Version 0.9.7

**Comment by jonpas** [comment]
Are you using any loadout scripts?

**Comment by Rod6er** [comment]
Yes. I can provide an example, they are executed in onPlayerRespawn.sqf (usually). In the loadout, all items are removed and a custom gear is applied to the player.
_this linkItem "tf_microdagr";
_this linkItem "tf_anprc152_3";
Example of an assigned radio. I believe we use the default parameters for TFAR and it assigns a radio to each infantry and a long range to squad leaders. 
Do we have to let TFAR assign the radios and remove them from the loadout, or simply disable TFAR handing radios out at mission start?

**Comment by jonpas** [comment]
There is your problem then, you are assigning a radio with an ID. What you have to do is simply change the `tf_anprc152_3` to `tf_anprc152`. The _N is the ID and it will clash.

**Comment by Rod6er** [comment]
Thank you. I will try this for our next game session and see if it fixes the problem. Much appreciated! I'm not sure if this was the right place to ask but I didn't find any other forums/community spot.

**Comment by CorruptedHeart** [comment]
I will mark this as closed, if it doesn't work you can comment on it again and I will reopen it.
