### ISSUE TITLE
Got script errors and couldn't use radio

### ISSUE THREAD

**Issue by dixon13** [michail-nikolaev/task-force-arma-3-radio#894]
Here is the error...

23:01:37 File task_force_radio\functions\fn_onSwTangentPressedHack.sqf, line 8
23:01:38 Error in expression <hen { 
_mods = (cba_keybinding_handlers select (_sw_keybind)) select 2;
_mods_lr>
23:01:38   Error position: <select (_sw_keybind)) select 2;
_mods_lr>
23:01:38   Error Zero divisor
23:01:38 File task_force_radio\functions\fn_onSwTangentPressedHack.sqf, line 8
23:01:38 Error in expression <hen { 
_mods = (cba_keybinding_handlers select (_sw_keybind)) select 2;
_mods_lr>
23:01:38   Error position: <select (_sw_keybind)) select 2;
_mods_lr>
23:01:38   Error Zero divisor

Was going to go into my controls to look at how to lock onto a target when I got this script error. I couldn't use my caps lock to talk on the radio nor could I open the radios.

**Comment by michail-nikolaev** [comment]
Hm... Correct CBA version?

**Comment by dixon13** [comment]
I'm using the most update version of CBA for Arma 3.

**Comment by dixon13** [comment]
Reference #889 for similar issue.

**Comment by dixon13** [comment]
Haven't experience issue since new CBA key binding system was implemented. So issue was probably fixed.
