### ISSUE TITLE
"you are not able to use the radio" upon respawn

### ISSUE THREAD

**Issue by mvadstrup** [michail-nikolaev/task-force-arma-3-radio#895]
Maybe this should be a MCC issue, but here goes

I am getting  "you are not able to use the radio" upon respawn with TFAR: 0.9.7 and MCC enabled (http://forums.bistudio.com/showthread.php?127214-MCC-Sandbox-The-Mod).

Guess the error is part of the MCC respawn event, but as MCC is widely use @mod, it could be great to get this supported by TFAR

**Comment by mvadstrup** [comment]
Hi - Just forget this issue - This offcourse only occurs if you play with the MCC sandbox mission. Sorry :-(

**Comment by michail-nikolaev** [comment]
nevermind, thanks for report
