### ISSUE TITLE
Long Range Alternate Channel

### ISSUE THREAD

**Issue by simwah** [michail-nikolaev/task-force-arma-3-radio#897]
Issue with long range alternate channel

Reproduction:

Set long range alternate channel
Able to listen to alternate channel
When you transmit using transmit long range alternate bind the the normal channel switches to the alternate channel

**Comment by michail-nikolaev** [comment]
hm... Not sure I get it...

**Comment by Raspu86** [comment]
The primary channel is the last selected channel on the interface. If you switch to channel 3 and set it as alternate and you do not change back then channel 3 will be your primary and alternate channel.

To set it up correctly:
- Open the radio interface.
- Go to channel 3.
- Press Alternate channel (Display changes).
- Go to the channel you want to use as primary.
- Close the interface.

**Comment by michail-nikolaev** [comment]
@simwah is more help required?

**Comment by simwah** [comment]
Non Issue, problem was with bind and usage
