### ISSUE TITLE
Rename currentUnit variable

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#898]
Also, Function TFAR_fnc_haveSWRadio seems to use a global variable currentUnit, and will sometimes provide an error when called during mission initialization scripts if the currentUnit variable is not initialized. If this is the actual unit the player is currently playing, then the function should just return false when the variable is not initialized.

**Comment by CorruptedHeart** [comment]
This just requires adding `TFAR_` to the variable name and doing a `isNil`/`isNull` check on the variable correct?

**Comment by michail-nikolaev** [comment]
Thanks!
