### ISSUE TITLE
TS server Plugin for Linux

### ISSUE THREAD

**Issue by Wiamor** [michail-nikolaev/task-force-arma-3-radio#899]
Hey,

if i understand correctly, the TS server also has to run the client Plugin.
Since i'm running only Linux servers i was wandering if you have planed on releasing a TFR-Linux-server-plugin.

that would be real nice.
Thx and keep up that good work

**Comment by Raskil** [comment]
Hi,

the plugin is not needed on the TS Server, only on the TS Client.
I've a TS3 server on linux myself and it works withour problems.

Greets

Raskil

**Comment by Wiamor** [comment]
How do i then select the ts server and Channel to use? i coudn't find it anywhere in the how to or files by quickly swiping over them.

Thx for the good news ;)

**Comment by michail-nikolaev** [comment]
@Wiamor by default TaskForceRadio with 123 password.

**Comment by michail-nikolaev** [comment]
to change - check https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables

**Comment by Wiamor** [comment]
Thx a lot. in that case just cole this ticket or make add this for server owners how to and then close it.

Thx again and keep up the good work.

**Comment by Raskil** [comment]
Normally, you don't need to change missions if you want to use TFAR with its defaults. Just create a channel named TaskForceRadio on your TS server and protect it with the password 123 and you are good to go. If you however want to customize some of the variables, TFAR comes with some handy editor modules which you can place on the map in editor to customize some of the settings.

**Comment by Wiamor** [comment]
thx
