### ISSUE TITLE
Small MTU results in major desync issues

### ISSUE THREAD

**Issue by BigNose** [michail-nikolaev/task-force-arma-3-radio#900]
I noticed a problem using TFR in Multiplayer:

Due to my slow internet connection I have a MTU of 1300, with which I can play ArmA III Online just fine, until trying to load TFR.

When I do, no matter if it's installed and used on the server or not, I get major desync issues like not being able to enter vehicles, open doors or do damage. This happens regardless of other loaded mods, even on a vanilla game with just CBA and TFR.

I use the lastest version 0.9.7.1.

I know the low MTU size must be the problem, as I tried with some buddies of mine, which have a better connection, and once they lower their MTU to 1300 artificially, they have the same problem.

To reproduce this issue, try to lower the MTU by using the following instructions:

1.) Open the command prompt as an admin

2.) Type "netsh interface ipv4 show subinterfaces" to find out the name of your internet adapter

3.) Use this command to lower the MTU to 1300 artificially (without the square brackets):
netsh interface ipv4 set subinterface "[NAME OF YOUR ADAPTER]" mtu=1300 store=persistent

4.) Join a ArmA III Multiplayer server with TFR loaded

5.) Try to get in a few types of vehicles, open a few doors, check if you can damage other clients
(Sometimes it works for the first couple of times, but it will fail eventually and not come back)

To reset your MTU back to DSL standard, use the same command like in 3. but with "mtu=1500".

I hope this is enough information to find the problem, but I will monitor this ticket at least daily, so if anything remains unclear, just ask.

Thanks in advance,

BigNose

**Comment by michail-nikolaev** [comment]
Thanks for information. Not sure we will able to fix that (becasue it is something deep in Arma engine)...

**Comment by BigNose** [comment]
If you are using a function deep in the ArmA Engine which causes this problem this could indeed be a though one.

Still, without TFR this bug never occurs, even with low MTUs. In some form or another TFR must be the reason, we even tested it on multiple systems, so it can't be a local issue.

**Comment by BigNose** [comment]
Nevermind, the problem seems to have fix itself. This issue can be closed!

**Comment by michail-nikolaev** [comment]
@BigNose woo-ho!
