### ISSUE TITLE
AI hearing players when speak

### ISSUE THREAD

**Issue by Knight1981** [michail-nikolaev/task-force-arma-3-radio#902]
Hey guys,

I saw that ACRE2 has implemented the feature that the AI can now hear players speak and radios on speakers.

It would be so fantastic to have this feature also in TFAR, so we have to whisper or give handsignals in CQB fights etc.

Hope you are able to implement this also in TFAR :) Thanks a lot for your fantastic work!

**Comment by michail-nikolaev** [comment]
Probably will do, also it is possible to implement via some scripting

**Comment by ACyprus** [comment]
I've been planning this myself for a while but have been waiting on some
event handlers due in the next release.

**Comment by michail-nikolaev** [comment]
@ACyprus check https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Events

**Comment by ACyprus** [comment]
Thanks nkey, I was more talking of this one:

https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/865

Granted, the existing handlers would allow me to achieve 90% of
functionality, though I was hoping to do it all in one go (so that AI may
react to your incoming transmissions depending on radio volume and or
whether speakers are active.

Also hoping to use that for integration with my pushtohear addon.

**Comment by Knight1981** [comment]
It would be so great when AI would hear us speaking and react based on this, so we need to whisper in CQB. :)

**Comment by Knight1981** [comment]
@michail-nikolaev: Do you know if you will implement this feature in the near future?

**Comment by michail-nikolaev** [comment]
@Knight1981 not sure yet, possible it is best to integrate it into some AI addon. But I will need to provide some API for it.

**Comment by Knight1981** [comment]
I do not know how ACRE2 has implemented this feature. Maybe you can have a look into their code to get an idea how it works. 

Thank you for your fantastic work!

**Comment by ACyprus** [comment]
The question is, how would you have the AI react? That logic should probably be handled externally by an AI addon. Hence I'm waiting for #865 to make that external addon. I might even look at implementing #865 myself.

**Comment by dedmen** [comment]
Can use https://community.bistudio.com/wiki/reveal to notify AI about us talking. Though #865 is missing to check incoming transmissions. But i guess as long as speakers are not enabled AI can't hear what you hear through your headset.

**Comment by LISTINGS09** [comment]
We use the following script in on a dedi MP to emulate this function, it's not perfect but the script may be of some use to others until this great feature is included as standard.

https://github.com/LISTINGS09/Zeus_Server2/blob/master/f/radios/tfr/fn_tfr_aiHearing.sqf

**Comment by dedmen** [comment]
We will just put it into a optional PBO... I guess.. That would be the perfect solution right? ofcause have to make sure everyone is running that

**Comment by Saborknight** [comment]
Another example of a pre-existing enhancement I found randomly is this:
https://github.com/Spearhead-Gaming-Milsim/TFAR_AI_HEARING

I don't know anything about it but you know.... The title kind of hints at it's function :P

**Comment by dedmen** [comment]
The above link by @LISTINGS09 is the original of your linked script.

**Comment by Knight1981** [comment]
It is great to see that there is progress on this. Cool :)

**Comment by dedmen** [comment]
Solved by adding a Optional pbo in 88fa187c07a61289c5ae59ce9e2409876b2fbf90
