### ISSUE TITLE
Maybe it's possible to fire up the 'Ontangent' EH before setting sendingDistenceMulti?

### ISSUE THREAD

**Issue by ir0n1e** [michail-nikolaev/task-force-arma-3-radio#904]
Situation:
I set the multi with 'Ontangent' EH dynamically, but it is not recognized by 'fnc_onLRTangentPressed'.
The EH fires after setting the multi.

**Comment by michail-nikolaev** [comment]
Not sure I get you.. Could you please provide some additional information? Maybe some SQF code?

**Comment by ir0n1e** [comment]
line 20/23 
https://github.com/ir0n1e/BWplus/blob/master/.files/oldfnc/communications_clientInit.sqf
I set the multi depending on BWplus_communications_fnc_getConnectionQuality (it's variable).

Process now:
Button pressed calls fnc_onLRTangentPressed
fnc_onLRTangentPressed asks for multi and sets multi in line 13
line 18 fires up EH
My EH says: Set new Multi.
New mult is not recognized by fnc_onLRTangentPressed

Process could be:
Button pressed calls fnc_onLRTangentPressed
Fireup EH
fnc_onLRTangentPressed asks for multi and sets multi
New mult is recognized by fnc_onLRTangentPressed

At this time I have to set the multi before i press the button. But it's not possible for me, because the multi is valid for all radios (SR, LR, Underwater). I want to set it for LR, only. So I have to use the EH.

**Comment by ir0n1e** [comment]
To me: Don't press Close, nap

**Comment by michail-nikolaev** [comment]
Hm.... Got you issue. Need to think here.

**Comment by michail-nikolaev** [comment]
So, if you will able to set multi per radio it will fix issue for you, right?

**Comment by michail-nikolaev** [comment]
Or event "BeforeTangent"

**Comment by ir0n1e** [comment]
Both solutions are possible for me.
and perfect is, if you implant 'multi per radio' and the 'EH version'.
