### ISSUE TITLE
fadak dissapears on Ctrl + [

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#908]
> * **Tourorist**: Привет, я тут ковырялся в открытых задачах, но или пропустил или такого еще не докладывали. Так вот, заметил что при смене рации ближней связи (Ctrl+[) в момент когда таковая существует у игрока только в единственном числе и модели Fadak, то она самая исчезает из инвентаря с сообщением:
> **[«Канал: scalar NaN Частота: any»](http://cloud-4.steamusercontent.com/ugc/29611747692376520/9AB947CBE7443F7D32A43DB60D8CD0EF5E398D87/)**
> * **Tourorist**: Это уже где-либо обсуждалось, или это вообще не проблема? У других игроков на одном из наших серверов проверял — вроде воспроизводиться повсеместно. До такой степени, что таким образом избавляемся от нежелательных товарищей в радиоэфире, вместо изъезженного «Нажми Alt+F4 чтобы %1». ☻
> * **Nkey**: Привет
> * **Nkey**: Да, баг
> * **Nkey**: надо пофиксить

**Comment by michail-nikolaev** [comment]
can't reproduce

**Comment by Tourorist** [comment]
Neither can I; seems to have resolved itself in v0.9.7.1 running on RC6 of CBA. :four_leaf_clover: 

Haven't confirmed with any other players yet, but when I do, I'll let you know if it's still an issue.
