### ISSUE TITLE
Allow players to change volume between different channels on the same radio.

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#918]

**Comment by kavinsky** [comment]
did u mean for channel 1: 20% and for channel 2: 60% volume?

**Comment by michail-nikolaev** [comment]
I think 90% for mail, 30%  for additional (like stereo settings)

**Comment by kavinsky** [comment]
oh, separate volume setting for main and additional

**Comment by dedmen** [comment]
#1011
