### ISSUE TITLE
ACE3 integration

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#923]
- ability to open radios in self-interation menu
- ability to use other person LR radio via 3D menu (also, should be possible without ACE3)
- replace MicroDAGR in TFAR with the ACE 3 alternative, if such exists
- **"Take radio"** – 3D action over a dead player

**Comment by michail-nikolaev** [comment]
* headphones integration (not implemented yet)

**Comment by CorruptedHeart** [comment]
TODO
- [ ] Open Radios via self-interaction
- [ ] Use another player's radio via interaction
- [ ] Use ACE 3's MicroDAGR (if ace 3 is loaded)
- [ ] Take radio on dead body interaction
- [ ] Headphones integration (I assume this will be for in vehicles?)

**Comment by Knight1981** [comment]
The 2nd point would be awesome!
"ability to use other person LR radio via 3D menu (also, should be possible without ACE3)"

It would be really cool if the "actual" (e.g. teamleader) can use the radio of the operator etc. :)

**Comment by BryanBoru** [comment]
+1 this! thanks!

**Comment by SzwedzikPL** [comment]
"Open vehicle radio via interaction menu in vehicles" @CorruptedHeart hm?
