### ISSUE TITLE
arma3 profilname with space at end cause TS3 spam "error"

### ISSUE THREAD

**Issue by havena** [michail-nikolaev/task-force-arma-3-radio#927]
A player with arma3 profilename end with space and the same name without space on TS3, ex :
A3 profilename : "name "
TS nickanme : "name"

cause TS3 spam "error" when trying to rename user after switch in TFAR channel (end space cause nickname is already in use).

Perhaps prevent rename if the "nickname" is the same at "nickname " ?

**Comment by michail-nikolaev** [comment]
thanks!

**Comment by dedmen** [comment]
#1003 is a duplicate but I used it in a commit so I'll close this one.
Fixed in 1.0
