### ISSUE TITLE
Zeus Forced interface, wanished binds

### ISSUE THREAD

**Issue by ArcanumSK** [michail-nikolaev/task-force-arma-3-radio#930]
You cannot control TFR from zeus forced interface. Binds just wanish from menu. Even defaults are not working. Direct is working all right. BUt you cannot press anything...

**Comment by michail-nikolaev** [comment]
which version? 0.9.7.1?

**Comment by michail-nikolaev** [comment]
probably this code not updated to new CBA:

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_processCuratorKey.sqf#L3-L12

**Comment by ArcanumSK** [comment]
Version 0.9.7.2

**Comment by ArcanumSK** [comment]
Hotfix would be nice ;)
