### ISSUE TITLE
0.9.7.1 RPT error task_force_radio_items\config.cpp

### ISSUE THREAD

**Issue by havena** [michail-nikolaev/task-force-arma-3-radio#931]
RPT error :
File task_force_radio_items\config.cpp, line 35: Config: ';' used as a separator in the array

**Comment by michail-nikolaev** [comment]
Thanks for info

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio_items/config.cpp#L36
