### ISSUE TITLE
LR communication interrupting

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#933]
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2919440&viewfull=1#post2919440

**Comment by dedmen** [comment]
Link is not valid anymore.

**Comment by dedmen** [comment]
Found it https://forums.bistudio.com/topic/159393-task-force-arrowhead-radio/?p=2844224 but video still down.
