### ISSUE TITLE
Hatchback sport handles like normal hatchback

### ISSUE THREAD

**Issue by DeliciousJaffa** [michail-nikolaev/task-force-arma-3-radio#936]
When using TFAR the hatchback sport handles like a normal hatchback rather than a hatchback sport.

**Comment by DeliciousJaffa** [comment]
Based on testing, this happens when only when TFAR is installed on the client, it handles correctly without TFAR / CBA on a server with TFAR & CBA installed. Potentially to do with when radios are "setup" on vehicles?

Originally noticed this issue on version 0.9.7 however it still appears to be happening in 0.9.7.3

**Comment by dedmen** [comment]
#827 #1190
Fixed in 1.0 build 188
