### ISSUE TITLE
TAB for LR works incorrect

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#937]
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2923581#post2923581

**Comment by GRUBES** [comment]
Able to reproduce this with any key, not just Tab. I rebound "LR Transmit" keybinding to several keys like "C" and still see this issue.

**Comment by GRUBES** [comment]
Duplicate of #845 ?

**Comment by dedmen** [comment]
Forum link not valid anymore

**Comment by BmanDesignsCanada** [comment]
I am not able to reproduce this in `1.-1.0.244`
Both Tab and "C" work fine

**Comment by dedmen** [comment]
Yes. Was fixed in  cecc67d3ef46cf125827b48b541448fdfbb1f60
