### ISSUE TITLE
SQF error on start

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#939]
23:22:25   Error Type Not a Number, expected Number
23:22:25 File task_force_radio\functions\fn_defaultPositionCoordinates.sqf, line 38
23:22:25 Error in expression <R_currentUnit;
p2 = eyePos this;

if (terrainIntersectASL[_p1, _p2]) then {
_l>
23:22:25   Error position: <terrainIntersectASL[_p1, _p2]) then {
_l>
23:22:25   Error Type Not a Number, expected Number
23:22:25 File task_force_radio\functions\fn_calcTerrainInterception.sqf, line 25

**Comment by dedmen** [comment]
Already solved long ago.
