### ISSUE TITLE
Change Radio Range for Short Wave Radio

### ISSUE THREAD

**Issue by TheToxitLP** [michail-nikolaev/task-force-arma-3-radio#949]
Hey,

I´m in a german police roleplay rlan für Arma 3. We want to use TFAR to communicate. 
But the 5km range with the AN/PRC 152 isn`t enough to talk. I have tried to change th "tf_range" in the task_force_radio_items file. If the range value is over 9000 I get this error:
![unbenannt](https://cloud.githubusercontent.com/assets/12240725/7460914/c3a48c04-f2a6-11e4-8bdc-d8233a41ea45.PNG)

Is there any opportunity to change the range?

Sorry for my bad english.

Greetings

ToXiT

**Comment by michail-nikolaev** [comment]
Hello.
Looks like you made some mistake in cfg file....

Also, you may change range by using SQL script - player setVariable
["tf_sendingDistanceMultiplicator", 2]
It will increase range twice.

2015-05-04 22:47 GMT+03:00 TheToxitLP <notifications@github.com>:
