### ISSUE TITLE
[Question] Development Guide

### ISSUE THREAD

**Issue by GRUBES** [michail-nikolaev/task-force-arma-3-radio#951]
Do you have a guide anywhere for developing and building the addon? I've installed the A3 Tools, but I'm failing to get a build to work. Any documentation exist that might be helpful?

**Comment by michail-nikolaev** [comment]
You need to use addon builder from A3 Tools to build pbos.
Also, VC Express will required to compile plugin.

Also, it is possible to just build task_force_radio_items.pbo and use debug mission with  rest code.
