### ISSUE TITLE
Set keybindings on controller

### ISSUE THREAD

**Issue by derdeagle** [michail-nikolaev/task-force-arma-3-radio#952]
First of all I wanted to thank you for your great work!

Second is: is it possible to set the keybindings for radio and lr-radio on a controller? If I take a look at the settings ingame I only see the possibilty to use keys from the keyboard but not from a controller.

Thank you in advance!

**Comment by michail-nikolaev** [comment]
You need to use some program to bind controller keys to keyboard.
