### ISSUE TITLE
Major FPS drop when playing as Zeus

### ISSUE THREAD

**Issue by Drezzo** [michail-nikolaev/task-force-arma-3-radio#953]
I'm making this ticket after seeing post on BI forum and reproducing the bug:
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2936337&viewfull=1#post2936337

TFAR Version: 0973

Mods:

    @cba_a3
    @tfar

Placed TFAR Modules:

    None, just the BIS ZEUS Game master module with setting: all addons including unofficial ones.

Description:

   Major FPS drop when using the movement keys as Zeus using latest stable tfar and cba. (- 30/40 FPS)
With TFAR version 097 + CBA R4 or without TFAR and CBA R4 normal FPS drop due to object loading.

Steps to reproduce:

  Place down a player on Altis and a Zeus Game master module. Press keybind to access Zeus interface and move camera with movement keys or arrowkeys. Notice high FPS drop with TFAR 0793 + CBA R6. 
Load same mission with TFAR version 097 + CBA R4 or just CBA R4 or R6 and notice normal FPS drop when moving as Zeus.

Where did the issue occur?

   Editor

**Comment by michail-nikolaev** [comment]
Hm.. Probably I know

**Comment by igorkiss** [comment]
i confirm this bug. Especially with ACE3 FPS drop is really noticeable (from 60 to 20) on my PC. Without enabled TFAR everything is ok.

**Comment by dedmen** [comment]
Is this still valid?
I'd say telling the Teamspeak plugin or position is the likely culprit here.

**Comment by kavinsky** [comment]
never notice a FPS drop with ZEUS and TFAR.

**Comment by dedmen** [comment]
I think I had that issue a few weeks ago when i tested ACRE :D But not with TFAR though. But i dont use Zeus that often.

**Comment by kavinsky** [comment]
happened to my yesterday with ACRE :P
