### ISSUE TITLE
Spaced channel name on TFAR module brokes positional voice

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#955]
Steps to reproduce:
1. Place _Require TFAR_ Module.
2. Set channel to a name with space/s
3. Leave password blank.
4. Enter in multiplayer game.

**Comment by dedmen** [comment]
Don't see how this could happen in 1.0. Only thing affected by ChannelName was seriousMode.. But that switched to using ChannelID internally. And no effect whatsoever on positional voice.
