### ISSUE TITLE
Vulnerable userconfig

### ISSUE THREAD

**Issue by BaerMitUmlaut** [michail-nikolaev/task-force-arma-3-radio#956]
For more info, read here:
http://forums.bistudio.com/showthread.php?192187-Userconfig-Vulnerabilities&p=2943475#post2943475

**Comment by michail-nikolaev** [comment]
@BaerMitUmlaut thanks, will check, We did some tests here, but need to recheck.

**Comment by kavinsky** [comment]
closing in favor of #1099
