### ISSUE TITLE
Speakers enabled on JIP brokes radio reception

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#957]
Steps to reproduce:
1. Inside a game: Turn on own radio speakers.
2. Disconnects from game (in my case was power shortage).
3. Join in progress and take a radio.
4. you can transmit but you cant receive from others till you turn radio speakers on and then off.

Using a PRC152

**Comment by kavinsky** [comment]
Confirmed, ill try to fix it.

**Comment by dedmen** [comment]
Kinda hard to reproduce. Maybe was already fixed in other 1.0 work. Need to retest in 1.0
