### ISSUE TITLE
Radio Screen is Black

### ISSUE THREAD

**Issue by agorapolis** [michail-nikolaev/task-force-arma-3-radio#960]
Hello,

Since the last update Arma 3 (1.46) the radio screen is black.
Here is a screen:
![2015-06-08_00001](https://cloud.githubusercontent.com/assets/2111927/8042508/f1a0437a-0e1f-11e5-9e79-216bb6540da8.jpg)

**Comment by michail-nikolaev** [comment]
yes, update will be soon

**Comment by agorapolis** [comment]
Ok, thanks

**Comment by ArMaTeC** [comment]
anarc164/anarc164.ext
anarc210/anarc210.ext
mr6000l/mr6000l.ext

will also need a change

**Comment by michail-nikolaev** [comment]
@ArMaTeC thanks
