### ISSUE TITLE
TFAR Frequencies module JIP Broken

### ISSUE THREAD

**Issue by Arcanum417** [michail-nikolaev/task-force-arma-3-radio#963]
When I set frequencies using TFAR Frequency module, it works only for those, who have been connected when mission starts. When someone reconnects or JIP, it will give him generated frequencies (even radio which droped from body is set to defaults generated frequencies)

**Comment by michail-nikolaev** [comment]
thanks for info

**Comment by ArcanumSK** [comment]
Any possibility, it can be fixed untill this sunday ?

**Comment by michail-nikolaev** [comment]
probably nope :(

**Comment by ArcanumSK** [comment]
Thx, I have been preping for bigger action and needed to know if I could count on these... Whatever I will let people handle it :D Good luck

**Comment by looterz** [comment]
It would be awesome if you could set this in the server config as well, default frequency and channel for SW & LR.

**Comment by ShiFoo** [comment]
Is there any workaround for this? I have tried using the TFAR API but it seems that the functions don't really work when the player joins (using TFAR_fnc_setPersonalRadioFrequency in a script in the init line of a player).

**Comment by michail-nikolaev** [comment]
@ShiFoo try to set values via script: (tf_freq_west and other - https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables )

**Comment by ShiFoo** [comment]
Maybe i need to be more precise: Imagine i have a platoon consisting of 2 squads. Each squad has two fireteams + pilots + armor group. I want everyone in each platoon and each squad to have the same frequencies. But Channel 1-8 in platoon should be different than channel 1-8 in squad. Yet it must be working with JIP and respawn. I tried to use the frequency module in the editor and sync them with each group. But this only works on mission start and not for JIP. Any idea?

**Comment by looterz** [comment]
If TFAR does have JIP support, it definitely doesn't work correctly. Until a patch is created to address this issue, I think you could implement your own code to support JIP & Respawn not wiping set default radio settings for units.

**Comment by michail-nikolaev** [comment]
Looks like it is issues in Arma... Group frequencies are stored inside Group object. And looks like its state is not synced in case of JIP for some reason.

**Comment by michail-nikolaev** [comment]
bwt, are sync works without module? In such case each squad will have own generated freqs.

**Comment by ShiFoo** [comment]
My unit is switching the structure of the platoon which requires the seperate frequencies. Before that we only had to use the TFAR - Enforce Usage and set the "Same SW frequencies" and "Same LW frequencies" to YES. Now, setting both to "NO" and using the Frequency module, it has only worked (only at mission start) when i synced it with every playable unit and set the mode to "Synced object only". It has not worked at all with "Synchronized grouped object only". Currently: either everyone has the same frequency or everbody has scrambled frequencies...

**Comment by dedmen** [comment]
Is this still valid? Or has the issue been fixed on Arma side?

**Comment by dedmen** [comment]
isGlobal = 2; //2 for persistent global execution

**Comment by TheMagnetar** [comment]
While for players that join the mission from start I can configure radio channels correctly through script, the same cannot be said for those joining later (JIP). I systematically get: 

> Error in expression <count (assignedItems TFAR_currentUnit);
> _result>
> 22:47:04   Error position: <_result>
> 22:47:04   Error Undefined variable in expression: _result
> 22:47:04 File task_force_radio\functions\fn_activeSwRadio.sqf, line 25
> 22:47:04 Error in expression <y = _this select 2;
> 
> _lr = if (typename _radio == "STRING") then { false }else{t>
> 22:47:04   Error position: <_radio == "STRING") then { false }else{t>
> 22:47:04   Error Undefined variable in expression: _radio
> 22:47:04 File task_force_radio\functions\fn_SetChannelFrequency.sqf, line 8
> 22:47:04 Error in expression <count (assignedItems TFAR_currentUnit);

I have  also tried to delay the execution of the script that configures the frequencies and channels to 10s after start. No luck.

**Comment by dedmen** [comment]
Make sure the Module is executed for each JIP Player. 
Remove warning of frequency already set for JIP players.
Skip setting tf_xx_frequency if isNil and isJIP (https://community.bistudio.com/wiki/didJIP)

**Comment by dedmen** [comment]
Should be fixed in 1.0. If not just open a new issue.
