### ISSUE TITLE
Some people get it working / others not....

### ISSUE THREAD

**Issue by tswg86** [michail-nikolaev/task-force-arma-3-radio#964]
I run a Arma 3 Life server, " Big City Life Teamspeak: TS.a3lbigcitylife.com Website: www.a3lbigcitylife.com ". We have a issue, we are running TFR version 0.98 and some people get it to work and others can't. Everyone who joins the server is able to use TFR to talk to people near them but almost nobody but me and the other owner are able to use the functions such as using the radios. It is a huge problem and we could really use some help. If you are interested in helping and would like to view the mission we are running hop on teamspeak. 

Thank you,
South

**Comment by kavinsky** [comment]
Can you provide which addons are you using and an RPT Log of failing clients?

Im using that version on my community and have no problems (+25 players).

**Comment by kavinsky** [comment]
@tswg86 any update?
