### ISSUE TITLE
task_force_radio_items added to mission.sqm

### ISSUE THREAD

**Issue by whiztler** [michail-nikolaev/task-force-arma-3-radio#966]
Sometimes "task_force_radio_items" is added to the mission.sqm, even though there are no TFAR items placed in the editor. This creates an unnecessary dependency.

**Comment by jonpas** [comment]
That's an Arma problem, it will add whatever you are running during mission saving.

**Comment by whiztler** [comment]
Thanks for your quick reply.. It only seems to happen with certain missions

**Comment by CorruptedHeart** [comment]
So it doesn't happen every time? Usually if it happens it's because there is an updating of a Base class.

Usually visible in the rpt. "updating of Base class xxx to yyy by zzz" or similar message.

**Comment by whiztler** [comment]
It's re my Wolfpack campaign (https://github.com/whiztler/Wolfpack) It only happens day 5,6,10. No idea why. I went through the SQM thoroughly and could not find any reason why it happens to those missions. 

The Wolfpack missions are only CBA_A3 dependent, TFAR (/ACRE/ACE/cTAB) are optional. Everything that involves addons is added with scripts (based on mod detection).

It only happens with TFAR (`task_force_radio_items`), so I am not sure if this is (only) a BIS issue.

**Comment by CorruptedHeart** [comment]
Are there vehicles in those days? I will take a look later today and see what potentially could cause the requirement being inserted.

**Comment by whiztler** [comment]
Yes, vehicles have been pre-placed

**Comment by dedmen** [comment]
Fixed with 1.0. There are no Modules anymore and task_force_radio_items doesn't exist anymore anyway
