### ISSUE TITLE
Virtual arsenal resets LR frequency

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#970]

**Comment by michail-nikolaev** [comment]
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2955962#post2955962

**Comment by rogerxxxx** [comment]
I noticed this bug as well.  (I'm now subscribed this bug issue.)

Especially would be nice to have frequency presets within the userconfig radio_settings.hpp Client side section.  (ie. ShortRange C1="128.150" C2="250.150", ...; LongRange C1="800.125", C2="802.150", ...)

**Comment by dedmen** [comment]
Fixed in #1150
