### ISSUE TITLE
Cant hear anyone over 100 Clients per Channel with TF

### ISSUE THREAD

**Issue by etrex2k4** [michail-nikolaev/task-force-arma-3-radio#971]
Unfortunately, no one can hear once more as 100 clients , do you have a solution to this problem ? with 99 clients it works with no problems . We have a 150 Slot Server

**Comment by michail-nikolaev** [comment]
It is TS issue - check channel settings

**Comment by etrex2k4** [comment]
http://www.pic-upload.de/view-27510332/TS_settings.png.html

**Comment by etrex2k4** [comment]
Is it possible that the problem is the codec quality? the Teamspeak Server run on a Intel Xeon machine,

**Comment by michail-nikolaev** [comment]
Using your client TS3:
Edit Server --> "Misc" Tab --> See the value in "Min clients in channel before silence"

**Comment by etrex2k4** [comment]
Thanks a lot! This solved the problem!

**Comment by etrex2k4** [comment]
do you have a paypal adress for me?

**Comment by michail-nikolaev** [comment]
nope :) donate to red cross :)

**Comment by etrex2k4** [comment]
i will honor you bigger in our Credits!
