### ISSUE TITLE
Possible plugin memory leak

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#975]

**Comment by dedmen** [comment]
Should retest after i added teamspeak freeMemory guards in 1.0

**Comment by dedmen** [comment]
76e9f04 ? #825 ?

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/ts/src/Clunk.h#L53
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/ts/src/Clunk.h#L39
Fixed in 1.0

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/ts/src/plugin.cpp#L2242
memory Leak. Never deleted.. Though small leak only. But that almost provoked a bigger leak in 1.0

**Comment by dedmen** [comment]
can't confirm any more leaks. And as almost everything was rewritten the likelyhood for a leftover leak is near 0.
