### ISSUE TITLE
RHS:USAF vehicles

### ISSUE THREAD

**Issue by BryanBoru** [michail-nikolaev/task-force-arma-3-radio#976]
Running the latest versions of CBA, TFAR and RHSUSAF
Many of the RHSUSAF vehicles are not recognized to have LW radios. The includes many of the HUMVEEs which obviously would have LW radios onboard. It does work on many of the Helicopters, however.
I am unsure if this is something TFAR configs need to address or the RHS configs.

**Comment by kavinsky** [comment]
on this case, RHS should address this issue.
#737

**Comment by BryanBoru** [comment]
thanks, I couldn't find the issue you lssue # you linked.
