### ISSUE TITLE
Channels in radio seem to switch random

### ISSUE THREAD

**Issue by dedmen** [michail-nikolaev/task-force-arma-3-radio#980]
Using PRC-152 with Channel 2 as additional channel.
When changing the frequency sometimes it just doesnt save it. it also once reset my frequency from 337 to 333 which makes no sense. Also other people are not transmitting on the channel they thought they were on.
Channel switching via Numpad works fine.
Video here: http://www.twitch.tv/dedmenmiller/c/6989626
showing the random channel switching.
After dropping everyones radio and getting a new one it works fine again.

Sorry for that kinda crappy looking report i have to get back into the mission.

I suppose that channel switching in the radio interface switches through an array which doesnt get cleared properly when setting a frequency.

**Comment by cptnnick** [comment]
How are you assigning the radios to your players? Seems like a classic
duplicate radio or JIP issue.

**Comment by dedmen** [comment]
Yep i just heard that from the mission builder... he had his Loadouts in the init field of every unit, which should not be done for multiple reasons but some people still do it. Why was there no fix for the duplicate radio issue yet?

**Comment by cptnnick** [comment]
Could you post an example of a loadout? line? It sounds like initialized
radios are handed out instead of the base class name. Is your mission maker
copy pasting virtual arsenal loadouts? That is something that can't be
fixed mod-side.

**Comment by dedmen** [comment]
yeah hes copying Arsenal loadouts (this linkItem "tf_anprc152_1")

**Comment by cptnnick** [comment]
Yeah he's assigning everyone a duplicate radio, see the _2. Use TF_anprc152
and you'll be done, just tell your mission maker to look out when making
loadouts.
