### ISSUE TITLE
Activating with caps lock uses default arma 3 Comms

### ISSUE THREAD

**Issue by Pozdrav** [michail-nikolaev/task-force-arma-3-radio#981]
I seem to have encountered this issue where when I use capslock it uses the default arma 3 communication, i've made sure I've followed the instructions on the main page exactly but I can't figure out what is wrong with it, the other controls don't work either but I'm 100% sure the addon is loaded because if I join I can hear the little radio sound and if I'm not on a teamspeak server it says Pipe Error 6 and I have all the TFAR radios. 
I've tried reinstalling etc but it doesn't work instead of the Transmitting dialogue in TFAR it's just the little Communication icon. It's extremely weird as my friend used exactly the same version as me yet his works perfectly.

**Comment by kavinsky** [comment]
1. You should unbind the default PTT key on ArmA3 controls.
2. Have you checked your teamspeak3 have the tfar plugins installed and activated?

**Comment by Pozdrav** [comment]
![i60xars](https://cloud.githubusercontent.com/assets/11020750/8894676/92cd4e3e-33b7-11e5-9bf9-ee7433bb93eb.png)
This is my teamspeak plugins, and you can see it's activated and has the little activation message by my Name the 'Connected N Play N P:0.9.8 A: ' So I don't think it is that.

This is my arma 3 PTT config in the settings.
![bwe7o3c](https://cloud.githubusercontent.com/assets/11020750/8894721/f5ab767e-33b8-11e5-9004-f4ca83d8af8e.png)

Just incase my teamspeak config
![ee6k5qe](https://cloud.githubusercontent.com/assets/11020750/8894723/201b517c-33b9-11e5-92a2-f3e4474d7155.png)

I'm pretty stumped as to what the problem is. I've re-installed the plugin and addon to prevail either.

**Comment by Pozdrav** [comment]
Issue is fixed I wasn't aware that I'd accidently replaced the CBA version that comes with TFAR, you must use the Candidate 7 Hotfix2 for it to be able to function. Thanks for your help anyway it's working perfectly now.
