### ISSUE TITLE
Win10 support

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#983]

**Comment by sancron** [comment]
Sorry to ask, but is there an issue with Win10 at all? On my small Unit, we have serveral people including me using WIndows 10 with TFAR. And we don't noticed a problem at all yet.

**Comment by michail-nikolaev** [comment]
@sancron I hope so :)

**Comment by xJenny99x** [comment]
Using win 10 here, no problems. Working 100% as intended!

**Comment by Gurkengewuerz** [comment]
can only agree with @xJenny99x
