### ISSUE TITLE
objects in synced triggers and LR settings

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#988]
https://dl.dropboxusercontent.com/u/34537696/SHQ_MissionTemplate_AAF.Altis.rar

**Comment by michail-nikolaev** [comment]
https://forums.bistudio.com/topic/159393-task-force-arrowhead-radio/?p=2897688

**Comment by dedmen** [comment]
Two bad links.. I'll just close this
