### ISSUE TITLE
using callExtension with empty string causes apphang

### ISSUE THREAD

**Issue by X39** [michail-nikolaev/task-force-arma-3-radio#997]
to reproduce:
"task_force_radio_pipe" callExtension ""

dll seems to be not happy with empty strings

**Comment by michail-nikolaev** [comment]
Hm.. But how to cause TFAR to send empty string?

**Comment by X39** [comment]
its not TFAR sending empty strings anywhere (at least i did not found any way to)
however, the so callen "hackers" aka script kiddies would love to use this bug to wipe out a server entirely

a simple ```if(strFnc[0] == '\0') return;``` should do it and would prevent deadly harm
