### ISSUE TITLE
Move player on TS

### ISSUE THREAD

**Issue by breaup** [michail-nikolaev/task-force-arma-3-radio#998]
Anyone can point me in the right direction to have this move my players to a designated channel on teamspeak when they join in game then move them back?

Cheers

**Comment by ACyprus** [comment]
Look for **Serious Mode** under **Operation Modes** at the main website, or:

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/README_EN.md


To change the channel details, look up the variable to set here:

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables

**Comment by breaup** [comment]
thanks alot
